### ISSUE TITLE
Afiliadas adicionadas

### ISSUE THREAD

**Issue by altboy** [olavopeixoto/plugin.video.brplay#100]
Pelo que estava vendo no endereço da central de ajuda da Globo, foram adicionados outras afiliadas, link: http://centraldeajuda.globo.com/Globoplay/Informacao-Tecnica/noticia/2015/10/em-que-cidades-e-possivel-assistir-programacao-da-globo-ao-vivo.html

Segue descrição no site:

Em que cidades é possível assistir à programação da TV Globo ao vivo no Globoplay?

Em que cidades é possível assistir à programa
Na web e nos aplicativos móveis, a programação ao vivo no Globoplay pode ser acessada nas regiões metropolitanas do Rio de Janeiro, São Paulo, Recife e Minas Gerais; além dos estados do Amapá, Pará, Amazonas, Acre, Roraima, Rondônia e das cidades de Brasília, Florianópolis, Goiânia, Salvador e São Luiz.

Além disso, você pode assistir às íntegras e aos trechos dos programas, mesmo estando fora da sua cidade. Já a programação ao vivo é transmitida de acordo com o lugar em que você se encontra, não sendo possível assistir à programação ao vivo de outra cidade.

Gostaria de saber se há previsão para adicionar as outras afiliadas no brplay??

Grato!

**Comment by olavopeixoto** [comment]
Incluido na ultima versao 0.0.27

**Comment by altboy** [comment]
Olá bom dia

Funcionando perfeitamente, grato pela disposição em adicionar estás afiliadas.

Mas... gostaria de pedir um favor...rs

Estava vendo em um fórum específico de TV e gostaria só de uma confirmação e claro se confirmar a adição também, segundo o que vi a listagem de afiliadas com programação ao vivo no globoplay é maior, segue:

SP, RJ, MG, PE, **Cariri**, no DF, no AM, nas cidades de Belém (PA), Campinas, Sorocaba, Itapetininga, São Luís, Bauru, São José do Rio Preto (SP), Florianópolis (SC), Salvador (BA), Curitiba (PR), Vitória (ES), Fortaleza (CE), Porto Alegre (RS) e Natal (RN) e nos estados de AC, RR, RO, AP, GO.

Poderia verificar ou devo abrir outro issue?

Grato!

**Comment by olavopeixoto** [comment]
Adicionado as capitais que você mencionou.
Também adicionei as opções para buscar a sua cidade pelo seu IP (como o globoplay funciona normalmente) e adicionar as suas próprias coordenadas.
Dessa forma você pode adicionar a cidade que você quiser, só precisa configurar a latitude e longitude da localização que você deseja.
Por exemplo:
Bauru:
Latitude: -22.314207
Longitude: -49.065316

Pode usar o Google Maps para buscar as coordenadas

**Comment by altboy** [comment]
Valeu Olavo

Grato pela orientação.

**Comment by altboy** [comment]
Olavo boa tarde

Fiz a busca pelas coordenadas e deu super certo, porém gostaria de fazer algumas observações:

* Você informou que poderia fazer a busca pelo IP, aqui só consegui fazer a busca pelas coordenadas, procurei a opção pelo IP e não encontrei nada, poderia me orientar?

* Consegui acessar as seguintes afiliadas pelas coordenadas:

1. EPTV Campinas
2. TV TEM Bauru
3. TV TEM Sorocaba
4. TV TEM Itapetininga

* Estás afiliadas não consegui acessar mesmo colocando as coordenadas das cidades referidas:

1. EPTV Central -> Coordenadas da Cidade de São Carlos
2. EPTV Ribeirão Preto -> Coordenadas da cidade de Ribeirão Preto
3. EPTV Sul de Minas -> Coordenadas da cidade de Varginha
4. TV TEM São José do Rio Preto -> Coordenadas da cidade de São José do Rio Preto
5. TV Fronteira -> Coordenadas da cidade de Presidente Prudente
6. TV Vanguarda -> Coordenadas da cidade de São José dos Campos/Taubaté
7. TV Tribuna -> Coordenadas da cidade de Santos
8. TV Diário -> Coordenadas da cidade de Mogi das Cruzes

Lembro que apesar das informações não oficiais do fórum onde consultei, pelo menos sei que a EPTV e TV TEM tem programação ao vivo pelo globoplay, apesar que na central de ajuda do globoplay não consta estas cidades.

Grato pela atenção.

**Comment by olavopeixoto** [comment]
Pra usar a busca por IP é só escolher “Auto”/“Automático”. O addon fará a busca pela localização do seu IP atual.
Se as coordenadas não encontraram a afiliada ela não está disponível nesta API.
