### ISSUE TITLE
Somente canais ao vivo funcionam (autenticação)

### ISSUE THREAD

**Issue by helviojr** [olavopeixoto/plugin.video.brplay#101]
Tenho dois usuários diferentes para Globosat Play e para Globo Play. Não sei se tem a ver, já que o Addon permite a configuração separada. Se eu tentar usar o browser, serei obrigado a fazer logoff de um para entrar no outro (pois faz cache/mantém cookie da autenticação Globo.com), mas ambos os sites estão funcionais..

Na opção 'Canais sob Demanda' o erro é:

ERROR:     return get_credentials()[0]
ERROR:   File "C:\Users\Casa\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\auth_helper.py", line 12, in get_credentials
ERROR:     credentials = authenticator().authenticate(username, password)
ERROR:   File "C:\Users\Casa\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\auth.py", line 38, in authenticate
ERROR:     self.credentials = self._authenticate(username, password)
ERROR:   File "C:\Users\Casa\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\auth.py", line 82, in _authenticate
ERROR:     credentials = cookies[self.GLOBOSATPLAY_TOKEN_ID]
ERROR: KeyError: 'GST'
ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.brplay/?action=vodChannels
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.brplay/?action=vodChannels) failed

Em 'Destaques Globosat', consigo navegar nas diversas listagens (novidades, mais vistos etc., pois provavelmente não usa autenticação), mas não consigo executar (ao tentar abrir um seriado):

ERROR:     episodes = scraper.get_card_episodes(id_program, id_season)
ERROR:   File "C:\Users\Casa\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\scraper_vod.py", line 205, in get_card_episodes
ERROR:     next = result['next'] if 'next' in result else None
ERROR: TypeError: argument of type 'NoneType' is not iterable
ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.brplay/?action=openvideos&id_globo_videos=None&provider=globosat
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.brplay/?action=openvideos&id_globo_videos=None&provider=globosat) failed

E, ao tentar executar alguns:

vários erros:
ERROR: NEWADDON Unknown Video Info Key "....."

e o erro:
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.brplay/?action=playvod&provider=globosat&id_globo_videos=8160881&meta=.....

Usando o branch 'master' e o Kodi Leia.

**Comment by olavopeixoto** [comment]
Tinha um bug nas credenciais separadas, estava misturando para os serviços. Eu não tenho as credenciais separadas então é difícil de testar 100%.
Verifica se a ultima versão da master (0.0.28) resolve o seu problema.

**Comment by helviojr** [comment]
OK. Funcionaram canais ao vivo Globo e Globosat. Programas sob demanda da Globo não funcionaram (Video não encontrad

**Comment by helviojr** [comment]
(desculpe, cliquei em fechar sem querer)

OK (0.0.32). Funcionaram canais ao vivo Globo e Globosat (problema original). 

Programas _sob demanda da Globosat_ **funcionaram vários**. 

Mas tive dificuldade com série _sob demanda do Universal Channel_ (**conteúdo protegido por DRM**, inputstream.adaptive), mas estou usando Leia e inputstream.adaptive está habilitado. E, sim, tenho acesso ao canal e a esse conteúdo na web (Globosat Play). Não testei todos os canais:
`ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.brplay/?action=playvod&provider=globosat&id_globo_videos=8135338&meta=%7B%22...`

Programas _sob demanda da Globo_ **não funcionaram** (Informações do vídeo não encontrada).
`ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.brplay/?action=playvod&provider=globoplay&id_globo_videos=7517719&meta=%7B%22tvshowtitle...`

É só o que tem no log do Kodi, além de inúmeras repetições das linhas abaixo (acho que só de navegar no addon, esses erros são gerados, mas não tenho sequer certeza de que se trata do addon):
```
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "brplayprovider"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "id"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "id_cms"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "live"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "logo"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "name"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "slug"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "vod"
02:02:49.795 T:7376   ERROR: NEWADDON Unknown Video Info Key "adult"
```

Não sei se os problemas têm a ver com o problema inicial ou se já há Issues abertos para eles. Fique à vontade para fechar este, se for o caso.

**Comment by helviojr** [comment]
Os erros de DRM (Universal) acontecem sob demanda e ao vivo também, mas é uma questão separada #75

**Comment by olavopeixoto** [comment]
O log de debug é uma opção separada nas configurações do brplay e do Kodi. Ambos devem estar habilitados para gerar a informação completa.
Habilite no settings do addon e no settings do Kodi e veja se consegue mais informações do erro.

**Comment by Thicoxxi** [comment]
Olá, Olavo Peixoto. Tenho um raspberry pi rodando libreelec instalei o aadon na versão 0.0.34 que peguei do repositório, e reparei que para conteudo ao vivo esta funcionando legal, porém para os seriados (on demand) ele trava as vezes e o audio para de funcionar. Tenho nessa mesma estrutura instalado netflix e amazon vod (prime videos). Além do addon tbm estar misturando todas as temporadas de seriados por exemplo.

**Comment by thorandrade** [comment]
> Olá, Olavo Peixoto. Tenho um raspberry pi rodando libreelec instalei o aadon na versão 0.0.34 que peguei do repositório, e reparei que para conteudo ao vivo esta funcionando legal, porém para os seriados (on demand) ele trava as vezes e o audio para de funcionar. Tenho nessa mesma estrutura instalado netflix e amazon vod (prime videos). Além do addon tbm estar misturando todas as temporadas de seriados por exemplo.

Desculpa usar essa área, sei que está incorreto, mas você consegue usar o amazon vod em resolução maior que 540p e sem a lentidão para carregar os menus?

**Comment by Thicoxxi** [comment]
Olá,
Estou conseguindo, usar sim ele funciona em HD normalmente.

Em dom, 12 de abr de 2020 00:57, thorandrade <notifications@github.com>
escreveu:
