### ISSUE TITLE
Configuration - disable adaptative stream

### ISSUE THREAD

**Issue by rokam** [olavopeixoto/plugin.video.brplay#105]
Hi Olávo,

I think it would be better for you plugin if the configuration stands for enable adaptive stream.
That way, you won't confuse the user with the check/uncheck UI.

**Comment by rokam** [comment]
PR: #106 should do the job.

**Comment by olavopeixoto** [comment]
Thank you for the pull request, I have not merged since I changed the codebase but I applied your changes.
