### ISSUE TITLE
Canal Globo sumiu

### ISSUE THREAD

**Issue by pathamo1** [olavopeixoto/plugin.video.brplay#107]
Hoje, 03 de agosto de 2020, não consegui mais encontrar qualquer afiliada para assistir. Os canais globosat seguem funcionando normalmente. 

Já fiz teste mudando de afiliada e também deixando todos disponíveis e não tive sucesso.

Limpei o cache e não tive sucesso.

Reinstalei o addon e não tive sucesso também.

P.S  Quando eu logo no site ou app da Globo play, consigo assitir normal o canal.

Testes foram feitos Kodi 18 Leia no Smartphone e TV box.

**Comment by digaogt** [comment]
Eu tenho uma pergunta que pode parecer idiota mas é bastante pertinente: você está tentando assistir ao canal Globo diretamente do Brasil? Caso esteja fora do Brasil, recomendo o uso de VPN senão a Globo não roda de nenhum jeito pq eles identificam o IP local.
Uma sugestão seria de você limpar as configurações e cache manualmente, diretamente na pasta do addon e iniciar do zero, pq mesmo que vc apague o addon essas configurações ainda permanecem (isso partindo da premissa que você consegue assistir através da página deles diretamente).

Sucesso!

Rodrigo

**Comment by pathamo1** [comment]
Rodrigo, eu estou no Brasil! Eu repeti o processo de limpar o cache e dessa vez usei também o Indigo (addon de manutenção) para limpar todo o cache do Kodi de forma geral. Mesmo com todas essas novas tentativas, ainda não obtive sucesso. 

O problema aparaceu ontem, segunda(03), pois até domingo de madrugada todos os canais globo estação disponíveis. Como eu já havia dito o problema surgiu nos meus dois dispositivos Android. 

![Screenshot_20200804-015012_Kodi](https://user-images.githubusercontent.com/28604497/89254712-2ead4580-d5f6-11ea-8236-364163a2b802.jpg)

![Screenshot_20200804-015036_Kodi](https://user-images.githubusercontent.com/28604497/89254726-3e2c8e80-d5f6-11ea-83e5-ba957521feae.jpg)

![Screenshot_20200804-015210_Kodi](https://user-images.githubusercontent.com/28604497/89254747-4ab0e700-d5f6-11ea-9e04-92563cd774d6.jpg)

**Comment by olavopeixoto** [comment]
O problema é na API de EPG da globo.
https://api.globoplay.com.br/v1/epg/{data}/praca/{code}
Ela está instável e retornando erro (500) em alguns momentos e funcionando em outros de forma intermitente.
Vou colocar um tratamento de erro para exibir o canal sem a informação de EPG em caso de erro enquanto procuro uma solução alternativa

**Comment by olavopeixoto** [comment]
Testa a ultima versão (0.0.43) por favor pra ver se o problema resolveu pra você

**Comment by pathamo1** [comment]
Olavo, hoje o canal já apareceu novamente. Eu salvei como favorito para caso venha a sumir novamente quando eu for abrir a aba 'Live' ou 'Canais ao vivo'. Acredito que o canal salvo nós favoritos deva ficar visível mesmo com erro da EPG. 

Por esse motivo, eu adio o teste para a versão anterior. Mas caso volte a acontecer, eu o faço.

Mas vejo que uma atualização no addon é super necessária pra corrigir isso. 

Obrigado e valeu!!

![Screenshot_20200804-090732_Kodi](https://user-images.githubusercontent.com/28604497/89298253-6f7b7d80-d63b-11ea-89be-01ed02f70d09.jpg)

![Screenshot_20200804-092048_Kodi](https://user-images.githubusercontent.com/28604497/89298276-7e623000-d63b-11ea-8627-a982c406ba88.jpg)
