### ISSUE TITLE
Conteúdos com DRM apresentam falha na reprodução (Vídeo e Áudio)

### ISSUE THREAD

**Issue by ThaBozz** [olavopeixoto/plugin.video.brplay#108]
Ao tentar reproduzir conteúdos com DRM sob demanda, o vídeo dá uns pulos e o áudio para de vez. Testado na versão 0.0.34 do add on, CoreELEC 9.2.4.2, hardware Khadas VIM3L.

**Comment by olavopeixoto** [comment]
é um bug antigo do inputstream.adaptive do Kodi, por enquanto não tenho muito o que fazer.

https://github.com/peak3d/inputstream.adaptive/issues/130
https://github.com/peak3d/inputstream.adaptive/issues/184

**Comment by ThaBozz** [comment]
Obrigado pela resposta. Espero que eles acabem arrumando, porque de
resto o add-on está funcionando bem.

**Comment by olavopeixoto** [comment]
resolvido na versão 1.08
