### ISSUE TITLE
On Demand, fechando após 20 minutos. 

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#11]
Utilizando o Kodi 17.3 junto ao plug-in 0.10   canais Live estão rodando legal em modo adaptive, porém os vídeos on demand chegaram em um certo minuto da exibição trava ou reinicia... Como resolvo esse problema?

**Comment by olavopeixoto** [comment]
Os vídeos on demand devem funcionar corretamente no modo Auto, pode fazer esse teste?

**Comment by diegopeixotostitch** [comment]
Mesmo no modo auto! Se adiantar o vídeo além de 20 minutos ele para... E sai para o menu, já fiz testes no jarvis, 17.3, .4 , SPMC.

**Comment by diegopeixotostitch** [comment]
Plugin.video.brplay  em modo adaptive, não fica com imagem HD, na versão 17.4. 
Galera não deixe o addon morrer, é o melhor app do Brasil esse...

**Comment by olavopeixoto** [comment]
Esta funcionando normalmente pra mim.
Kodi 17.4: Adaptive Redirect, Adaptive Downloader, Adaptive Redirect Buffered
Testei na Fire TV Stick - Android 5.0

Todos se adaptam ao bitrate e sobem a resolução de acordo com a velocidade/delay do download e chegam a resolução máxima disponível eventualmente.

**Comment by diegopeixotostitch** [comment]
Estava olhando e realmente as novelas, se adiantar o vídeo acima dos 20 minutos, add-on fecha...

**Comment by diegopeixotostitch** [comment]
Verificar on demand da rede globo nova na íntegra...

**Comment by diegopeixotostitch** [comment]
Verificar on demand da rede globo novela* na íntegra...

**Comment by olavopeixoto** [comment]
Avançar e retroceder video é uma coisa que nunca tento porque sempre da problema.
Vou fazer mais experimentos com isso, mas em geral não é uma boa experiência, o player do Kodi é muito fraco nesse ponto, na minha opinião.
Fechar o addon com certeza é um bug, vou avaliar.

**Comment by diegopeixotostitch** [comment]
Qual player usa...? Ou versão do kodi?

**Comment by olavopeixoto** [comment]
Pode fazer o teste no Krypton e Leia com a versão 0.0.14?
O plugin nativo "inputstream.adaptive" tem que estar habilitado

**Comment by diegopeixotostitch** [comment]
Fiz os testes na versão 0.0.14, percebi o seguinte cenário utilizando o Kodi 17.4 :

* Problema no encerramento da transmissão em 5 minutos no modo auto foi sanado ;🔚
* Transmissão após alguns minutos, apresenta lentidão de quadros e perda de som em modo auto e adaptive; teste realizado com cabo de rede. Internet de 100mb ;🚨
* Novelas após o avanço com intervalos de 10 minutos, após os 20 trava. 🚨 não realizei os testes vendo naturalmente, sem avançar.

**Comment by Valcamonicos** [comment]
No meu caso o problema dos 5 minutos continua , a url da globosat ou globoplay mudam o token a cada 300 segundos será que é possível adaptar um script que automatize isso de forma eficaz ?

**Comment by olavopeixoto** [comment]
Isso é feito automaticamente pelo Kodi e, no caso do adaptive player, o próprio proxy é responsável por manter a sessão.

No caso do Krypton e Leia (Kodi >= 17) a forma de resolver o problema é habilitar o plugin "InputStream.Adaptive"

**Comment by Valcamonicos** [comment]
Olá Olavo , realmente resolveu muito obrigado , estou querendo rodar as urls da globo e globosatplay fora do kodi eu consigo captar a url ja com o token mas com esse problema dos 5 minutos não é possível você poderia me ajudar ? eu iria criar um servidor em e compartilhar com a Família os canais Globosat , Valeu ....

**Comment by olavopeixoto** [comment]
Acredito que você saiba que isso é ilegal, por favor não me peça ajuda nem discuta sobre nada ilegal aqui neste site.

Para duvidas sobre o seu plano e como o compartilhar entre em contato com a sua operadora.

**Comment by Valcamonicos** [comment]
Ok Olavo , proibido seria fazer o uso comercial mas sem problema , é que você não deve morar no Brasil , não deve ganhar pouco e pagar caro em tudo , muito Obrigado ....
