### ISSUE TITLE
Canais Telecine

### ISSUE THREAD

**Issue by danilo759** [olavopeixoto/plugin.video.brplay#111]
Olavo, 

Em primeiro lugar, obrigado pelo excelente plugin. Os canais Premiere funciona com imagem melhor que no aplicativo GE. Fantástico.

Gostaria de saber se existe a possibilidade de adicionar o conteúdo da Rede Telecine?

**Comment by olavopeixoto** [comment]
É possível implementar o Telecine sim, vou investigar melhor o tipo de proteção pra ver se é compatível com o Kodi.
Eu dou prioridade a canais ao vivo porque em geral os Apps oficiais são bons pra VOD e fracos pra TV ao vivo. No caso do telecine não existe canal ao vivo pela internet, somente VOD.

**Comment by danilo759** [comment]
Obrigado pelo retorno, Olavo.
Será de muita utilidade se for possível.

Grande abraço!

**Comment by danilo759** [comment]
> 
> 
> É possível implementar o Telecine sim, vou investigar melhor o tipo de proteção pra ver se é compatível com o Kodi.
> Eu dou prioridade a canais ao vivo porque em geral os Apps oficiais são bons pra VOD e fracos pra TV ao vivo. No caso do telecine não existe canal ao vivo pela internet, somente VOD.

Depois nos avisa como anda esse tópico.

Abs.

**Comment by olavopeixoto** [comment]
Implementado na última versão
