### ISSUE TITLE
Bão demais!

### ISSUE THREAD

**Issue by heavenblest** [olavopeixoto/plugin.video.brplay#113]
Funcionou blzinha no Android TV... agora o globoplay tem os canais ao vivo, mas quem é assinante via operadora continua dependendo do globosatplay para assistir os canais fechados. Como não tem app do globosatplay para Android TV, o BR Play fez o trabalho com perfeição! (Só precisa ativar o inputstream adaptive pros canais com DRM pegarem. Até agora não tive problema...)

Parabéns!

**Comment by olavopeixoto** [comment]
👍🏻 obrigado

**Comment by heavenblest** [comment]
Teve uma hora que a lista de canais sumiu... acessei pelo navegador para verificar se não era erro no servidor, tava normal. No outro dia eu acessei o Live TV de novo e ela voltou. Será que é alguma proteção anti-bot deles lá?

**Comment by danilo759** [comment]
As vezes isso acontece mesmo, mas tenho quase certeza que é alguma instabilidade no acesso aos serviços da API onde o Olavo consulta, pois, se vc aguardar poucos segundos, tudo é carregado.

**Comment by olavopeixoto** [comment]
Aqui não aconteceu ainda mas eu estou usando a API antiga da globo que tem informações que não existem na nova API, é possível que ela falhe ou deixe de funcionar totalmente em algum momento.
A ultima falha reportada foi na API de EPG, na ocasião eu atualizei o código para carregar os canais sem o EPG caso desse problema. A API acabou voltando a funcionar.
Caso aconteça novamente com você me manda o log pra eu entender onde esta o problema. Mas use a versão mais recente do addon.

**Comment by danilo759** [comment]
Tranquilo, Olavo.
Estou usando sim a última versão com TNT Play. Legal saber que vc já tem uma saída pra quando desativar de vez. Grato por sempre responder quando possível e compartilhar conosco seu trabalho. Estou a disposição pra ajudar, se precisar.

Abs.

**Comment by heavenblest** [comment]
Na 0.0.34 até agora não sumiu nenhuma vez... vou voltar com a 0.0.46 para registrar o log.

**Comment by heavenblest** [comment]
A 0.0.47 não deu erro, a lista não sumiu nenhuma vez...
Era algum problema com a 0.0.46 mesmo.
