### ISSUE TITLE
Tela de informações aparecendo aleatoriamente

### ISSUE THREAD

**Issue by jandermoreira** [olavopeixoto/plugin.video.brplay#114]
Tanto nas transmissões ao vivo quanto nas sob demanda, a tela de informações aparece sozinha.

Essa tela é a que aparece se apertar o botão "info" do controle remoto.

Tenho a sensação (apenas sensação) que ela aparece quando há alguma flutuação no stream.
O problema é que, pra voltar para o programa tem que ser manualmente (apertando "back" ou "info"). Isso torna cansativo quando as informações aparecem a cada 10 ou 15 segundos.

Há como desabilitar essa situação? Não achei nada das configurações.

Obrigado.

Kodi Leia 
OpenElec em Raspberry Pi 3
Addon BRPlay na última versão

**Comment by olavopeixoto** [comment]
A tela do "Player" é controlada pelo Kodi, o addon termina a execução no memento que passa a url do video pro Kodi.
Se houver qualquer opção desse tipo será nas opções do Kodi e/ou do skin.
