### ISSUE TITLE
TNT Play

### ISSUE THREAD

**Issue by danilo759** [olavopeixoto/plugin.video.brplay#115]
TNT Play aqui está retornando um erro: NoneType object has no attribute __getitem

Oi Play => Desabilitado

TNT Play => Habilitado
Senha e User => OK
OPERADORA => Apareceu OI TV automaticamente, não tem como eu escolher a CLARO (que eu assino)

Se precisar de login e senha da operadora para testar, me avisa que eu passo.

Abs.

**Comment by olavopeixoto** [comment]
Atualmente somente a operadora Oi está implementado. Vou tentar implementar a Claro pra você testar, caso precise dos dados eu entro em contato

**Comment by danilo759** [comment]
Ok, obrigado Olavo.

Grande abraço!

**Comment by danilo759** [comment]
Pra quem acessar esse tópico, Olavo atualizou o plugin ontem e agora já é possível selecionar sua operadora. Esse garoto é fera mesmo. Grato, Olavo. 

Abs

**Comment by olavopeixoto** [comment]
Coloquei a opção das operadoras mas ainda não implementei a autenticação. Funcionando 100% por enquanto só a Oi.
A claro/net eu fiz uma tentativa, preciso do seu feedback pois não tenho o login pra testar todo o fluxo.
Me diga se funciona pra você.

**Comment by danilo759** [comment]
Funciona! Aqui os 3 canais abriram com o login da Claro.

**Comment by olavopeixoto** [comment]
👍🏻

**Comment by danilo759** [comment]
TNT Play parou de funcionar com o último update do VOD Telecine?
Aqui não aparece mais os 3 canais em "Ao Vivo".
