### ISSUE TITLE
Globo play 

### ISSUE THREAD

**Issue by altboy** [olavopeixoto/plugin.video.brplay#12]
Olá, bom dia 

O play funciona perfeitamente, sem freeze. Muito bom, só tenho a dúvida: quando será adicionado a globo nordeste, pois hoje foi liberado a função ao vivo para o pessoal dessa região. 

Grato!

**Comment by bruno-briner** [comment]
Está libnerado pelo aplicativo GloboPlay para celulares?

**Comment by altboy** [comment]
Sim, está!

**Comment by bruno-briner** [comment]
Por o acaso você tem um iPhone e familiaridade com o Wireshark?

**Comment by altboy** [comment]
Android. 
Você diz sniffer né? 
Não muito!

**Comment by olavopeixoto** [comment]
Implementado na versão 0.0.11
