### ISSUE TITLE
Canais Globo não estão carregando o vídeo ao vivo

### ISSUE THREAD

**Issue by danilo759** [olavopeixoto/plugin.video.brplay#120]
Os canais ao vivo da Globo não estão abrindo aqui na versão 1.0.4... Olavo, quando puder verifica pra gente.

**Comment by olavopeixoto** [comment]
Verifica se foi resolvido na ultima versão

**Comment by danilo759** [comment]
> Verifica se foi resolvido na ultima versão

Corrigido! Obrigado 😃
