### ISSUE TITLE
Canais Globosat em Canais Globo

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#121]
O globoplay passou a vender pacotes de canais ao vivos da Rede Globosat (Multishow, GloboNews, etc) para seus assinantes que não possuem TV por assinatura. A pergunta é se já encontra a opção de ativar e desativar esses canais no addon?

**Comment by olavopeixoto** [comment]
versão 1.0.7 tem suporte
