### ISSUE TITLE
Demora na listagem dos canais ao vivo

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#123]
Essa última versão(1.0.8) tá apresentando uma enorme demora pra listar os canais ao vivo.

**Comment by marcusmuller** [comment]
Voltou o problema do epg que faz com que as afiliadas não apareçam.

**Comment by marcusmuller** [comment]
Voltei pra versão 1.0.6 e continuou a mensagem de erro. Desativei o Globo Internacional e o problema sumiu.

**Comment by olavopeixoto** [comment]
tem o log?

**Comment by olavopeixoto** [comment]
Esse problema ainda existe ou posso fechar o issue?

**Comment by marcusmuller** [comment]
> Esse problema ainda existe ou posso fechar o issue?

Pode fechar! Não está mais demorando.
