### ISSUE TITLE
Oi Play não funciona no Windows/Xbox

### ISSUE THREAD

**Issue by andersonrfsilva** [olavopeixoto/plugin.video.brplay#124]
Saudações!

Agradeço pela disponibilidade de desenvolver e manter esse addon, parabéns pelo ótimo trabalho!

Gostaria de relatar o problema que encontrei, instalei e configurei o BR Play para reproduzir canais ao vivo da Oi Play, porém não funciona.

aqui o kodi.log
https://hastebin.com/olemanovet.apache

em tempo, eu baixei o widevinecdm.dll manualmente como eu li em
https://www.husham.com/how-to-install-netflix-kodi-18-addon/
nesse endereço
"https://redirector.gvt1.com/edgedl/widevine-cdm/970-win-x64.zip"
e coloquei no diretório em questão, mas o erro continua o mesmo.

Usei tanto a versao do Kodi 18.9 da Windows Store quanto baixando a versão x64 do site oficial.

Mesmo problema ocorre no xbox, a mensagem de erro é diferente:
ERROR: AddOnLog: InputStream Adaptive: No decrypter found for encrypted stream

**Comment by olavopeixoto** [comment]
O problem aí é na instalação do inputstream.adaptive. Você já testou algum outro addon que use ele também?
Vou tentar automatizar a instalação em versões futuras usando o [https://github.com/emilsvennesson/script.module.inputstreamhelper](https://github.com/emilsvennesson/script.module.inputstreamhelper)

**Comment by andersonrfsilva** [comment]
Usei o addon Pluto.TV que instala automático o inputstream.adaptive e funcionou 🤷‍♂️ tenta abrir um issue lá no git do inputstream, vocês são desenvolvedores podem conversar na mesma linguagem. 😁 Valeu a força.

Vi que adicionou o suporte ao Pluto.TV, show!
