### ISSUE TITLE
GloboPlay com videos somente na integra?

### ISSUE THREAD

**Issue by bruno-briner** [olavopeixoto/plugin.video.brplay#126]
Olavo,

Estava usando ainda a versao 0.0.43 e recentemente atualizei. Fiquei surpreso que agora todos os videos do GloboPlay aparecem somente na integra sem a opcao nos "Settings" como antes. Isto foi proposital? Tem como retornar como antes, ou seja, como uma opçao? Com a minha idade ja nao tenho mais a paciencia de ficar assistindo os telejornais na integra.

Bruno Briner

**Comment by olavopeixoto** [comment]
Foi na atualização para a nova API. Atualmente trechos so na busca ou na playlist "mais assistidos".
Vou ver uma forma melhor de incluir os trechos também.

**Comment by bruno-briner** [comment]
@olavopeixoto à algum tempo as partes não são mais exibidas. Somente na íntegra novamente. 

Talvez algo na API tenha mudado?
