### ISSUE TITLE
Erro 403 canais globo com credenciais globoplay

### ISSUE THREAD

**Issue by Thicoxxi** [olavopeixoto/plugin.video.brplay#128]
Boa tarde, Olavo.
Tenho o addon instalado em um raspberry pi 3 com kodi 18.9 na aba de canais ao vivo entra somente a globo globonews e futura. Os demais canais que tenho dentro do pacote globoplay como exemplo megapix, universal etc.. Todos dão erro 403 na hora que  tento acessar. Já fiz o teste de acessar via google chrome pelo site do globoplay e funciona perfeitamente. Estou usando a ultima versão disponível do addon do repositório.

**Comment by olavopeixoto** [comment]
Preciso do log pra ajudar.
Os canais extras são por TV por assinatura ou globoplay + canais ao vivo?
403 me parece que você esta tentando usar a plataforma errada.
Se for globoplay, desabilite o globosat e habilite o globoplay + canais ao vivo.

**Comment by Thicoxxi** [comment]
Olavo muito obrigado pela resposta. Fiz a correção para globoplay + canais ao vivo e funcionou. Estou procurando os logs para mandar para vc pois acredito que agora tem um outro erro relacionado a DRM widevine pois canais como mega pix, universal e syfy não estão sendo carregado. eu tenho instalado o inputstream adaptive 2.6.4 no kodi 18.8 leia. vc poderia me dizer onde acho os logs do addon por favor.

**Comment by olavopeixoto** [comment]
Aqui tem informações de onde encontrar e como fazer o upload do log
[https://kodi.wiki/view/Log_file/Easy](https://kodi.wiki/view/Log_file/Easy)

O BRplay também precisa estar configurado para registrar no log, nos ajustes do addon na aba Geral habilite o debug.

**Comment by Thicoxxi** [comment]
Olá Olavo, 
Segue log para você analisar.
https://paste.kodi.tv/awatocebiq.kodi ou 
https://paste.ubuntu.com/p/JWJYXBd2rk/

**Comment by olavopeixoto** [comment]
testa a versão 1.0.13 e me diz se resolveu pra você.

**Comment by Thicoxxi** [comment]
Olavo, bug resolvido nessa última versão que vc disponibilizou no repositório. Muito obrigado.
