### ISSUE TITLE
Login Canais Globo (operadora) e Globoplay

### ISSUE THREAD

**Issue by danilo759** [olavopeixoto/plugin.video.brplay#132]
Tem algum jeito de assistir os Canais Globo pelo login da minha operadora?

Explico, sou assinante da Claro NET (antiga NET Cabo) e também sou assinante Globoplay, quando eu coloco as credenciais da Globoplay entro com sucesso, os Canais Globo não funciona embora apareça da lista.

Se eu for em configurações e desabilitar o Globoplay, ai tem uma opção colocar as credenciais do Canais Globo, porém não tem a opção de selecionar a operadora, com isso gera um erro de autenticação.

Tem alguma forma de entrar com o Globo Play desabilitado? 

Antes de eu assinar o Globoplay eu usava a opção "Usar as credencias Globoplay para os canais Globo" e na opção Globo Play eu deixava habilitado e colocava meu login e senha. Funcionava perfeito, eu conseguia ver os canais Globosat, agora não consigo mais.

**Comment by olavopeixoto** [comment]
Você fez a associação da sua operadora com o seu login globoplay?
O Canais Globo (Globosat) só funciona com o login da operadora associado ao login globo.com (Globoplpay)

**Comment by CaioTheBrain** [comment]
É o que o @olavopeixoto falou.

Você tem que entrar no Canais Globo (antigo Globosat Play) pelo navegador web e logar lá. Ele vai pedir que você informe as credenciais da sua operadora para associar à sua conta na Globo.com.

**Comment by rogerioronin** [comment]
É possível assistir a globo com o login gratuito do Globo Play ?

**Comment by CaioTheBrain** [comment]
É possível sim, inclusive até selecionar qual dos sinais disponíveis no serviço você quer assistir.

**Comment by rogerioronin** [comment]
> É possível sim, inclusive até selecionar qual dos sinais disponíveis no serviço você quer assistir.

Eu coloquei minha contar gratuita do globo play, mas não encontrei, vou dar mais uma olhada  aqui!
