### ISSUE TITLE
Problemas na nova atualização do plugin

### ISSUE THREAD

**Issue by altboy** [olavopeixoto/plugin.video.brplay#133]
Olá

Vi que foi lançado uma nova versão do plugin eu baixei e atualizei no Kodi (smartphone, tv box e Chrome os), porém aconteceram as seguintes coisas:

* Lista de canais (tanto Globo quanto Globosat) desapareceram, não aparecem mais.

* Na versão anterior tinha favoritado os canais e quando tentei acessá-los pelos favoritos da erro.

* No VOD, quando tento acessar qualquer conteúdo ele dá uma mensagem de erro: **captchablank** e dependendo do conteúdo ele dá o erro de "**video is for subscribers only**", sendo que sou assinante e coloquei meu login e senha corretamente. No app do Globo play está funcionando normalmente.

Todas as opções estão inalteradas da última versão do plugin, não mudei nada.

Segue anexo o log para verificação.

[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/6017642/kodi.log)

Grato pela atenção.

**Comment by hcisilio** [comment]
Boa noite. Comigo também ocorre problema para acesso ao conteúdo globosat, mais especificamente aos jogos do premiere em que sou assinante pela sky. Já fiz a associação da minha conta sky com a minha conta globo corretamente e pelo navegador eu consigo fazer o login e assistir ao conteúdo normalmente. 

Pelo que verifiquei agora para fazer login nos portais globo (fiz o teste pelo site do globo esporte) é exigido usuário, senha e captcha. Acho que por este motivo o login pelo plugin não funciona.

**Comment by dudumaroja** [comment]
Confirmo o problema, a mensagem captchblank seguida de erro 403 para todo conteúdo da globo

**Comment by olavopeixoto** [comment]
Exatamente, o problema é que a globo aparentemente está exigindo Captcha em todas as tentativas agora. O addon é 100% automático, sem interatividade, e está ignorando o captcha no momento. Vou precisar fazer uma interface pra resolver o captcha no login.

**Comment by olavopeixoto** [comment]
Foi resolvido o problema pra vocês na ultima versão?

**Comment by altboy** [comment]
Vou testar aqui e te aviso ok.
Grato!

**Comment by altboy** [comment]
@olavopeixoto 

Perfeito!!!!

Funcionou, consegui acessar os canais pelo meus favoritos.

Porém ao acessar o plugin diretamente os canais globo e globosat não apareceram na listagem, somente os canais Pluto TV.

De qualquer maneira parabéns pelo trabalho.

Grato!

**Comment by olavopeixoto** [comment]
manda o log pra saber qual o problema.
Você pode experimentar com as opções de ignorar autorização pra ver se resolve.

**Comment by hcisilio** [comment]
Foi lançado no branch master? pelo menos o auto update do plugin dentro do kodi diz que não há atualização para mim e o problema persiste. vou baixar o zip e reinstalar e te do o retorno

**Comment by hcisilio** [comment]
Acessando após a instalação no PC. a atualização que fiz na minha tvbox gerou um erro, mas acho que é problema do sistema dela. vou remover completamente o plugin de lá e reinstalar

**Comment by altboy** [comment]
> manda o log pra saber qual o problema.
> Você pode experimentar com as opções de ignorar autorização pra ver se resolve.

Boa tarde

Mesmo ignorando a autorização não resolveu e ainda não aparece os canais na listagem de canais, somente canais plutotv.

Consigo acessar os canais somente nos favoritos.

Segue log:

[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/6218019/kodi.log)

Grato

**Comment by altboy** [comment]
@olavopeixoto 

Agora funcionou perfeitamente, sem travamentos e a listagem está aparecendo normalmente.

Grato pela solução e parabéns pelo trabalho esse plugin é 10.

Vlw
