### ISSUE TITLE
Erro Captcha 

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#136]
Na versão 1.0.14 surge um erro de Captcha e que me impede de acessar os Canais Globo e Globo Play.

Tô voltando pra versão 1.0.12 que é a mais estável até agora.

![Screenshot_20210304-065621_Kodi](https://user-images.githubusercontent.com/28604497/109947328-f4a14080-7cb7-11eb-8096-0da32eee271f.jpg)

**Comment by marcusmuller** [comment]
Atualização: Voltei na versão 1.0.12 (na qual está estável e já estou logado há um tempo) e encontrei o mesmo erro ao tentar abrir os Canais Globo e Globo Play em outro dispositivo novo. 

Erro: CaptchaBlank 

Será que a TI ferrou com o addon?

**Comment by marcusmuller** [comment]
Confirmando que é real que a Globo implementou a verificação de robô 🤖. O Captcha está atrapalhando. Tem como resolver isso?

![Screenshot_20210304-072426_Brave](https://user-images.githubusercontent.com/28604497/109950074-e56fc200-7cba-11eb-9e3b-e4d8fd40b42e.jpg)

**Comment by olavopeixoto** [comment]
Como você identificou, a globo está exigindo o captcha em todos os requests e não somente em alguns como antes. Esse erro já foi reportado aqui:
https://github.com/olavopeixoto/plugin.video.brplay/issues/133

**Comment by marcusmuller** [comment]
Como da pra contornar isso?

**Comment by olavopeixoto** [comment]
Por enquanto não tem o que fazer do ponto de vista do usuário. Vou colocar aqui como prioridade.

**Comment by marcusmuller** [comment]
A versão "1.0.2: - Changed Globoplay/Canais Globo authentication method" está funcionando perfeitamente. Valeu.
