### ISSUE TITLE
Add BBB para o Globo play

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#137]
Atualmente só tem opção de BBB para os Canais Globo(Tv a cabo). Nao consigo acessar com o Globoplay

**Comment by olavopeixoto** [comment]
Já da pra acessar pelo menu On Demand. So navegar la pela Globo que aparece a opção tanto on demand quanto ao vivo.

**Comment by marcusmuller** [comment]
Então... Dar erro de que o vídeo é só pra assinantes. Acredito que seja para assinantes de TV a Cabo, pois assinante Globo Play e vejo o BBB no app. Apenas o primeiro link do BBB abriu, já o resto apresentou o erro. 

Segue os prints:

![Screenshot_20210305-173524_Kodi](https://user-images.githubusercontent.com/28604497/110171064-e0556480-7dd9-11eb-9e52-5d3e25f7944b.jpg)
![Screenshot_20210305-173601_Kodi](https://user-images.githubusercontent.com/28604497/110171079-e9463600-7dd9-11eb-9cfd-33d0dfc827db.jpg)
![Screenshot_20210305-173608_Kodi](https://user-images.githubusercontent.com/28604497/110171091-ee0aea00-7dd9-11eb-9627-f29d30703f78.jpg)

**Comment by olavopeixoto** [comment]
O BBB no menu principal é da Globosat, o do Globoplay fica dentro do canal Globo.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/7496076/110177725-4e5f5300-7dfd-11eb-84cb-cd05390cbedc.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7496076/110177784-659e4080-7dfd-11eb-97c0-f5a4bc7cf4b6.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7496076/110177804-6df67b80-7dfd-11eb-97ea-afcc8b34b60f.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7496076/110177835-76e74d00-7dfd-11eb-99f7-721e2ac42e75.png">

**Comment by marcusmuller** [comment]
Situação resolvida! Valeuu.
