### ISSUE TITLE
Funcionamento do "CDN" nos Ajustes

### ISSUE THREAD

**Issue by bruno-briner** [olavopeixoto/plugin.video.brplay#140]
Como é o funcionamento das opções em CDN nos Ajustes?

Eu implementei uma regra de "Policy-Based-Routing" no meu pfSense para que quando IPs da Globo fossem acessadas os pacotes IPs eram enviados para uma conexão VPN permanente que eu tenho com o Brasil. Isto me dava a funcionalidade de acessar conteúdo "georestricted". Funcionava muito bem 99% das vezes, exceto quando a conexão estava muito lenta.

Porém recentemente somente consigo acessar se eu desativar a minha regra PBR, ou seja, somente se eu acessar via meu IP nativo não BR. Ativando minha regra PBR e ajustando o CDN para Globo, qualquer conteúdo pelo addon falha, enquanto que acessando por Browser, funciona sem problemas. 

Pelas minhas investigações ao acessar via Browser, IPs da Globo parecem ser acessadas se você realmente está no Brasil (testado via VPN direto no meu MacBookPro e através do minha regra de PBR), enquanto IPs da Verizon ou Akamai foram acessados ao tentar usar pelo meu IP nativo fora do BR (com a mensagem de que eu não posso usar o serviço fora do BR)

O addon tenta "descobrir" onde ele está por algum motivo?

**Comment by olavopeixoto** [comment]
No addon não existe nenhuma lógica própria de identificação geográfica para fins de rota de video. A própria API da globo faz esse roteamento automaticamente. Escolhendo o CDN nos settings ele força o uso de um CDN especifico, nos meus testes a API sempre retorna CDN da Globo automaticamente a não ser para Globo Internacional.
Não sei porque no seu caso está falhando pelo addon, você consegue ver o erro no log?

**Comment by rogerioronin** [comment]
Uma pergunta (se não for conveniente aqui, fique a vontade para apagar), eu estou tentando habilitar somente os canais globo gratuito, sem fazer login em conta alguma, mas não acontece nada, não é possível fazer o que desejo ou estou errando em alguma coisa ?

**Comment by bruno-briner** [comment]
@olavopeixoto Acredito ser algo com a combinação Kodi e PBR do pfSense, pois ao colocar o Kodi inteiro no gateway via OpenVPN tenho praticamente o mesmo resultado.

O engraçado é que por Web Browser o meu sistema de roteamento funciona muito bem, enquanto que via Kodi não mais.

Levo à acreditar que os sistema de servidores da G também estejam implementando sistemas de detecção. Coincidentemente hoje a seção "Trechos" desapareceu, o addon retorna somente os videos "na íntegra" e sem que eu ativar as minhas regras de PBR o addon retorna erro de "Georestricted".  Vou ter que testar mais para saber com certeza o que está acontecendo. Pelo Web Browser está funcionamento normalmente.

**Comment by helviojr** [comment]
> Uma pergunta (se não for conveniente aqui, fique a vontade para apagar), eu estou tentando habilitar somente os canais globo gratuito, sem fazer login em conta alguma, mas não acontece nada, não é possível fazer o que desejo ou estou errando em alguma coisa ?

@rogerioronin , realmente os assuntos devem ser compartimentados, e essa é uma outra questão. O ideal seria você clicar aí em cima em "New Issue" e abrir uma questão separada. Se o Olavo quiser, apague a pergunta e a minha resposta, que segue: pelo que percebi, o acesso aos "canais abertos da Globo" via internet são exclusivos para assinantes Globo.com (ao menos os acessos implementados neste Add-on. Então, não seria possível o que você deseja. Você consegue, entretanto, acessar o SBT pelo BR play. Não sei se o Olavo tem intenção (e possibilidade) de implementar outros canais abertos.

**Comment by olavopeixoto** [comment]
> > Uma pergunta (se não for conveniente aqui, fique a vontade para apagar), eu estou tentando habilitar somente os canais globo gratuito, sem fazer login em conta alguma, mas não acontece nada, não é possível fazer o que desejo ou estou errando em alguma coisa ?
> 
> @rogerioronin , realmente os assuntos devem ser compartimentados, e essa é uma outra questão. O ideal seria você clicar aí em cima em "New Issue" e abrir uma questão separada. Se o Olavo quiser, apague a pergunta e a minha resposta, que segue: pelo que percebi, o acesso aos "canais abertos da Globo" via internet são exclusivos para assinantes Globo.com (ao menos os acessos implementados neste Add-on. Então, não seria possível o que você deseja. Você consegue, entretanto, acessar o SBT pelo BR play. Não sei se o Olavo tem intenção (e possibilidade) de implementar outros canais abertos.

obrigado, é isso mesmo. Não precisa ser assinante, você pode abrir uma conta gratis na globo.com e assistir os conteúdos gratuitos.

Se for continuar a thread, por favor, abra outro issue com a duvida.

**Comment by bruno-briner** [comment]
Apenas fechando este "issue" para que não fique aberto. Como feedback, não sei na realidade qual era a causa raiz do problema no meu caso. Agora com o meu setup e ajuste consigo acessar qualquer conteúdo, sem restrição de localização.
