### ISSUE TITLE
Erro ao logar com as credenciais para "Canais Globo"

### ISSUE THREAD

**Issue by eder-erl** [olavopeixoto/plugin.video.brplay#147]
No últimos dias tenho encontrado dificuldades ao carregar o plugin brplay com o usuário/senha para o "Canais Globo" que por muitas vezes não exibe a lista de canais e retorna a tela inicial do plugin.

Segue log do erro: https://paste.kodi.tv/xodihinuqi.kodi

**Comment by marcusmuller** [comment]
Também tive esse erro na versão atual, então voltei duas atrás pra sair do bug.

**Comment by olavopeixoto** [comment]
A ultima versão deve ter resolvido isso
