### ISSUE TITLE
Bug release 1.0.23

### ISSUE THREAD

**Issue by xicobiu** [olavopeixoto/plugin.video.brplay#149]
Testei essa nova versão hoje e não funcionou pra mim. Erro: "Invalid Token".  Apaguei cachê, reconfigurei e nada de funcionar os serviços globo. Testei Oi Player tá OK! Voltei pra versão: 1.0.2 que está estável pra mim.

**Comment by olavopeixoto** [comment]
tem log do erro? Aqui esta tudo ok, preciso entender melhor o problema

**Comment by neiguerra** [comment]
Olá... mesmo problema aqui de Token Inválido... Aonde encontro o arquivo de Log? já fucei em tudo quanto canto e não acho... obrigado!!

**Comment by olavopeixoto** [comment]
[https://kodi.wiki/view/Log_file](https://kodi.wiki/view/Log_file)

**Comment by olavopeixoto** [comment]
Versão antiga, não teve mais informações vou fechar o issue. Se ainda houver problemas abra outro com as informações do log.
