### ISSUE TITLE
Erro ao reproduçao conteúdo na Integra

### ISSUE THREAD

**Issue by faberinfo** [olavopeixoto/plugin.video.brplay#15]
Estranhamente, a versão na intergra de series e novelas, deixaram de funcionar. Nos Jornais funcionam normalmente.
Entrei pelo site do GloboPlay e consigo visualizar as versões na integra, normalmente.

Quando clico em Mostrar Error. O Tipo de erro é Exceptions.KeyError = hash.
Isso acontece na função que manda dar play no video.

**Comment by olavopeixoto** [comment]
Experimente limpar o cache no Settings. A última opção é "Clear Cache"
