### ISSUE TITLE
Now - There are multiple cookies with name, avs_browser_id

### ISSUE THREAD

**Issue by willf444** [olavopeixoto/plugin.video.brplay#159]
Não funciona.
As vezes dá o erro do título, as vezes dá outro erro.

Globo Play também não funciona.

Estou usando Kodi Matrix.

Só funciona Pluto

**Comment by olavopeixoto** [comment]
Fixed on https://github.com/olavopeixoto/plugin.video.brplay/releases/tag/1.0.24 and https://github.com/olavopeixoto/plugin.video.brplay/releases/tag/2.0.2
