### ISSUE TITLE
Transmissão Globo Play em 1080p

### ISSUE THREAD

**Issue by PauloDapper** [olavopeixoto/plugin.video.brplay#16]
Olavo, aparentemente agora o Globo Play transmite em Full HD, há um novo link chamado "globo-xx_3475/playlist.m3u8"

Há a possibilidade de adicionar essa nova resolução ao addon?

**Comment by diegopeixotostitch** [comment]
Não percebi alteração na resolução do play... Como faço esse teste?

**Comment by bruno-briner** [comment]
@PauloDapper Voce se refere à GloboPlay para celulares ou GloboPlay para navegadores? Se o ultimo, voce poderia colocar o link completo para testar?

**Comment by olavopeixoto** [comment]
O BR play já suporta qualquer resolução disponível nativamente, não precisa fazer nada.
Pra mim já abre aqui com a nova banda de 3.5Mbps

![image](https://user-images.githubusercontent.com/7496076/29984851-b4d51e8e-8f32-11e7-820f-3d83a7b8b3bb.png)

**Comment by olavopeixoto** [comment]
Mas so aumentou a banda, a resolução continua 720p...

**Comment by PauloDapper** [comment]
Entendi! Quando vi o link novo e que a qualidade estava melhor pensei que tinham botado em 1080p, obrigado Olavo.
