### ISSUE TITLE
Vix Streaming [Pedido]

### ISSUE THREAD

**Issue by rogerioronin** [olavopeixoto/plugin.video.brplay#165]
Ola não sei como funciona a adição dos streaming no plugin BR Play, mas se possível seria interessante a adição do VIX (https://www.vix.com/tv/on-demand), isso porque ele é gratuito e razoavelmente descente (por ser gratuito), agradeço pelo ótimo trabalho!

**Comment by olavopeixoto** [comment]
Implementado na versão 2.2.0
