### ISSUE TITLE
Globoplay Europa

### ISSUE THREAD

**Issue by altboy** [olavopeixoto/plugin.video.brplay#168]
Bom dia, boa tarde e boa noite para todos

Finalmente a globoplay chegou em Portugal e outros paises da Europa como Alemanha, Espanha, França, Reino Unido, Itália e Suiça, além do Canadá.

Além do conteúdo teremos os canais ao vivo na plataforma: Globo Internacional, Viva, GNT, GloboNews, Multishow e dois canais de esporte, sendo um deles o PFC.

Gostaria de solicitar ao desenvolvedor que incluísse os canais do globoplay europa no brplay.

Teria como incluí-los no plugin?

Grato pela atenção e boas festas para todos.

**Comment by olavopeixoto** [comment]
Adicionado na versão 2.1.0 do Matrix
