### ISSUE TITLE
Versão 0.0.12 não instala no Kodi nem no SPMC

### ISSUE THREAD

**Issue by PauloDapper** [olavopeixoto/plugin.video.brplay#18]
Olavo, não estou conseguindo instalar a nova versão do addon em nenhum dos programas, aparece o seguinte erro:
![ulz_iqpfqq__gqh-a-hpyw](https://user-images.githubusercontent.com/29785406/30037275-bf5267d6-918f-11e7-9037-36e70e67cb37.png)

**Comment by diegopeixotostitch** [comment]
Estava apresentando este erro no meu tb.. Fui direto pelo site oficial e peguei no botão verde, download zip.. Baixou arquivo escrito master e a instalação foi realizada com sucesso.

**Comment by PauloDapper** [comment]
Rapaz, deu certo mesmo! Valeu.

**Comment by diegopeixotostitch** [comment]
Nada...  comunidade é para isso mesmo... Vamos ajudar os desenvolvedores a melhorarem o addon...

**Comment by olavopeixoto** [comment]
Resolvido.
