### ISSUE TITLE
Version 2.1.0 does not work (at least for me)

### ISSUE THREAD

**Issue by bruno-briner** [olavopeixoto/plugin.video.brplay#180]
The addon stopped working for me a few minutes ago. I was constantly receiving "Geoblocking" errors.

I then tried to identify the root cause when I saw that my Kodi autoupdated to a version 2.1.0. I was surprised since the master branch was still in 2.0.3.

I then reverted back to v2.0.3 and the addon worked again.

Since my setup is a bit complicated it might well be that the v2.1.0 doesn't work only for me. In a nutshell my setup is based on Policy Based Routing, I have a permanent OpenVPN connection to a server in Brazil established by my router pfSense. This connection is made as a gateway, so traffic from and to a Globo IP or Globo FQDN is routed to this gateway. With v2.1.0 I could not detect any traffic via this gateway as I normally see with the v2.0.3

@olavopeixoto : Just FYI at the moment. I will make more trials with the new version when I have some more time.

**Comment by olavopeixoto** [comment]
Things to look for in the new version:
Globoplay API sub domain has changed, it is now requesting from https://cloud-jarvis.globo.com
There is now a required setting to choose the region, it defaults to Brazil but I haven't tested how it upgrades from previous versions
The addon proxy setting is being used, if set, only for Brazil region. It is being ignored for other regions. It is also now used for EPG and other APIs as well, previously it was not being used for this purpose but since Globoplay started in Europe the API is not working without a proxy / vpn.

**Comment by bruno-briner** [comment]
Primeiramente desculpe a todos eu ter escrito em inglês, foi força do hábito já que havia tecnicamente acabado de ter saído do trabalho e o Inglês é a língua que hoje possuo melhor desenvoltura para escrever / falar que o próprio Português Brasileiro. Sei que inglês não é problema para o @olavopeixoto, mas para outros pode ser empecilho para interagir aqui.

É interessante que a API usa agora o "cloud-jarvis.globo.com". o FQN "cloud-jarvis.globo.com” resolve como 35.244.145.35, que é um IP que na realidade pertence ao Google. Este FQDN não estava na minha lista.

Uma breve explicação do porquê do roteamento para servidores da Globo por IP de destino ou FQDN de destino através de uma conexão OpenVPN no Brasil. Isto me possibilitou, em conjunto com o ajuste de CDN para o Akamai, assistir sem qualquer geo-restrição e com uma fluidez excelente já que o addon fazia as requisições pela conexão OpenVPN via IP brasileiro, ou seja, como se eu estivesse no Brasil mas os vídeos em si eram servidos pelo Akamai "mais próximo". Com a remoção dos CDNs no início era impossível assistir qualquer coisa inteiramente pela conexão OpenVPN, mas agora é tão raro eu ter problemas que até havia me esquecido que esta regra/conexão existia.

Para os resultados abaixo eu desativei as regras no meu pfSense baseado em IPs ou FQDN e adicionei uma outra regra baseada simplesmente no IP do meu Kodi, ou seja quando você ler "OVPN_BR Sim" isto quer dizer que todo o tráfego do meu Kodi (RPi4 com LibreElec 10.0.1) é via um IP brasileiro. Quando você ler "OVPN_BR Não" isto quer dizer que o todo o tráfego é via um IP nativo suíço. OBS: Independente do estado "OVPN_BR Sim/Não" as requisições DNS do meu RPi4 são feitas para um servidor Pihole que por sua vez usa o meu pfSense que por sua vez usa os servidores Google DNS mais próximos (havia esquecido deste detalhe)

Para o teste eu desinstalei completamente a versão v2.0.3 e me certifiquei que todos os diretórios haviam sido apagados. Instalei então a versão v2.1.0 do repositório e ajustei conforme explicado abaixo, em toda mudança eu limpava o “cache”.



**Teste A) – Ajustes parecidos Teste X com a v2.0.3, Afiliada São Paulo, OpenVPN ativado**

Addon: v2.1.0
Região: Brasil
Afiliada: São Paulo
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Sim (todo o tráfego por IP brasileiro)

Jornal da Globo: 

- Vídeos na Integra: Erro de "Georestricted" em todos os que testei.

- Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que resulta em erro de "georestricted"


Jornal Nacional

- 	Vídeos na Integra: Erro de "Georestricted" em todos os que testei.
- 	Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que resulta em erro de "georestricted"


Fantástico

- 	Vídeos na Integra: Erro de "Georestricted" em quase todos, alguns rodam sem problemas
- 	Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.



**Teste B) – Os ajustes foram mantidos, mas eu desativei o OpenVPN**

Addon: v2.1.0
Região: Brasil
Afiliada: São Paulo
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Não (todo o tráfego por IP suíço)

Jornal da Globo: 

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que roda sem problema

Jornal Nacional

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que roda sem problema

Fantástico

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.


**Se os resultados de A e B fossem inversos eu entenderia perfeitamente os resultados, mas como não são inversos eu fiquei extremamente confuso.**





**Teste C) – Mudei a região para “Europa” e mantive o OpenVPN desativado**

Addon: v2.1.0
Região: Europa
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Não (todo o tráfego por IP suíço)

Repetiu os resultados de Teste B), ou seja, tudo rodou sem erro de georestrição.




**Teste D) – Mantive a região para “Europa” e ativei o OpenVPN**

Addon: v2.1.0
Região: Europa
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Sim (todo o tráfego por IP brasileiro)

Repetiu os resultados de Teste A), ou seja, erro de georestrição.





Para comparação:



**Teste X) – A que funciona 100% para mim**
Addon: v2.0.3
Afiliada: São Paulo
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Sim (todo o tráfego por IP brasileiro)


Jornal da Globo: 

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna todos os dias, sendo que o último dia é a real data do último programa (20/05/2022) e tudo roda sem problemas. 


Jornal Nacional

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna todos os dias, sendo que o último dia é a real data do último programa (21/05/2022) e tudo roda sem problemas. 


Fantástico

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.





**Teste Y) – Funciona, mas sem listagem completa dos trechos, igual resultado B**
Addon: v2.0.3
Afiliada: São Paulo
Ignorar Autorização de Canais: Desligado
CDN : Auto
OVPN_BR Não (todo o tráfego por IP suíço)




Jornal da Globo: 

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que roda sem problema


Jornal Nacional

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que roda sem problema


Fantástico

- 	Vídeos na Integra: Todos os que testei rodaram sem problemas.
- 	Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.




**OBS** A listagem dos dias / vídeos e a ordem é diferente de com X e Y.

**Comment by bruno-briner** [comment]
Seria interessante saber o que uma pessoa que está fisicamente no Brasil, em São Paulo, obtém com o v2.1.0 e comparar com os meus resultados de Teste A) acima.

**Comment by punkomatic** [comment]
Aonde eu consigo a versão 2.1.0? Ela resolve o problema dos canais ao vivo?

**Comment by olavopeixoto** [comment]
> Aonde eu consigo a versão 2.1.0? Ela resolve o problema dos canais ao vivo?

instala o repositorio que sempre tem as versões mais recentes
https://github.com/olavopeixoto/repository.brplayer/releases/tag/v1.0

ou então faz o download do zip do branch e instala manualmente no kodi
https://github.com/olavopeixoto/plugin.video.brplay/tree/Matrix

**Comment by olavopeixoto** [comment]
> Primeiramente desculpe a todos eu ter escrito em inglês, foi força do hábito já que havia tecnicamente acabado de ter saído do trabalho e o Inglês é a língua que hoje possuo melhor desenvoltura para escrever / falar que o próprio Português Brasileiro. Sei que inglês não é problema para o @olavopeixoto, mas para outros pode ser empecilho para interagir aqui.
> 
> É interessante que a API usa agora o "cloud-jarvis.globo.com". o FQN "cloud-jarvis.globo.com” resolve como 35.244.145.35, que é um IP que na realidade pertence ao Google. Este FQDN não estava na minha lista.
> 
> Uma breve explicação do porquê do roteamento para servidores da Globo por IP de destino ou FQDN de destino através de uma conexão OpenVPN no Brasil. Isto me possibilitou, em conjunto com o ajuste de CDN para o Akamai, assistir sem qualquer geo-restrição e com uma fluidez excelente já que o addon fazia as requisições pela conexão OpenVPN via IP brasileiro, ou seja, como se eu estivesse no Brasil mas os vídeos em si eram servidos pelo Akamai "mais próximo". Com a remoção dos CDNs no início era impossível assistir qualquer coisa inteiramente pela conexão OpenVPN, mas agora é tão raro eu ter problemas que até havia me esquecido que esta regra/conexão existia.
> 
> Para os resultados abaixo eu desativei as regras no meu pfSense baseado em IPs ou FQDN e adicionei uma outra regra baseada simplesmente no IP do meu Kodi, ou seja quando você ler "OVPN_BR Sim" isto quer dizer que todo o tráfego do meu Kodi (RPi4 com LibreElec 10.0.1) é via um IP brasileiro. Quando você ler "OVPN_BR Não" isto quer dizer que o todo o tráfego é via um IP nativo suíço. OBS: Independente do estado "OVPN_BR Sim/Não" as requisições DNS do meu RPi4 são feitas para um servidor Pihole que por sua vez usa o meu pfSense que por sua vez usa os servidores Google DNS mais próximos (havia esquecido deste detalhe)
> 
> Para o teste eu desinstalei completamente a versão v2.0.3 e me certifiquei que todos os diretórios haviam sido apagados. Instalei então a versão v2.1.0 do repositório e ajustei conforme explicado abaixo, em toda mudança eu limpava o “cache”.
> 
> **Teste A) – Ajustes parecidos Teste X com a v2.0.3, Afiliada São Paulo, OpenVPN ativado**
> 
> Addon: v2.1.0 Região: Brasil Afiliada: São Paulo Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Sim (todo o tráfego por IP brasileiro)
> 
> Jornal da Globo:
> 
> * Vídeos na Integra: Erro de "Georestricted" em todos os que testei.
> * Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que resulta em erro de "georestricted"
> 
> Jornal Nacional
> 
> * Vídeos na Integra: Erro de "Georestricted" em todos os que testei.
> * Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que resulta em erro de "georestricted"
> 
> Fantástico
> 
> * Vídeos na Integra: Erro de "Georestricted" em quase todos, alguns rodam sem problemas
> * Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.
> 
> **Teste B) – Os ajustes foram mantidos, mas eu desativei o OpenVPN**
> 
> Addon: v2.1.0 Região: Brasil Afiliada: São Paulo Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Não (todo o tráfego por IP suíço)
> 
> Jornal da Globo:
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que roda sem problema
> 
> Jornal Nacional
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que roda sem problema
> 
> Fantástico
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.
> 
> **Se os resultados de A e B fossem inversos eu entenderia perfeitamente os resultados, mas como não são inversos eu fiquei extremamente confuso.**
> 
> **Teste C) – Mudei a região para “Europa” e mantive o OpenVPN desativado**
> 
> Addon: v2.1.0 Região: Europa Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Não (todo o tráfego por IP suíço)
> 
> Repetiu os resultados de Teste B), ou seja, tudo rodou sem erro de georestrição.
> 
> **Teste D) – Mantive a região para “Europa” e ativei o OpenVPN**
> 
> Addon: v2.1.0 Região: Europa Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Sim (todo o tráfego por IP brasileiro)
> 
> Repetiu os resultados de Teste A), ou seja, erro de georestrição.
> 
> Para comparação:
> 
> **Teste X) – A que funciona 100% para mim** Addon: v2.0.3 Afiliada: São Paulo Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Sim (todo o tráfego por IP brasileiro)
> 
> Jornal da Globo:
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna todos os dias, sendo que o último dia é a real data do último programa (20/05/2022) e tudo roda sem problemas.
> 
> Jornal Nacional
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna todos os dias, sendo que o último dia é a real data do último programa (21/05/2022) e tudo roda sem problemas.
> 
> Fantástico
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.
> 
> **Teste Y) – Funciona, mas sem listagem completa dos trechos, igual resultado B** Addon: v2.0.3 Afiliada: São Paulo Ignorar Autorização de Canais: Desligado CDN : Auto OVPN_BR Não (todo o tráfego por IP suíço)
> 
> Jornal da Globo:
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna o último dia como sendo de 27/10/2021 que contém somente um vídeo que roda sem problema
> 
> Jornal Nacional
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: A API retorna o último dia como sendo de 23/10/2021 que contém somente um vídeo que roda sem problema
> 
> Fantástico
> 
> * Vídeos na Integra: Todos os que testei rodaram sem problemas.
> * Trechos: Completo com todas as chamadas da semana, todos os vídeos do último domingo (15/05/2022) rodaram sem problemas.
> 
> **OBS** A listagem dos dias / vídeos e a ordem é diferente de com X e Y.

obrigado pelos testes detalhados.
vou testar mais aqui também.
Minha experiencia até agora é que requests feitos pela região errada retornam resultados errados.
Alguma coisa na sua configuração deve estar fazendo com que o request pra api saia por um IP não brasileiro.
Outra possibilidade, que eu não testei mas já vi acontecer com outros streamings, é se o seu proxy/vpn for por um provedor de cloud, pode ser que tenha algum filtro e ele reconheça como request externo.
Pra mim, funciona normal usando IP brasileiro. IP de fora do brasil acontece o que você descreveu, conteúdos antigos, faltando, etc.

Se mudar a região pra Europa, Portugal, etc e tentar acessar com IP brasileiro também dará problema. Nesse caso tem que ser um IP europeu.

**Comment by bruno-briner** [comment]
Testei rapidamente a v2.2.1, mas analizando as modificações não esperava qualquer mudança e dito-e-feito, erro de geoblocking e/ou retorno incompleto.

Não acredito que exista qualquer "vazamento" de requisições fora da minha conexão de OpenVPN. Nos meus testes, nunca tive qualquer indício de vazamento e, para evitar que um certo grupo de IPs tivesse sido esquecido ou que um FQDN não estivesse na minha lista (como o cloud-jarvis.globo.com por exemplo), eu desviei toda requisição do meu Kodi para o IP brasileiro. Vale a pena ressaltar que a versão 2.0.3 funciona 100% para mim desde que eu mantenha as requisições via IP brasileiro.

Eu então editei "_modules/globoplay/__init__.py_" de "_cloud-jarvis.globo.com_" para "_products-jarvis.globo.com_" e agora a v2.2.1 "modificada" está funcionando 100%.
 
EDIT: Testando "traceroute" do terminal do meu Kodi, tanto para _cloud-jarvis_ quanto para _products-jarvis_ resultam que ambos são feitos pelo IP brasileiro.

**Comment by MartinsNeto80** [comment]
> > Aonde eu consigo a versão 2.1.0? Ela resolve o problema dos canais ao vivo?
> 
> instala o repositorio que sempre tem as versões mais recentes https://github.com/olavopeixoto/repository.brplayer/releases/tag/v1.0
> 
> ou então faz o download do zip do branch e instala manualmente no kodi https://github.com/olavopeixoto/plugin.video.brplay/tree/Matrix

A opção de CANAIS GLOBO (não Globoplay) parou de funcionar nessa nova atualização. Aparentemente os regionais da Globo estão mais fluidos no Globoplay.

**Comment by bruno-briner** [comment]
Resolvido com a implementação da opção de escolher a API a ser usada (2.2.4)
