### ISSUE TITLE
Não consigo dar player e alguns canais com DRM (Megapix, SYFY Universal e Studio)

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#182]
[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/8757893/kodi.log)

*Input Stream e RMP instalados.

A Globo Europa e Portugal não podem ser destravadas como a Globo US sem o uso de VPN?

**Comment by marcusmuller** [comment]
Percebi que esse erro ocorre quando desativa o InputStream Adaptative. Eu prefiro desativar pra que os restante dos canais funcionem melhor: sem erro de minutagem do player, as vezes o canal inicia no tempo de 01h30min atrás, e também para que possa abrir em 1080p. No intupStream só fica disponível 720p.

**Comment by olavopeixoto** [comment]
Sem o InputStream Adaptative o DRM não funciona.

"A Globo Europa e Portugal não podem ser destravadas como a Globo US sem o uso de VPN?":
Não tem nada de especial no Addon para "destravar" o US. O sinal lá não tem nenhum tipo de restrição geográfica. O bloqueio não tem como ser desfeito.
