### ISSUE TITLE
Seleção de praças e CDN's Globo não funcionam

### ISSUE THREAD

**Issue by szneto** [olavopeixoto/plugin.video.brplay#189]
só tá funcionando a CDN auto, e todas as praças redirecionam pra da área de cobertura. aparentemente como já falaram aqui, o plugin ta puxando a localização do ip. e antes a opção cdn globo ainda funcionava, gerando o link direto no live.globo, sem fazer peering

segue o log: **[google drive](https://drive.google.com/file/d/1WOxx43znCXSxHx_QFluS12WHYeMHxz6L/view?usp=sharing)**

**Comment by bruno-briner** [comment]
O link para o arquivo de log retorna erro "_Not Found (#404) This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff_"

**Comment by szneto** [comment]
link do log atualizado

**Comment by marcusmuller** [comment]
> só tá funcionando a CDN auto, e todas as praças redirecionam pra da área de cobertura. aparentemente como já falaram aqui, o plugin ta puxando a localização do ip. e antes a opção cdn globo ainda funcionava, gerando o link direto no live.globo, sem fazer peering
> 
> segue o log: **[google drive](https://drive.google.com/file/d/1WOxx43znCXSxHx_QFluS12WHYeMHxz6L/view?usp=sharing)**

@olavopeixoto

**Comment by olavopeixoto** [comment]
resolvido na 2.2.2
