### ISSUE TITLE
Globoplay não reproduz 

### ISSUE THREAD

**Issue by marcusmuller** [olavopeixoto/plugin.video.brplay#198]
Tentei dar play nos conteúdos ondemand do Gloplay e não consigo executar.

**Comment by guiworldtv2** [comment]
> Tentei dar play nos conteúdos ondemand do Gloplay e não consigo executar.

Igualmente, canais ao vivo funcionando de boas e conteúdos gravados não abrem :(

**Comment by drag0nst0ne** [comment]
Aqui tambem não. Segue meu log aí
[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/9173048/kodi.log).

**Comment by marcusmuller** [comment]
@olavopeixoto da um help aqui, plss.

**Comment by marcusmuller** [comment]
😭😭😭😭😭😭

**Comment by olavopeixoto** [comment]
testa ai na ultima versão por favor 2.2.4

**Comment by marcusmuller** [comment]
> testa ai na ultima versão por favor 2.2.4

Só filé!

**Comment by drag0nst0ne** [comment]
Confirmed! Ta funcionando na nova versão.
