### ISSUE TITLE
Jogos do Premiere não abrem

### ISSUE THREAD

**Issue by CaioTheBrain** [olavopeixoto/plugin.video.brplay#2]
Os jogos do Premiere não abrem. 

Os demais canais ao vivo funcionam normalmente (não possuo acesso ao Combate). 

Dispositivo: Fire TV Stick
Sistema: Fire OS 5 (baseado em Android 5.1)
Aplicativo: SPMC 16.7.0
Versão do add-on BR play: 0.0.5
Operadora: Sky

**Comment by vitorpacheco** [comment]
Tenho o mesmo problema com os canais Premier.

Dispositivo: Raspberry Pi 3
Sistema: Raspbian
Aplicativo: Kodi 17.3
Versão do add-on BR play: 0.0.10
Operadora: Vivo

**Comment by olavopeixoto** [comment]
Favor enviar o log completo registrando o problema.

**Comment by vitorpacheco** [comment]
Segue o log do momento em que abro os canais ao vivo

`20:35:53.682 T:1945698976   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
20:36:07.865 T:1088418736   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/workers.py", line 12, in run
                                                self._target(*self._args)
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globoplay/scraper_live.py", line 34, in __append_result
                                                list.append(fn(*args))
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globoplay/scraper_live.py", line 49, in __get_affiliate_live_channels
                                                live_program = __get_live_program(code)
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globoplay/scraper_live.py", line 88, in __get_live_program
                                                live = client.request(url, headers=headers)['live']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
20:36:08.136 T:1054864304   ERROR: Exception in thread Thread-6:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/workers.py", line 12, in run
                                                self._target(*self._args)
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/indexer.py", line 24, in __append_result
                                                list += fn(*args)
                                              File "/home/pi/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/scraper_live.py", line 109, in get_premiere_live_channels
                                                live_games = client.request(PREMIERE_LIVE_JSON, headers=headers)['jogos']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
20:36:17.831 T:1324348336   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/univ24ha/snapshot/?v=1500075368
20:36:18.038 T:1224733616   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/5497510.jpg
20:36:18.660 T:1216345008   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/SporTV.png
20:36:18.742 T:1224733616   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/spo124ha-praca/snapshot/?v=1500075368
20:36:18.905 T:1447031728   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/3180419.jpg
20:36:18.979 T:1216345008   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/msw24ha/snapshot/?v=1500075368
20:36:19.018 T:1224733616   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Multishow.png
20:36:19.097 T:1324348336   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/4163749.jpg
20:36:19.157 T:1324348336   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Canal Brasil.png
20:36:19.236 T:1216345008   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/bra24ha/snapshot/?v=1500075368
20:36:19.347 T:1447031728   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/3775811.jpg
20:36:19.378 T:1216345008   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/GloboNews.png
20:36:19.433 T:1447031728   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/gnews24ha/snapshot/?v=1500075368
20:36:19.523 T:1224733616   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/3180453.jpg
20:36:19.542 T:1224733616   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/GNT.png
20:36:19.598 T:1216345008   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/gnt24ha/snapshot/?v=1500075368
20:36:19.724 T:1324348336   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for http://s01.video.glbimg.com/x720/4164401.jpg
20:36:19.811 T:1324348336   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/Combate.png
20:36:19.814 T:1224733616   ERROR: CCurlFile::Stat - Failed: SSL connect error(35) for https://live-thumbs.video.globo.com/cbt24ha/snapshot/?v=1500075368`

**Comment by olavopeixoto** [comment]
Pode tentar acessar essa url no seu browser e postar aqui o resultado?

http://globosatplay.globo.com/premierefc/ao-vivo/add-on/jogos-ao-vivo/520142353f8adb4c90000008.json

**Comment by vitorpacheco** [comment]
Segue

```
{"exibir_nome_campeonato":true,"campeonatos":[{"id":2515,"nome":"Brasileiro"},{"id":2516,"nome":"Brasileiro Série B"},{"id":2496,"nome":"Pernambucano"},{"id":2513,"nome":"Primeira Liga"}],"jogos":[]}
```

**Comment by olavopeixoto** [comment]
O dado está ok. No seu fire stick por algum motivo não está retornando o mesmo resultado.
Eu também tenho um fire stick primeira geração, e funciona numa boa. Tenho o Krypton 17.3 instalado nele.

Fire OS 5.2.4.1

**Comment by vitorpacheco** [comment]
O fire stick não é meu, eu to achando que é alguma biblioteca do python que está faltando, ou está numa versão problemática, por causa do erro `CCurlFile::Stat - Failed: SSL connect error(35)`, estou reinstalando algumas coisas pra ver se funciona. E também nem as imagens estão carregando.

**Comment by vitorpacheco** [comment]
Eu fiz uma instalação limpa do Raspbian e Kodi, e os canais passaram a abrir.
Inclusive as imagens que não estavam sendo carregadas, agora são carregadas.
