### ISSUE TITLE
sugestão: adicionar outros serviços

### ISSUE THREAD

**Issue by tiagoluizo** [olavopeixoto/plugin.video.brplay#20]
sugestão para adicionar outros serviços de tv por assinatura como: WatchEspn, Fox, Fox Sports.

**Comment by CaioTheBrain** [comment]
Poderia adicionar o conteúdo do Futura Play?

Tem Live e On demand e é aberto, não precisa de autenticação. 

www.futuraplay.org

**Comment by olavopeixoto** [comment]
Futura Live ja foi adicionado a versão master. On demand ainda pendente.

**Comment by CaioTheBrain** [comment]
Opa já tô ansioso por esse release, com tantas funções adicionais. 

Valeu.

**Comment by olavopeixoto** [comment]
Não precisa esperar pelo release, você pode testar a versão master. Faz o download do zip e instala/copia por cima do anterior no Kodi.
https://github.com/olavopeixoto/plugin.video.brplay/archive/master.zip

**Comment by CaioTheBrain** [comment]
Já testei e está funcionando o Futura ao vivo na versão 0.0.17.

Valeu.

**Comment by CaioTheBrain** [comment]
Está acontecendo algo curioso.

Quando eu executo o SPMC 16.7.2 e entro no BR Play - Canais ao Vivo - ele lista o Futura.

Eu posso selecionar o canal que ele é transmitido normalmente.

Porém, depois que eu interrompo a reprodução e volto para a lista, ele não aparece mais. Isso acontece se eu escolher qualquer outro canal para assistir também. 

Só fechando o SPMC e abrindo de novo para aparecer novamente.

**Comment by CaioTheBrain** [comment]
Atualizei para a versão 0.0.18 e o problema com o Futura Play ao vivo se foi.
