### ISSUE TITLE
Impossível assistir ao sinal ao vivo do Oi Play

### ISSUE THREAD

**Issue by guiworldtv2** [olavopeixoto/plugin.video.brplay#200]
![image](https://user-images.githubusercontent.com/95205982/185051508-b954800c-4aeb-4437-a0df-4382117adcdb.png)

Só foi atualizar para a nova versão do add-on, que agora não é possível mais ver os sinais ao vivo do Oi play
19.4 matrix no firetv e também no windows :(

**Comment by Leonardo110722** [comment]
Eu estou tentando configurar a conta Oi Play mas não está abrindo nada, nem os canais ao vivo e nem os sob demanda...
Poderia me ajudar informando se o usuário que tenho que colocar no addon é o cpf mesmo e se for, devo colocar somente os números sem os separadores (xxxxxxxxxxxxx) ou devo colocar com os separadores (xxx.xxx.xxx-xx)?
Já tentei das 2 formas mas o icone do oi play aparece somente nos canais sob demanda e clicando nele aparece a animação do kodi de que está processando mais ela logo some e não acontece nada... 

O oi play não está funcionando ou eu estou fazendo algo errado na configuração do usuário e senha? Vi que no addon não tem como mudar o perfil que está como Padrão, mas na minha conta do oi play o perfil é General e até mudei o nome pra Padrão pra ver se erra isso que estava impedindo de aparecer os vídeos.

Alguém aqui que usa a conta do oi play poderia me ajudar?
Grato,
Leonardo.

**Comment by olavopeixoto** [comment]
A API de autenticacao do Oi Play mudou. Vou atualziar o Addon em breve.

**Comment by Leonardo110722** [comment]
> A API de autenticacao do Oi Play mudou. Vou atualziar o Addon em breve.

Obrigado por ter respondido!
Grato,
Leonardo.
