### ISSUE TITLE
Pluto tv e oi play

### ISSUE THREAD

**Issue by Leonardo110722** [olavopeixoto/plugin.video.brplay#203]
Olá!
Encontrei esse addon navegando aqui no github e estou testando ele com conta gratuita do globoplay e está funcionando bem.

Oi Play
Tenho visto alguns comentários de pessoas usando com conta da oi playTv mas não consegui configurar. Na configuração do usuário eu não sei se tenho que colocar o cpf, igual como é no navegador web, e também não sei qual o formato usar se é somente os número do cpf ou com os separadores (xxxxxxxxxxx ou xxx.xxx.xxx-xx), no navegador web digito somente os números mas os separadores são adicionados automáticamente. Já testei com somente os números, números com os separadores, com o meu e-mail da conta, com o meu número de telefone da minha conta oi mas nada funciona. O icone do oi play aparece no brplay mas clicando nele, aparece a animação do kodi indicando que algo vai acontecer mas nada acontece e não aparece nenhuma mensagem de erro. Não estou sabendo configurar a conta ou não está funcionando mesmo?

Pluto Tv
Esse é o único addon que conheço que consegue acessar o conteúdo on demand do pluto tv (minto... o addon que tem no repositório oficial do kodi também acessa esse conteúdo mas alguns ficam com link quebrado e não funcionam), todos os outros que testei apenas transmitem o conteúdo live que congela a transmissão do vídeo quando entra o comercial e fica rodando somente o audio (o addon pluto tv que tem no repositório SlyGuy tem somente os canais de live mas o comercial entra e sai sem congelar o vídeo). Quando não tem entrada de comercial, o brplay funciona bem... tem alguma ideia de algum ajuste no kodi pra resolver isso?

Estou testando a versão 2.2.4 do brplay em 3 notebooks diferentes e apresentam os mesmos problemas relatados:
Notebook CCE com linux debian 10 e kodi 19.1
Notebook HP com LibreElec 10 e kodi 19.4
Notebook Acer com win10 e kodi 19.4

Fico grato de tiver alguma resposta dessa mensagem.
Leonardo.

**Comment by Rferreira2k** [comment]
O Addon Pluto.TV existente no repositório oficial (https://kodi.wiki/view/Add-on:Pluto.TV) acessa o conteúdo on Demand normalmente. Em todos os Addons que testei acontece essa perda de fluxo ao entrar ou sair dos comerciais. Pelo que andei lendo, esse problema acontece devido uma falha de interpretação do Inputstream Helper do Kodi e por enquanto não há como resolver. 
![screenshot00000](https://user-images.githubusercontent.com/92768950/189653706-a40197c6-2686-4476-a1fb-bab81b767252.png)

**Comment by olavopeixoto** [comment]
OiPlay foi resolvido na versão 2.2.5

**Comment by Leonardo110722** [comment]
> OiPlay foi resolvido na versão 2.2.5

Bom dia!
Eu estou tendo dificuldades de configurar a minha conta oiplay no addon... pode ser que eu não esteja sabendo fazer.
Poderia me ajudar?

Na configuração do addon estou habilitando o oi Play

No campo usuário eu coloco o cpf, igual como faço pelo site, uso somente os números xxxxxxxxxxx e também já tentei com os separadores do cpf xxx.xxx.xxx-xx

No campo senha eu coloco a minha senha que acesso pelo site

Vi que apareceu um campo novo nessa atualização, Cep cod, que vem com o número 20000, mantive esse número mas como não funcionou eu mudei para o cep que está na minha fatura da oi e coloquei também somente o número xxxxxxxx e tentei também com o separador xxxxx-xxx mas não funciona

O campo Perfil Padrão fica em cinza e não abre pra eu digitar o perfil da minha conta que era General mas entrei na minha conta do oi play e mudei o nome para Padrão, pensado que o addon estava buscando esse nome por estar fixo no campo. Na minha conta do oi play tem 2 perfis, Kids e General (que agora eu mudei para Padrão). Tentei deletar o perfil kids pra ver se com 1 perfil somente o addon conseguiria entrar mas não é permitido deletar o perfil kids na conta do oi play.

Como com a atualização o problema permanecia pra mim e aqui foi dito que estava resolvido, desinstalei a versão atualizada e instalei a nova versão 2.2.5 do zero e mesmo assim não consigo acessar a minha conta oi play e não aparece nenhuma mensagem de erro, apenas aparece a animação do kodi de que algo vai acontecer mas ela some e não acontece nada.

Poderia me informar se estou fazendo algo errado no cadastro da conta no addon?

Fico agradecido com alguma resposta.
Leonardo.

**Comment by olavopeixoto** [comment]
O Cep so e usado para fim de EPG, nao tem relevancia pra autenticacao. Acredito que nao precise alterar o Cep se o EPG esta certo pra vc.
Autenticacao e so isso mesmo, CPF sem formatacao e senha. Quanto ao perfil o addon pega o seu perfil padrao, nao deixei isso configuravel.
Pra eu te ajudar preciso do Log do Kodi com os detalhes do seu problema.

**Comment by Leonardo110722** [comment]
> O Cep so e usado para fim de EPG, nao tem relevancia pra autenticacao. Acredito que nao precise alterar o Cep se o EPG esta certo pra vc. Autenticacao e so isso mesmo, CPF sem formatacao e senha. Quanto ao perfil o addon pega o seu perfil padrao, nao deixei isso configuravel. Pra eu te ajudar preciso do Log do Kodi com os detalhes do seu problema.

Problema resolvido!
O linux debian 10 com kodi 19.1 deve estar faltando algo e por isso ele fazia que iria abrir mas não abria.
LibreElec 10 com kodi 19.4 funcionou.

Obrigado por responder.
Grato,
Leonardo.
