### ISSUE TITLE
Combate Play não está aparecendo.. 

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#21]
Sou assinante do play combate... Porém não estou o canal premiere combate,  ele aparecia na lista do aovivo

**Comment by olavopeixoto** [comment]
Nessa ultima versao os canais estao sendo filtrados pela permissao retornada pelo login.
Se voce tem direito e nao esta aparecendo preciso entender melhor porque isso esta acontecendo.
Pode tentar limpar o cache do plugin?

No Settings clica na ultima opção em baixo: "Clear Cache"

Depois tente novamente.

Se nao funcionar pode postar o seu kodi.log aqui?

**Comment by diegopeixotostitch** [comment]
Excelente dica... Após a limpeza do cache... Canal apareceu...
