### ISSUE TITLE
Erro vivo index out of range

### ISSUE THREAD

**Issue by dantebma** [olavopeixoto/plugin.video.brplay#22]
Sou usuário Vivo, estava funcionando vem até semana passada, no Jarvis. Passou a dar erro semana passada. Pensei ser problema com versão do kodi, mudei para a atual (krypton) mas o erro continuou.

"[vivo] list index out of range"

Obrigado...

**Comment by dantebma** [comment]
Voltei para a versão anterior. Voltou a funcionar. Obrigado.

**Comment by olavopeixoto** [comment]
Você pode postar o log do erro por favor?
Quais as versões que você testou, a que deu erro e a que funcionou?
Preciso de mais informações sobre como e em que momento acontece o erro.
