### ISSUE TITLE
erro videos globo.com on demand passam apenas 10 minutos

### ISSUE THREAD

**Issue by robgolbh** [olavopeixoto/plugin.video.brplay#24]
Olavo, achei mais um probleminha com relacao ao video on demand da globo.
Ja testei todas as configuracoes no br play e em todas elas, os novos conteudo q sao divididos em partes, (acredito q tenha propaganda entres cada parte do video, teste com a novela a força do querer) so passa o primeior bloco. O video pára e não segue pro segundo, terceiro bloco, etc. Ou seja passa cerca de 10 minutos apenas. 
Alguma solução?
abcs.

**Comment by diegopeixotostitch** [comment]
Falei deste erro recentemente, porém não tinha percebido sobre essa questão da propaganda... Boa análise...

**Comment by olavopeixoto** [comment]
Não consegui reproduzir este erro, você diz avançando com o "seek" ou assistindo o video normalmente? Minha mulher assiste a novela na íntegra sem problemas.

Tem algum exemplo de conteúdo e passo a passo pra reproduzir?

Pode ver se a versão nova 0.0.14 funciona pra você no Krypton ou Leia?
Pra funcionar o plugin inputstream.adaptive tem que estar habilitado

**Comment by cam100in1** [comment]
I allso get interrupts after 10-20 Minutes. May be advertising causes this.

**Comment by robgolbh** [comment]
Ola olavo. ;E quando asssisto normalmente.
Infelizmente nao tenho a versao krypton pra te ajudar. Uso jarvis aqui por
conta desse plugin. Ele n rodava no kripton.
Agora pintou outro problema, na hora de assistir on demand.

22:22:04 540.280945 T:1430254496  NOTICE: returning cached token:
5c8dbd237025fcdf45be3b98f74a22ae
22:22:04 540.321899 T:1430254496  NOTICE: Url request:
https://gsatmulti.globo.com/oauth/sso/login/?chave=85014160-e953-4ddb-bbce-c8271e4fde74&token=5c8dbd237025fcdf45be3b98f74a22ae
22:22:04 540.672180 T:1430254496   ERROR: Traceback (most recent call last):
22:22:04 540.672485 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/addon.py", line 124, in <module>
22:22:04 540.673401 T:1430254496   ERROR:
 vod.Vod().get_vod_channels_directory()
22:22:04 540.673584 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py",
line 28, in get_vod_channels_directory
22:22:04 540.677856 T:1430254496   ERROR:     channels =
self.get_vod_channels()
22:22:04 540.678101 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py",
line 34, in get_vod_channels
22:22:04 540.678467 T:1430254496   ERROR:     channels =
cache.get(self.__get_vod_channels, 360, table="channels")
22:22:04 540.678711 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/cache.py",
line 47, in get
22:22:04 540.680176 T:1430254496   ERROR:     r = function(*args)
22:22:04 540.680481 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/indexers/vod.py",
line 46, in __get_vod_channels
22:22:04 540.680786 T:1430254496   ERROR:     channels +=
globosat.Indexer().get_vod()
22:22:04 540.680969 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/indexer.py",
line 56, in get_vod
22:22:04 540.682190 T:1430254496   ERROR:     vod =
self.get_authorized_channels()
22:22:04 540.682373 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/indexer.py",
line 51, in get_authorized_channels
22:22:04 540.682556 T:1430254496   ERROR:     channels =
cache.get(scraper.get_authorized_channels, 360, table="auth_channels")
22:22:04 540.682739 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/cache.py",
line 47, in get
22:22:04 540.682922 T:1430254496   ERROR:     r = function(*args)
22:22:04 540.683044 T:1430254496   ERROR:   File
"/storage/.kodi/addons/plugin.video.brplay/resources/lib/modules/globosat/scraper_vod.py",
line 41, in get_authorized_channels
22:22:04 540.685486 T:1430254496   ERROR:     pkgs =
client.request(channels_url, headers={"Accept-Encoding": "gzip"})['pacotes']
22:22:04 540.685791 T:1430254496   ERROR: TypeError: 'NoneType' object has
no attribute '__getitem__'
22:22:04 540.707031 T:1964180032   ERROR: GetDirectory - Error getting
plugin://plugin.video.brplay/?action=vodChannels


2017-09-22 13:41 GMT-03:00 cam100in1 <notifications@github.com>:

**Comment by olavopeixoto** [comment]
Esse seu erro parece ser problema de autenticação/login expirado. Tente limpar o cache do addon.

![screen shot 2017-10-01 at 01 13 34](https://user-images.githubusercontent.com/7496076/31050554-2a79fbbc-a646-11e7-803d-677e42880244.png)

**Comment by robgolbh** [comment]
Deacobri o que era olavo.
por algum motivo a net pediu p eu atualizar neu cadastro no aplucativo da
globosat.
atualizei e deu certo.
abcs!

Em sábado, 30 de setembro de 2017, Olavo Castro <notifications@github.com>
escreveu:

**Comment by olavopeixoto** [comment]
Mesmo problema do #11
