### ISSUE TITLE
Erro Fanart Skin Brguide. 

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#25]
Vi a skin com BrGuide, ficou maravilhosa! Porém não está aparecendo a Fanart/background de filmes, séries do. BR PLAY...  já habilitei nas opções de fanarte,  porém sem sucesso, como a skin foi gerada por vc.. Gostaria de saber se tem algum jeito de consertar?

**Comment by olavopeixoto** [comment]
Para problemas no brguide favor usar o repo correto em https://github.com/olavopeixoto/script.brguide/issues

O fanart do addon vem da Oi Play - https://www.oiplay.tv/guide
