### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by phlamaral** [olavopeixoto/plugin.video.brplay#28]
Todas as vezes que tento abrir  qualquer conteúdo ao vivo ou on demand  no addon aparece este erro. O que pode estar acontecendo? Estou usando a versão mais recente
![screenshot000](https://user-images.githubusercontent.com/31171010/30983286-6030903c-a460-11e7-989e-452652f33db5.png)

**Comment by olavopeixoto** [comment]
Favor enviar o log para analise.
Pode tentar limpar o cache do plugin no settings.

![screen shot 2017-10-01 at 01 13 34](https://user-images.githubusercontent.com/7496076/31050546-c6756728-a645-11e7-8af8-9a95311d8425.png)

**Comment by phlamaral** [comment]
Limpei o cache e voltou ao normal, obrigado.
