### ISSUE TITLE
Premiere encerrando o streaming depois de uns 5 minutos

### ISSUE THREAD

**Issue by teilor** [olavopeixoto/plugin.video.brplay#29]
Instalei o add-on no Kodi 17.4 rodando numa Mi Box e o streaming do Premiere funciona normalmente, mas depois de uns 5 minutos fecha.

Não alterei nenhuma configuração do add-on além de adicionar minha conta da Globo. Tem alguma configuração que eu poderia modificar para tentar resolver esse problema?

btw, obrigado pelo add-on!

**Comment by olavopeixoto** [comment]
No Krypton é necessário habilitar o addon "inputstream.adaptive", ele é nativo do Kodi mas vem desabilitado por default dependendo da distribuição.

**Comment by teilor** [comment]
Obrigado. Ainda cai a transmissão de tempos em tempos mas o problema de cair a cada 5min foi resolvido.
