### ISSUE TITLE
Tradução de mensagens no BRPlay

### ISSUE THREAD

**Issue by bruno-briner** [olavopeixoto/plugin.video.brplay#3]
Olavo, Posso trabalhar na tradução completa do BRPlay ou para o seu desenvolvimento você prefere manter "hardcoded"?

Não sei se eu consegui me fazer entender. Exemplo:

Atual:
`if affiliate == "All":
        affiliates = ['Rio de Janeiro','Sao Paulo','Brasilia','Belo Horizonte']
    else:
        affiliates = [affiliate]`

Ficaria +/- assim
`if affiliate == "4":
        affiliates = ['Rio de Janeiro','Sao Paulo','Brasilia','Belo Horizonte']
    else:
        affiliates = [affiliate]`

O impacto é que é mais difícil depois o entendimento no código, que é claro, posso compensar com comentários.

**Comment by olavopeixoto** [comment]
Sem problemas. Toda ajuda é bem vinda.
Pode fazer um pull request com as alterações.

**Comment by vitorpacheco** [comment]
@bruno-briner, ao invés de colocar o valor direto na comparação, poderia criar umas variáveis, assim continua fácil de entender.

**Comment by olavopeixoto** [comment]
Merge executado na versão 0.0.11
