### ISSUE TITLE
Canais ao vivo travando

### ISSUE THREAD

**Issue by pupet** [olavopeixoto/plugin.video.brplay#31]
Possuo internet fibra de 40 mb e mesmo assim quase não deu p assistir ao jogo do Flamengo ontem por conta das travadas e buffers seguidos no Premiere.  Tentei assistir a Globo News ao vivo e a mesma coisa aconteceu. 

Habilitei o addon inputstream.adaptive no Kodi e mesmo assim não houve melhoras. Testei com o fluxo adaptive redirect e buffer, download e adpative buffered.

**Comment by olavopeixoto** [comment]
Travadas e buffers infelizmente não são culpas do addon e podem ter diversos motivos.
O InputStream.Adaptive apesar do nome ainda não é adaptive (variar o bit rate de acordo com a banda disponível em tempo real), essa função ainda está em fase de desenvolvimento.
Já o proxy interno do BrPlay, "Adaptive Downloader", possui a função adaptive e a princípio seria a melhor solução para uma conexão com problemas.
Outra alternativa é limitar a banda do Kodi no settings do programa: Settings -> System -> Internet Access -> Internet connection bandwidth limitation

![screen shot 2017-10-03 at 22 05 42](https://user-images.githubusercontent.com/7496076/31149244-2f634ff0-a887-11e7-9a46-1d0b8285fffc.png)
![screen shot 2017-10-03 at 22 06 04](https://user-images.githubusercontent.com/7496076/31149245-3006da8a-a887-11e7-9d21-49507006bebf.png)

Essa opção limita o streaming do player nativo (Somente na função "Auto") para a banda escolhida.

**Comment by pupet** [comment]
Hoje fluiu normalmente e assisti por quase duas horas, então tudo leva a crer q ontem o problema foi na minha conexão.

Percebi outro problema: quando deixo o plug in InputStream.Adaptive ativado, ao tentar encerrar o Kodi, o mesmo trava e só sai "forçando". Isso no pc, e na box Beelink. Ao desativar o plug in antes de fechar o Kodi esse problema não ocorre.
