### ISSUE TITLE
Adição do Premiere 24h

### ISSUE THREAD

**Issue by PauloDapper** [olavopeixoto/plugin.video.brplay#32]
Olá Olavo, o app do PFC Play p/ Android e iOS atualizou, e agora conta com uma sessão ao vivo 24h do Premiere Clubes, tem como adicionar esse canal ao addon?
(Na versão PC não tem essa opção)

**Comment by olavopeixoto** [comment]
Implementado na versão master, não tem release ainda

**Comment by CaioTheBrain** [comment]
Instalei o master da versão 0.0.17 mas ainda não aparece o PFC 24h.

A lista de próximos jogos aparece normalmente.

**Comment by olavopeixoto** [comment]
Experimente limpar o cache do addon. Se não funcionar, habilite a opção de ignorar a autorização dos canais para ver se resolve. Se resolver, esse canal não está na lista dos canais que você tenha permissão por algum motivo.

**Comment by PauloDapper** [comment]
Boa! a opção o de ignorar a autorização dos canais fez o canal aparecer aqui e funcionou!

**Comment by PauloDapper** [comment]
E eu tenho assinatura do PFC..

**Comment by CaioTheBrain** [comment]
Aqui também funcionou a opção de ignorar a autorização dos canais. 

Eu já tinha limpado o cache mas sem resultado.
