### ISSUE TITLE
Canais ao vivo funcionando só por 5 minutos e fechando

### ISSUE THREAD

**Issue by phlamaral** [olavopeixoto/plugin.video.brplay#34]
Já limpei o cache, fiz downgrade da versão do Addon e nada resolve. Ele abre perfeitamente ao vivo durante 5 minutos e depois fecha.

**Comment by jraymond4321** [comment]
I have the same issue.

**Comment by olavopeixoto** [comment]
What Kodi version are you guys using?
This issue happens on Kodi Krypton/Leia and only when "inputstream.adaptive" native Kodi add-on is disabled.
You can either use Jarvis/SPMC or enable "inputstream.adaptive"

**Comment by jraymond4321** [comment]
Hi, I am using kodi 17.3.  

I had read some of the other issues, and have already enabled "inputstream.adaptive" and still have the issue.

Thanks!

**Comment by phlamaral** [comment]
Formatei minha box e o problema foi resolvido. Obrigado.

**Comment by idiogolima** [comment]
Oi Olavo parabéns pelo trabalho. Eu estou com o mesmo problema. Raspberry pi3 com Kodi 17.3 e inputstream.adaptive desligado. Ao ligar o inputstream.adaptive nem mesmo abriu o canal ao vivo. Alguma sugestão?

**Comment by fsfonte** [comment]
Acontece o mesmo comigo. Xiaomi Mi Box 3 com o Kodi 17 (última versão da Play Store atualizada). Com o inputstream.adaptive desligado cai a cada 5 minutos. Com ele ligado os canais não abrem.

**Comment by olavopeixoto** [comment]
Preciso do log para tentar entender o problema. Para funcionar no Kodi 17 e 18 o inputstream.adaptive é obrigatório.
