### ISSUE TITLE
Canal Globinho 

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#35]
Verificando os canais do site globosat play, observei um novo canal... "GLOBINHO" será incluso?

**Comment by olavopeixoto** [comment]
Os novos canais entram automaticamente se estiverem incluídos no seu pacote.
Ele funciona pelo seu aplicativo ou da erro de autorização?

**Comment by diegopeixotostitch** [comment]
Ele aparece no site... Mas não aparece no addon, já limpei o cache...

**Comment by olavopeixoto** [comment]
No meu também aparece, mas não funciona, diz que não está incluído no meu pacote.
Você já tentou dar play, funcionou?

**Comment by diegopeixotostitch** [comment]
Pelo site funciona sim...

**Comment by olavopeixoto** [comment]
![screen shot 2017-10-20 at 16 11 20](https://user-images.githubusercontent.com/7496076/31828139-5e0f9340-b5b1-11e7-8119-34b1a0beced2.png)

Isso que aparece pra mim.

Pode me mandar o seu log do kodi?

Preciso saber o resultado desse request com o seu token:
https://gsatmulti.globo.com/oauth/sso/login/?chave=85014160-e953-4ddb-bbce-c8271e4fde74&token={SEU TOKEN}

**Comment by diegopeixotostitch** [comment]
Vou mansa... Obrigado pela atenção.

**Comment by diegopeixotostitch** [comment]
Vou mandar ... Obrigado pela atenção.
