### ISSUE TITLE
Avancar mais de 15 minutos 

### ISSUE THREAD

**Issue by iorifly** [olavopeixoto/plugin.video.brplay#38]
Ola, boa noite!
Estou tendo o seguinte problema. Ao avançar um video, neste caso, novela - forca do querer. O video é interrompido. Como se fosse um stop. As vezes durante a reprodução também ocorre o stop. Ja tentei a versão 13 e 14. Ja tentei colocar fluxo máximo, adaptativo e tenho o mesmo problema. Estou usando libreelec 8.1.7 ARM - Kodi 17.5-rc1(git:07424d3) versão.

**Comment by diegopeixotostitch** [comment]
Acontece constantemente comigo... Sempre nas novelas... Séries...

**Comment by olavopeixoto** [comment]
Existe uma opção na versão mais recente (master) para usar playlist para videos com blocos (novelas por exemplo), com essa opção habilitada o plugin usa um video por bloco e cria uma playlist. Para avançar para outro bloco basta mudar de video. Deve amenizar/resolver o seu problema.

**Comment by aacunha** [comment]
@olavopeixoto , com a versão atual do master resolve o problema de avançar, porém se pausar por alguns minutos a reprodução retorna e dai a alguns segundos começa a "pular" para os próximos blocos, reproduz um trecho, pula novamente, e assim sucessivamente.

Kodi 17 + Fire Stick TV

Vou tentar gerar o log. 

Outro problema que identifiquei foi que ao clicar em "jogos ao vivo" retornava para a listagem de canais ao vivo ao invés de listar os jogos. Vou testar novamente e caso persista irei gerar o log.


Parabéns pelo plugin.
