### ISSUE TITLE
BRPLAY  TV AO VIVO 

### ISSUE THREAD

**Issue by JMSA23** [olavopeixoto/plugin.video.brplay#39]
Boa noite. Eu instalei o BRPlay add-on versao 0.14 no Kodi Krypton versao 17.4 e quando tento assistir a tv ao vivo não funciona. Eu recebo o erro "Playback failed." e manda checar o log file pra mais informação.

Alguém sabe de alguma outra versao do BRPlay que funciona com o Kodi 17.4 pra assistir tv ao vivo?

Obrigado.

**Comment by pupet** [comment]
Eu uso essas versões q vc citou e pra mim funciona perfeitamente.

**Comment by JMSA23** [comment]
Pupet, obrigado pela resposta.

Eu descobri o problema. Eu estava usando o plugin com o Kodi Krypton 17.4 e assim que eu instalei o Kodi Jarvirs 16.1 e troquei a VPN agora tudo esta funcionando bem. A VPN que eu estava usando era a VPN Unlimited e eu troquei pra IPVanish VPN e funciona sem interrupção.

Se alguém estiver tendo esse problema aqui fica a informação. 

Obrigado a quem teve a idea de criar esse aplicativo.
