### ISSUE TITLE
Canais ao vivo por apenas 5 minutos

### ISSUE THREAD

**Issue by havilson** [olavopeixoto/plugin.video.brplay#4]
Instalei a versão 0.10 e só consigo assistir aos canais ao vivo (Live) por 5 minutos. Fiz o downgrade para a versão 0.8 e funciona ok.
Meu Kodi é 17.3 com Windows 10.

**Comment by guidugli** [comment]
Tambem estou com Windows 10 e nas versões 0.9 e 0.10 acontecem os seguintes problemas:
- Se coloco em adaptive, nao importa qual, o stream nem abre. Aparece só um dialogo rapidamente, desaparece, e fica assim. Na hora de sair do Kodi, tenho que matá-lo pois nao sai normalmente (fica travado).
- Se coloco em Low ou Medium, ele nem abre o stream, aparece que um erro ocorreu e oferece para enviar o relatório com o erro.
- Se coloco em Auto, a stream abre mas cai depois de 5 minutos

Ja na versao 0.8, confirmo que tudo funciona perfeitamente.

Fiz o upload dos logs em modo debug com cada caso descrito acima.

[Kodi.zip](https://github.com/olavopeixoto/plugin.video.brplay/files/1150604/Kodi.zip)

**Comment by havilson** [comment]
Acontece exatamente o mesmo para mim. Só funciona com Auto e cai após 5 minutos.

**Comment by eduvirgens** [comment]
Poxa. Eu voltei pro kodi 16.1 só por causa do addon porque funciona bem. Agora que eu vi seus comentários vou testar a versão 0.8 no kodi 17.3. Espero que seja a mesma coisa no kodi 17.3 do libreelec.

**Comment by guidugli** [comment]
O unico problema é que o kodi trava ao sair, ai você tem que matá -lo. Mas
no geral funciona bem. Já aconteceu também de não conseguir abrir vídeos no
YouTube após usar esse plugin, mas foi só reiniciar o kodi e tudo voltou ao
normal.

**Comment by diegopeixotostitch** [comment]
Como consigo a versão 0.8 quero fazer os testes.

**Comment by eduvirgens** [comment]
https://github.com/olavopeixoto/plugin.video.brplay/releases

**Comment by diegopeixotostitch** [comment]
Fiz os testes, na versão está 0.8 está funcionando mesmo, problema dos 5 minutos sanado. Percebi que a globo RJ parou.. 🙁. 

Um outra dúvida..! Qual a skin usada nas fotos do addon?

**Comment by eduvirgens** [comment]
Aqui, eu fiz o teste também no kodi do Libreelec. Realmente o canal não para nos 5 minutos, mas em compensação o sistema trava antes mesmo de eu desligar o aparelho. Não dá pra usar nenhuma das versões nesse aparelho com o kodi 17.3 . Se eu quiser usar o Brplay vou ter q voltar pro kodi 16.1 . Acho q vou fazer isso mesmo.

**Comment by diegopeixotostitch** [comment]
Poxa pena.. Por que no meu box a versão 16.1 apresenta muitas falhas, ele toda hora informa o Kodi parou e sai para launcher, se descobrisse o problema usaria sem problemas ela...

**Comment by CaioTheBrain** [comment]
diegopeixotostitch, o seu box é Android? 

Se sim, já testou com o SPMC? 

A versão mais recente é a 16.7.01

**Comment by diegopeixotostitch** [comment]
Não ouvi falar de spmc... Pesquisei agora no Google parece uma versão bem leve para o Android Box... Aonde consigo a última versão e o BR Play funciona bem nele?

**Comment by havilson** [comment]
Eu usei as versões 0.10 e 0.9 no Kodi 17 e no SPMC e em ambos para após 5 minutos. A versão 0.8 funciona tanto no Jarvis (16) como no Krypton (17).

**Comment by diegopeixotostitch** [comment]
Acabei de instalar o SPMC  16.7.01 com BRplay 0.10 no auto... Tudo perfeito... Parece sky, deixei rodando no celular na madruga, acordei ainda estava em exibição, 9 horas em pleno funcionamento... E agora no box está a 01:30 hrs sem sequer travar... 
🙌🙌🙌

**Comment by olavopeixoto** [comment]
O Krypton tem vários problemas com os streams da globo, todos os modos experimentais do addon foram uma tentativa de fazer funcionar no Krypton, mas são somente experimentais. Podem ou não funcionar pra você dependendo de um monte de fatores, entre eles o dispositivo que está usando.

O ideal é usar o Kodi 16 ou o SPMC que funcionam muito bem no modo Auto.

**Comment by brunomilet** [comment]
Alguma intenção de continuar tentando resolver o problema no Kodi 17 ?

Ele para o video em exatos 5 min.

To usando o OSMC com Kodi 17.4, num Raspberry 3

**Comment by brunomilet** [comment]
Acabei de instalar o 0.0.8 e funciona de boa.

**Comment by diegopeixotostitch** [comment]
Versão 0.8 auto? Não deu problemas no kodi 17.4?

**Comment by brunomilet** [comment]
Não...ta funcionando bem. Baixei o 0.8 desse link ai acima e instalei. E ta rodando de boa no Kodi 17.4 no OSMC no Rasp3.
Deixei aqui na Globo News e já ta rodando desde q postei a ultima msg.

O auto q vc se refere é o bandwidth ? Se for, ta em auto msm.
Deixei tudo padrão, só coloquei a conta.

**Comment by diegopeixotostitch** [comment]
Vou fazer o teste...! Eu prefiro a versão no automático.. Canais on demand funcionam melhor.

**Comment by havilson** [comment]
A versão 0.0.12 está funcionando normalmente em AUTO. Testei tanto em Jarvis (SPMC em um Firestick) como em Krypton 17.4 (Windows 10)

**Comment by eduvirgens** [comment]
Eu tenho um Ki Plus onde tenho o Android rodando na memória nand e o Libreelece no SDCard. No libreelec tenho o Kodi 17 com todos addons que gosto e no Android botei o Kodi 16 só pra rodar o BRPlay, pois nele roda perfeito.

**Comment by olavopeixoto** [comment]
Para funcionar no Kodi 17 e 18 o addon "inputstream.adaptive" tem que estar devidamente habilitado. Com ele tudo funcionar normal. Eu uso o 18 nightly aqui e funciona ok em todos os dispositivos: mac, windows, fire tv, Nvidia shield.
No 18 (leia) funciona inclusive os filmes do megapix se o widevine estiver configurado na maquina (android ja tem configurado nativamente).

**Comment by CaioTheBrain** [comment]
Mesmo com o inputstream.adaptive habilitado, não funcionou pra mim no Kodi/SPMC (RC) 17.

Como no SPMC 16 está funcionando tudo bem, eu fico com ele.

Mas isso de funcionar o conteúdo com DRM no Kodi 18 me interessa, pois tenho uma Mi Box com Widevine L1. 

Você vai incluir o conteúdo do Telecine também? Seria ótimo.

**Comment by olavopeixoto** [comment]
sim, telecine está no radar pra breve

**Comment by CaioTheBrain** [comment]
Instalei o Kodi 18 alpha-1 e ativei o inputstream.adaptive e finalmente funcionaram os canais ao vivo por mais de 5 minutos.

Testei com os filmes do Megapix e funcionou o vídeo mas não o áudio.
