### ISSUE TITLE
BR play travando muito

### ISSUE THREAD

**Issue by pupet** [olavopeixoto/plugin.video.brplay#40]
Desde ontem a noite percebi que está impossível assistir algo no br play. Tentei no Windows com Kodi 17.5, depois numa Mi Box e numa box Beelink GT1 Ultimate.

O que pode estar acontecendo já q pelo navegador está tudo OK.

Obrigado.

**Comment by diegopeixotostitch** [comment]
Tudo normal aqui... Esta usando pelo wifi?

**Comment by pupet** [comment]
Testei pela wifi e pelo cabo.

**Comment by faberinfo** [comment]
Nesta semana, tem travado muito, começa 3 segundos e já trava. Jornais, novelas. Está passando isso com vocês? Tanto na Box, quanto no windows, acontece o mesmo.
