### ISSUE TITLE
Video on demad (canais) não aparecem

### ISSUE THREAD

**Issue by thiagocunhar** [olavopeixoto/plugin.video.brplay#41]
Boa tarde!

Olavo, em primeiro lugar, parabéns pelo esforço, o add-on é fantástico!

Bem, os canais ao vivo estão funcionando perfeitamente, utilizo aqui o add on no SPMC.

Porém no menu que direciona para os conteúdos on demand só lista os programas do canal Globo. O curioso é que quando uso a ferramenta de busca ele encontra os conteúdos. Acho que numa versão anterior essa listagem era feita por canais, e programas, na sequência.

Alguma dica?

**Comment by CaioTheBrain** [comment]
Limpar o cache nas configurações do addon.

Resolveu pra mim.
