### ISSUE TITLE
Video Resource Not Found

### ISSUE THREAD

**Issue by bemasiero** [olavopeixoto/plugin.video.brplay#42]
Anytime I try playing some of the live channels (such as SporTV, Multishow, and others), I get a Video Resource Not Found message.

---

Toda vez que tento ver alguns canais ao vivo (tipo SporTV, Multishow e alguns outros), eu recebo a mensagem Video Resource Not Found.

**Comment by olavopeixoto** [comment]
Esse erro pode acontecer se estiver fora do território brasileiro. Você está tentando assistir de dentro do brasil?

This is a known issue if you're trying to watch from outside Brazil, some videos are geo restricted.
