### ISSUE TITLE
Globo play não funciona

### ISSUE THREAD

**Issue by ernestojose1** [olavopeixoto/plugin.video.brplay#43]
Sempre que tento assistir a algum programa da globo play (canal sob demanda: globo) aparece informações sobre o vídeo não encontradas, já a globosat play funciona corretamente e não é nenhum problema envolvendo senhas.

**Comment by bruno-briner** [comment]
Videos da GloboPlay via BRPlay funcionando perfeitamente para mim. Deve ser algum problema / configuração local sua.

**Comment by Ern3st** [comment]
Qual é a versão do seu kodi?

**Comment by bruno-briner** [comment]
LibreElec 8.2.2, ou seja Kodi Krypton com addon "InputStream Adaptive" instalado e com o BRPlay ajustado em "Auto".

**Comment by olavopeixoto** [comment]
Esse erro "informações sobre o vídeo não encontradas" é comum quando se assiste um video restrito ao território brasileiro de fora do brasil.
Se não for o caso, por favor mande o log do erro para eu poder verificar.
