### ISSUE TITLE
Conteúdo local

### ISSUE THREAD

**Issue by CaioTheBrain** [olavopeixoto/plugin.video.brplay#44]
Com a entrada do conteúdo local de várias emissoras afiliadas, em complemento ao conteúdo das 5 emissoras próprias, foi implementada uma forma de exibir o conteúdo regional de acordo com a localização obtida do usuário. 

No aplicativo Android, por exemplo, nas abas Jornalismo e Esportes são exibidos tanto o conteúdo nacional quanto o específico da localidade. 

Há uma categoria específica de conteúdo regional contendo todo o material das emissoras locais. 

Entretanto no addon está acontecendo o mesmo que acontece pelo app quando não permitimos acesso à localização: são exibidos apenas os conteúdos nacionais. Além disso não tem a categoria Regionais para buscar manualmente. 

Tem como adicionar essa funcionalidade?

**Comment by olavopeixoto** [comment]
Já está implementado no master, não tem release ainda porque ainda tem alguns bugs em outras alterações que estou fazendo.
Mas conteúdo local e videos 4k HDR já estão ok.
