### ISSUE TITLE
Error: [vivo] list index out of range

### ISSUE THREAD

**Issue by eduleite** [olavopeixoto/plugin.video.brplay#47]
Estava usando a versão 0.0.14 com sucesso autenticando na minha senha da Net.
Mudei para a vivo e ao mudar as credenciais para meu login da Vivo, agora recebo esse erro especificado no título, nenhum canal ao vivo é exibido, nem os canais on demand.

Estou usando o SPMC versão 16.7-02

**Comment by olavopeixoto** [comment]
Experimente limpar o cache nas opções do aduno primeiro. Se não funcionar me mande o log do erro.
Para poder implementar um novo login (se mudou a implementação por exemplo) preciso do arquivo conforme explicado aqui:
https://github.com/olavopeixoto/plugin.video.brplay/issues/5

**Comment by CaioTheBrain** [comment]
Segue anexo arquivo conforme orientações.
[globosatplay.globo.com.zip](https://github.com/olavopeixoto/plugin.video.brplay/files/1661435/globosatplay.globo.com.zip)

**Comment by olavopeixoto** [comment]
Não identifiquei nenhuma alteração na rotina de login. Pode enviar o log do Kodi com o erro de login?

**Comment by eduleite** [comment]
Eita, sem querer fechei a issue. Desculpas pelo engano.
Orbrigado pelo retorno, vou verificar o log do kodi/spmc se tem algum erro lá e posto aqui.

**Comment by eduleite** [comment]
Só consegui parar pra ver o log do kodi agora. Consegui reproduzir o erro e pegar o log rodando na minha máquina windows.

O log do erro em questão está no seguinte trecho:

21:35:28.770 T:6348   DEBUG: Loaded credentials from: globosat_credentials
21:35:28.770 T:6348   DEBUG: requesting token from provider: 147 (http://globosatplay.globo.com/-/auth/gplay/)
21:35:28.834 T:6348   ERROR: C:\Users\edule\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
21:35:29.192 T:6348   ERROR: Previous line repeats 5 times.
21:35:29.192 T:6348   DEBUG: ERROR AUTH: list index out of range
21:35:29.194 T:12368    INFO: CPythonInvoker(2, C:\Users\edule\AppData\Roaming\Kodi\addons\plugin.video.brplay\addon.py): script aborted
21:35:29.197 T:4336   DEBUG: ------ Window Init (DialogNotification.xml) ------
21:35:29.203 T:12368    INFO: Python script stopped
21:35:29.203 T:12368   DEBUG: Thread LanguageInvoker 12368 terminating


[globosatplay.globo.com.zip](https://github.com/olavopeixoto/plugin.video.brplay/files/1683727/globosatplay.globo.com.zip)

[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/1683716/kodi.log)

**Comment by eduleite** [comment]
O erro está na linha 
        nova_url = re.findall('var urlString = \'(.*)\';', html)[0]
na classe vivo

**Comment by olavopeixoto** [comment]
Pode verificar a ultima versão do master pra ver se resolve o seu problema?

**Comment by eduleite** [comment]
Olavo, pode deixar que eu verifico hoje a noite.

**Comment by CaioTheBrain** [comment]
Opa.

Acabei de testar aqui e funcionou com login da Vivo. 

Instalei o master da versão 0.0.17.

**Comment by eduleite** [comment]
Testei aqui e funcionou no kodi kripton no windows 10 e no spmc da mibox (android tv). Obrigado pelo apoio!!!

**Comment by eduleite** [comment]
Fiz besteira, fechei sem querer de novo...
