### ISSUE TITLE
O conteúdo Live não aparece.

### ISSUE THREAD

**Issue by havilson** [olavopeixoto/plugin.video.brplay#48]
Ao tentar usar para assistir, por exemplo, um jogo ao vivo no Sportv (usando a opção Live) nada aparece. Apenas GloboRJ, e se eu clicar para ver o que aparece também não funciona, só uam menssagem de erro.
Tentei tanto no SPMC (Firestick) quanto no Krypton (Windows 10).

**Comment by havilson** [comment]
O desenvolvimento deste addon parou? Algum outro, similar, mais atualizado?

**Comment by bruno-briner** [comment]
Pelo fato do criador e principal (senão único) desenvolvedor (Olavo) ter colocado ele mesmo como Assignee em um issue à mais ou menos 20 dias atrás eu diria que o desenvolvimento deste addon ainda está ativo. 

Quanto à existência de outro, desconheço.

**Comment by olavopeixoto** [comment]
Só com a sua descrição não tenho como ajudar. Preciso do log com os detalhes do erro.
Nunca funcionou ou funcionou e parou de funcionar?
Se nao aparecer nenhum canal na listagem ao vivo deu algum problema no seu login.
Qual a sua operadora?

**Comment by havilson** [comment]
olavopeixoto minha operadora é a NET-RJ. Funcionava anteriormente, sem problema algum. Agora simplesmente parou. No anexo tirei 2 prints da tela. Uma delas ao selecionar a opção "Live" aparece para mim apenas o que está na figura e na outra ao selecionar a opção "On Demand".

![brplay 4](https://user-images.githubusercontent.com/5696397/35363911-a3a87ae6-0153-11e8-8d33-9b3b7ff60842.png)


![brplay 2](https://user-images.githubusercontent.com/5696397/35363877-787a0e7a-0153-11e8-9b97-6161901eff28.png)

Trecho do log:

"22:04:36.497 T:19824   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\client.py", line 118, in request
22:04:36.498 T:19824   ERROR:     raise Exception("Permission Denied")
22:04:36.498 T:19824   ERROR: Exception: Permission Denied
22:04:36.971 T:19824   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\workers.py", line 12, in run
                                                self._target(*self._args)
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\indexers\live.py", line 64, in append_result
                                                list += fn(*args)
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\indexer.py", line 22, in get_live
                                                authorized_channels = [channel for channel in self.get_authorized_channels() if channel["live"]]
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\indexer.py", line 51, in get_authorized_channels
                                                channels = cache.get(scraper.get_authorized_channels, 360, table="auth_channels")
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\cache.py", line 47, in get
                                                r = function(*args)
                                              File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\scraper_vod.py", line 41, in get_authorized_channels
                                                pkgs = client.request(channels_url, headers={"Accept-Encoding": "gzip"})['pacotes']
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
22:06:13.896 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\client.py", line 118, in request
22:06:13.897 T:20660   ERROR:     raise Exception("Permission Denied")
22:06:13.897 T:20660   ERROR: Exception: Permission Denied
22:06:13.897 T:20660   ERROR: Traceback (most recent call last):
22:06:13.898 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\addon.py", line 124, in <module>
22:06:13.898 T:20660   ERROR:     vod.Vod().get_vod_channels_directory()
22:06:13.898 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\indexers\vod.py", line 28, in get_vod_channels_directory
22:06:13.921 T:20660   ERROR:     channels = self.get_vod_channels()
22:06:13.921 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\indexers\vod.py", line 34, in get_vod_channels
22:06:13.922 T:20660   ERROR:     channels = cache.get(self.__get_vod_channels, 360, table="channels")
22:06:13.922 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\cache.py", line 47, in get
22:06:13.922 T:20660   ERROR:     r = function(*args)
22:06:13.922 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\indexers\vod.py", line 46, in __get_vod_channels
22:06:13.923 T:20660   ERROR:     channels += globosat.Indexer().get_vod()
22:06:13.923 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\indexer.py", line 56, in get_vod
22:06:13.923 T:20660   ERROR:     vod = self.get_authorized_channels()
22:06:13.923 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\indexer.py", line 51, in get_authorized_channels
22:06:13.923 T:20660   ERROR:     channels = cache.get(scraper.get_authorized_channels, 360, table="auth_channels")
22:06:13.923 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\cache.py", line 47, in get
22:06:13.924 T:20660   ERROR:     r = function(*args)
22:06:13.924 T:20660   ERROR:   File "C:\Users\...\AppData\Roaming\Kodi\addons\plugin.video.brplay\resources\lib\modules\globosat\scraper_vod.py", line 41, in get_authorized_channels
22:06:13.924 T:20660   ERROR:     pkgs = client.request(channels_url, headers={"Accept-Encoding": "gzip"})['pacotes']
22:06:13.925 T:20660   ERROR: TypeError: 'NoneType' object has no attribute '__getitem__'
22:06:13.939 T:20328   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.brplay/?action=vodChannels
22:06:13.940 T:20328   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.brplay/?action=vodChannels) failed"

Kodi 17.6
SO: Windows 10 (64 bits) 1709

**Comment by olavopeixoto** [comment]
O erro é permissão negada no request pra verificar quais canais estão disponíveis.
Você experimentou limpar o cache das credenciais?
No Settings do Addon tem um link para fazer isso.

**Comment by havilson** [comment]
Ok, limpei o cache e funcionou novamente! Valeu!!!
