### ISSUE TITLE
Error brplay open recalbox

### ISSUE THREAD

**Issue by robgolbh** [olavopeixoto/plugin.video.brplay#49]
Ola Olavo, posso escrever em portugues? 
O Br Play funciona muito bem na versao do openelec. Mas preciso instalar ele no kodi que vem com o recalbox (no caso kodi 16.1 git:unknow

Quando clico pra abrir qualquer video on demand ou ao vivo, ele n me reporta nenhum erro, mas simplsmente nao abre o video. 
EM anexo o meu log. 

Abcs!!

Beto

[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/1674863/kodi.log)

**Comment by bruno-briner** [comment]
Você tentou com o Globo.com?

**Comment by robgolbh** [comment]
Ola bruno, vc diz o plugin globo.com ou c a conta da globo?
Achei que esse plugin tinha sido descontinuado por conta do brplay. vou conferir nele.

**Comment by bruno-briner** [comment]
Ao addon Globo.com.

Provalvelment não existirá mais suporte para o addon Globo.com, mas até pouco tempo atrás funcionava perfeitamente com o Kodi 16.1.
