### ISSUE TITLE
Erro de login

### ISSUE THREAD

**Issue by ramonbd** [olavopeixoto/plugin.video.brplay#5]
Sou assinante da Sky
Coloco o mesmo Login (cpf) e senha que utilizo para acessar o site da globosat play no navegador no addon e só dá erro de login. 

Kodi 17

**Comment by olavopeixoto** [comment]
Para poder dar suporte a provedores adicionais eu preciso da seguinte informação:

Abra uma janela privada (Incognito Window) para garantir que é uma nova sessão.
Abra a aba de desenvolvedor do chrome (Command + Option + I no MAC ou Ctrl + Shift + I no Windows) 3) Va na aba Network (Rede) e deixe ela aberta
Abra o site Globosat Play - https://globosatplay.globo.com/
Faça o login na sua operadora
Depois de logado aperte o botão direito na lista de requests da aba Network (Rede) e escolha "Save as HAR With Content" (Salvar como HAR com conteúdo)
Esse arquivo contém todas as requisições que foram feitas no servidor e terá o seu login e senha. Abra ele em um editor de texto e apague as informações confidenciais, pode usar um "find and replace" ou algo do tipo.

**Comment by CaioTheBrain** [comment]
Está funcionando normalmente com login SKY de novo.

**Comment by Cigano33** [comment]
Excelente, testado e aprovado na minha Android Box 2gbram, Android 6.0..
No começo começou a travar, mas era só as configurações de qualidade, pois minha internet é de apenas 5Mb, deixei em qualidade baixa, e rodou liso. Gostaria de saber se existe outros projetos para canais brasileiros. Já que existem transmissões digitais abertas.

**Comment by olavopeixoto** [comment]
Estou aberto a sugestões.
Tenho alguns na lista, mas quase todos tem DRM o que inviabiliza o addon para as versões atuais do Kodi:

- Telecine Play No Ar (Canal 24h),
- Fox Play,
- Esporte Interativo,
- TNT
