### ISSUE TITLE
Erro vivo index out of range

### ISSUE THREAD

**Issue by viniciusolima12** [olavopeixoto/plugin.video.brplay#50]
Boa Tarde,
comecei a usar o plugin e com meu usuário e senha da vivo dá esse erro acima...estou usando no kodi 17.6 e consigo usar normalmente com meu usuário e senha via app e site.

Obrigado

**Comment by viniciusolima12** [comment]
Só mais uma observação, testando a globo, tentei assistir ao jogo do psg x real madrid mas cai a cada 5min.
Não tenho esse problema ao fazer streaming de filmes por exemplo...tenho 25mb de internet.

Obrigado!

**Comment by bruno-briner** [comment]
Você leu a sessão de “issues closed”?

O mesmo erro foi discutido e a solução informada lá. 

Quanto aos “5 minutos”. Houveram também discussões sobre o assunto, que levaram o desenvolvimento dos proxies pelo Olavo. Para mim o que funciona de modo adequado é ajustar o addon em “auto” e instalar o addon inputstream adaptive “nativo” do Kodi.

**Comment by viniciusolima12** [comment]
Bom dia @bruno-briner 

Obrigado pela dica, realmente ainda não tinha lido a sessão "Closed" e agora vou fazer isso, mais alguns testes e se o problema persistir eu posto novamente.

Navegando aqui eu consegui usar apenas a versão 0.14, conversando com um colega ele me passou a 0.17 que o endereço indica para cá e talvez por falta de conhecimento meu sobre essa plataforma não tenha localizado, então o problema do login foi resolvido.

Obrigado.

**Comment by bruno-briner** [comment]
Todas as versoes do BRPlay são pre-release, sendo que a última é 0.014, datada de 15/Set/2017, e é esta versão que está no repositório "[brazilian.xbmc-addons](https://bitbucket.org/vitorhirota/repository.brazilian.xbmc-addons)", 

Porém o desenvolvedor Olavo já fez modificações no código diversas vezes após a liberação da 0.014, 16 "commits" para ser exato. Para você ter a versão mais atual basta baixar o código deste GitHub e substituir manualmente no seu Kodi. O repositório "[brazilian.xbmc-addons](https://bitbucket.org/vitorhirota/repository.brazilian.xbmc-addons)" só será atualizado quando o Olavo oficialmente liberar um novo "release".

Espero que isto esclareça você não ter encontrado versão maior que 0.014.

**Comment by viniciusolima12** [comment]
perfeito! muito obrigado pela explicação, for realmente esse arquivo que recebi, zipando ele vem como master.zip.

Fiz a alteração do inputstream e testarei em breve.

**Comment by bruno-briner** [comment]
Caso seus problemas forem soluicionados, favor fechar o "issue" para que o mesmo não permaneça aberto.

**Comment by viniciusolima12** [comment]
testei assistindo a globo por mais de 30min sem interrupções, muito obrigado pela ajuda @bruno-briner
