### ISSUE TITLE
Não reproduzindo conteúdo "ao vivo"

### ISSUE THREAD

**Issue by fernandotiegs** [olavopeixoto/plugin.video.brplay#51]
Olá, utilizo a v.0.0.14 c/ Kodi 17.4 na AppleTV 4, e a alguns dias o addon está com dificuldade p/ estabelecer a exibição do conteúdo "ao vivo" com usuário Globosat SKY. O addon passa um tempo tentando estabelecer uma conexão, e após uns 30s tentando, para, e volta a tela dos canais. O mesmo não acontece com o canal da Globo (GloboPlay), qual inicia a reprodução imediatamente.
Até esses dias, por durante alguns meses, estava perfeito, reproduzindo imediatamente todos os canais por horas. Utilizo internet fibra 60mb, e no addon sempre rodou em modo "Automático".

Não é um problema com o usuário SKY, pois o mesmo funciona normalmente no smartphone ou computador.
Alguém pode ajudar? Muito obrigado!

**Comment by altboy** [comment]
Olá Olavo,

Primeiro agradecer por todo o esforço de fazer este addon, está muito bom. 

Sobre o que já foi falado aqui, reforço que está acontecendo isso mesmo que o Fernando falou:

No meu caso uso o Kodi 17.4 com brplay 0.0.17 (Versão Master) com usuário NET.

Globosat play: há demora demasiada para abrir os canais, tanto no Kodi do meu smartphone e também quando utilizo o Chromecast, há canais que acabam nem abrindo. 

Globo play: há somente um canal que que abre consideravelmente rápido (Globo SP), porém o restante tem um grande delay para abrir excetuando a Globo PE que nem abre. 

Já verifiquei as opções: Executei o limpar cache e limpar credenciais, mas nada feito.

Aguardo a sua disponibilidade para auxílio nestas questões.

Grato pela atenção.

**Comment by olavopeixoto** [comment]
Olá,
esse problema passou a acontecer depois de alguma atualização ou sempre aconteceu?
Preciso de mais informações para poder ajudar. Manda o Log para tentar ver alguma coisa.
Aqui está tudo funcionando normal todos os canais ao vivo e on demand. Kodi 16, 17 e 18 e SPMC release e beta. Kodi >17 e SPMC release precisa do "inputstream.adaptive" habilitado, caso contrario pode acontecer o que você está dizendo, demora para iniciar o stream ou ate não tocar.
Testo na FireTV, Shield, MAC e Windows.

**Comment by fernandotiegs** [comment]
Olá, conferindo aqui, o inputstream ja estava ativo. Mais uma vez repassei tentando stream de todos os canais ao vivo, mas apenas o canal da Globo inicia reprodução.
Infelizmente não sei como criar um log na apple tv p/ ajudar.

**Comment by olavopeixoto** [comment]
Você pode tentar esse passo a passo aqui: https://kodi.wiki/view/Log_file/Easy
