### ISSUE TITLE
Possível adição do Telecine Pipoca

### ISSUE THREAD

**Issue by PauloDapper** [olavopeixoto/plugin.video.brplay#54]
Grande Olavo, o site Telecine Play adicionou uma aba chamada "No Ar"
Onde se dá pra assistir o Telecine Pipoca online (creio que mais pra frente vão adicionando os outros)
https://www.telecineplay.com.br/no_ar
Por ser um produto do serviço Globosat é possível a adição dele no Addon?

E sobre o canal PFC 24h que foi retirado na última atualização, tem previsão de volta?

**Comment by olavopeixoto** [comment]
O PFC foi consertado no ultimi commit.
A API que usamos pra buscar os detalhes dos canais não está retornando todas as informações de alguns canais, com isso não tem informação da programação para alguns canais como GNT por exemplo. No caso do PFC24H isso estava causando uma exceção no código e fazendo com que o canal fosse omitido.

O Telecine Play usa uma plataforma própria de transmissão diferente do resto dos canais Globo, por isso ainda não incluí os filmes no addon. O Canal ao vivo segue esse mesmo padrão.
Além disso todo o Telecine, incluindo o canal ao vivo usa DRM, com isso só irá funcionar no Kodi Leia (18) e em algumas plataformas onde o Widivine é suportado.

**Comment by PauloDapper** [comment]
Entendi! Valeu.
Realmente, os jogos do PFC voltaram ao normal, antes não tava rolando. 
Obrigado pela resposta, abraços.

**Comment by olavopeixoto** [comment]
O canal ao vivo não existe mais, mas o VOD do telecine está implementado.
