### ISSUE TITLE
Not the correct length

### ISSUE THREAD

**Issue by Derckie2** [olavopeixoto/plugin.video.brplay#55]
Hello,

I love your plugin but when I play Novellas or BBB the video is not the correct length.  I can see the listing on your plugin is more then one hour, but when it's playing it's only 15 mins.
When I try it with the same premium account in Chrome it is working ok. Issue is with and without proxy on.

I use your plugin on Kodi 17 on rasberry pi b+and your plugin is version 0.0.18 (downloaded from xbmcbrasil.net)

I hope you can help.

Thanks in advance,

Derck

**Comment by olavopeixoto** [comment]
Hi,
I need to understand your issue better.
It seems that you are using the "_Play multi part videos as playlist_". When enabled, this option creates a playlist with every "block" of the full video as a separated video in the playlist. Say the Novela you are trying to watch has 4 blocks of 15min each, it will add 4 videos to the playlist. If you advance to the next video it should play the following block.
