### ISSUE TITLE
VOD na íntegra não funciona

### ISSUE THREAD

**Issue by jeanmenezes** [olavopeixoto/plugin.video.brplay#56]
Primeiramente obrigado pelo excelente addon, em geral funciona com excelente qualidade.

Quando tento rodar vídeos on-demand da Globo, na íntegra, sempre recebo a mensagem de erro "Informações do vídeo não encontrado". Quando classifico por data e vou assistindo por partes roda perfeitamente (exemplo: capítulos de novela, não consigo ver o vídeo na íntegra mas consigo assistir as partes curtas separadas em sequência sem problemas). Alguma razão pra isso?
Estou rodando a versão instalada através do Github Browser, no Kodi Krypton sobre LibreElec 8.1. Minha configuração de reprodução está em Automático, com Inputstream Adaptive instalado e funcionando. Já limpei o cache várias vezes mas o problema persiste.

Grato pela atenção!

EDIT: atualizei para a versão 0.0.17 (master), limpei o cache e o problema persiste. As configurações estão com uma interface diferente, mas procurei manter em Automático e com o Inputstream Adaptive ativo.

**Comment by viniciusolima12** [comment]
Jean, não desenvolvi o addon mas os vídeos na íntegra são para assinantes Globoplay...
eu não sou assinante, então não tenho acesso a vídeos na íntegra, como não tenho acesso ao Combate e não tinha acesso aos canais BBB...

Vc é assinante? Caso seja, via site ou app do android estão funcionando os vídeos na íntegra?

Abraço

**Comment by jeanmenezes** [comment]
Putz, que vacilo o meu... Achei que as íntegras pra assinantes só valiam para episódios no mesmo dia. Obrigado, fechando o issue!
