### ISSUE TITLE
Problema com evento ao vivo no SporTV

### ISSUE THREAD

**Issue by havilson** [olavopeixoto/plugin.video.brplay#57]
Ontem eu tentei assistir ao jogo do Brasileirão no SporTV, Botafogo x Sport (PE). Entretanto não consegui pq fui redirecionado como se estivesse assistindo de PE, apesar de estar no RJ e estar configurado como sendo do RJ.
Tentei no SPMC (Kodi 16) em um FireTV stick.

**Comment by CaioTheBrain** [comment]
A configuração que você se refere é a do Globo Play.

No SporTV não passa os jogos ao vivo do Brasileirão mesmo, somente os VTs. É como se estivesse vendo pela TV no mesmo estado onde é realizada a partida.

**Comment by havilson** [comment]
Não, o jogo era em Recife e não no Rio de Janeiro. Estou no RJ e gostaria de assistir ao jogo que foi realizado em Recife, ao utilizar o sportvplay eu podia assistir ao jogo.

**Comment by CaioTheBrain** [comment]
Isso é porque no app do SporTV /Globosat Play tem a opção de ativar a localização.

No addon ainda não tem.

@olavopeixoto dá pra fazer isso?

**Comment by CaioTheBrain** [comment]
Você que não entendeu.

O addon NÃO tem a opção de localização.

Aquela lista é só para escolher qual das emissoras da Globo você quer assistir, podendo ser inclusive TODAS.

Não interfere no SporTV.

**Comment by olavopeixoto** [comment]
Implementado a opção de escolha de cidade para o globosat play.
Ainda não foi testado, veja se funciona pra você.

**Comment by CaioTheBrain** [comment]
Acabei de testar no jogo da Série B (Londrina x Coritiba) mas não funcionou.

Passa só o VT de Paraná x Atlético-PR.

Configurei nas cidades de Rio Branco e Palmas, e deu a mesma coisa nas duas.

**Comment by olavopeixoto** [comment]
As coordenadas das cidades estavam trocadas, atualizei.
Mas não sei se esse é o problema, como faço pra verificar a programação de cada cidade, existe algum site com essa informação?
O aduno está usando a mesma api do app, deveria buscar a programação correta

**Comment by CaioTheBrain** [comment]
Que eu saiba, isso só acontece nas transmissões ao vivo dos jogos do Campeonato Brasileiro - Séries A e B.

Por exemplo, agora no SporTV está passando Sport x Atlético/MG, menos para Pernambuco, para onde é exibido VT de algum outro jogo.

Amanhã às 21h00 passará Atlético/PR x Santos, menos para o Paraná.

www.esporteemidia.com/2018/05/veja-escalas-de-globo-sportv-e-premiere_29.html

**Comment by CaioTheBrain** [comment]
Testei hoje selecionando as cidades Palmas e São Paulo, mas ainda não funcionou.

O jogo era Ceará x Cruzeiro, menos para o Estado do Ceará.

Eu só consegui ver o VT de Palmeiras x São Paulo.

**Comment by havilson** [comment]
Também tentei assistir ontem ao jogo do Botafogo x Ceará e não funcionou, inclusive tentei usando uma VPN mas nada.

**Comment by olavopeixoto** [comment]
Agora está resolvido e testado. Verifique se está ok para vocês também.
