### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Digaogt** [olavopeixoto/plugin.video.brplay#58]
Ola, Olavo.

Qual foi a skin utilizada por você para os screenshots do seu README? Achei interessante o layout do aplicativo naquele formato.
Abraço e sucesso.

**Comment by olavopeixoto** [comment]
Olá, o skin é o FTV mod do sualfred: https://github.com/sualfred/skin.fTVfred
Mas eu modifiquei algumas coisas pro brplay. Segue a versão que eu usei nos prints: [https://filebin.net/835sx0rnm7bwsi99/skin.fTVfred-2.2.2.zip](https://filebin.net/835sx0rnm7bwsi99/skin.fTVfred-2.2.2.zip)

**Comment by pprado** [comment]
Olavo, o skin modificado por vc funciona para o Krypton e Leia? Aproveitando, você tem usado qual versão com o brPlay, Krypton ou Leia?

**Comment by olavopeixoto** [comment]
O Skin só funciona proa Jarvis, não modifiquei para as outras versões ainda.
Eu normalmente uso o Leia última nightly que tiver disponível. Atualizo pelo menos semanalmente. Mais porque estou desenvolvendo novas funções pra essa versão, como video com DRM.
O Leia está bastante estável pra mim.

**Comment by pprado** [comment]
Vou passar a usar o Kodi Leia para contribuir mais então... já estou usando a versão Main do Br Play e está show de bola, uma pena só que a Rede Bobo resolveu zonear a forma de autenticação. Parabéns pelo projeto!

**Comment by thigas88** [comment]
> Olá, o skin é o FTV mod do sualfred: https://github.com/sualfred/skin.fTVfred
> Mas eu modifiquei algumas coisas pro brplay. Segue a versão que eu usei nos prints: https://filebin.net/835sx0rnm7bwsi99/skin.fTVfred-2.2.2.zip

@olavopeixoto dá pra disponibilizar o link da versão do skin que vc utilizou, não está mais disponível.

**Comment by pathamo1** [comment]
Olavo, você tem uma versão nova da skin dos screenshot para a versão atual do kodi? Abraço.
