### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by bruno-briner** [olavopeixoto/plugin.video.brplay#6]
Olavo. Estarei tentando fazer um proxy usando a plataforma AWS EC2. Pelas minhas pesquisas os mais comuns proxy servers são baseados em Squid e TinyProxy.  O BRPlay funciona com o mais simples TinyProxy?

**Comment by olavopeixoto** [comment]
TinyProxy funciona perfeitamente.

**Comment by radols** [comment]
Oi Bruno, Olavo,

vocês tem alguma dica de como criar um servidor VPN em um RPi3 para deixar no Brasil como Proxy? Qual software vocês utilizam?

Muito obrigado
