### ISSUE TITLE
Falha de autenticação

### ISSUE THREAD

**Issue by renatomeneses** [olavopeixoto/plugin.video.brplay#60]
Boa noite Olavo,

Parece que com a necessidade de vincular a conta da TV por assinatura em uma conta globo.com o addon não está conseguindo autenticar nos canais globosat.

Você consegue verificar se é um problema apenas com meu usuário?

Obrigado,

**Comment by brunoramosrj** [comment]
Eu to com o mesmo problema.
Globo play funciona normal, mas o globosat play não autentica.

**Comment by olavopeixoto** [comment]
Não entendi exatamente o que é isso: "necessidade de vincular a conta da TV por assinatura em uma conta globo.com"

As contas são separadas, uma para a globo.com outra da sua operadora.

Favor enviar o log com o modo "debug" habilitado no Kodi e no Addon.

**Comment by felipebruni** [comment]
Oi Olavo. 

O que acontece é que agora a Globo inventou de vincular os dois acessos. Quando você entra no Globosat Play pela página, ele solicita que você vincule a uma conta existente da Globo.com.
Mas no plugin nenhum dos acessos é aceito e os canais da Globosat não aparecem. No meu caso apenas o Futura está aparecendo.
No meu plugin configurado no Kodi no Xbox está funcionando normal, porque já estava configurado. Mas estou tentando configurar do zero numa Mibox e estou tendo o mesmo problema dos colegas acima. Os canais simplesmente não aparecem.

**Comment by belsholff** [comment]
O mesmo comigo.

**Comment by brunoramosrj** [comment]
Fiz o teste pelo Chrome.
Como o login já estava salvo eu entrava no Globosat play automaticamente. Nem percebi que tinha mudado algo.
Quando saí da conta e fui entrar novamente pediu pra vincular a uma conta da Globo.com.

**Comment by felipebruni** [comment]
Estou fuçando no site do Globosat Play e descobri uma área para autorizar dispositivos. Por algum motivo o meu Xbox que já estava configurado aparece. Mas a Mibox não. É necessário inserir um código oferecido para vincular, mas o plugin não oferece (ou eu não encontrei). Acredito que esse seja o problema. A globo simplesmente mudou a forma de autenticação.

**Comment by brunoramosrj** [comment]
Felipe, acredito que essa parte não tenha nada a ver com o problema.
Essa área de autorizar dispositivos é apenas pros aparelhos que não fazem o login por aplicativo próprio. Por exemplo uma tv smart ou o próprio Xbox.

**Comment by felipebruni** [comment]
Puxa, então não faço ideia. Na Mibox não estou conseguindo de jeito nenhum mesmo. Estava ok até ontem, mas precisei formatar haha

**Comment by belsholff** [comment]
Boa tarde, @olavopeixoto 

Vai meu log ai para este problema.

Algumas observações:

- Lendo um pouco o log, bati na [URL](http://globosatplay.globo.com/-/auth/gplay)
 de autenticação e vi que ela está em HTTP. Não sei se de fato essa troca de senhas é feita em neste protocolo, pois assim que acesso a URL o o globo.com redireciona para uma URL em HTTPS, mas a boa notícia é que adicionando o `s` na URL o anúncio de erro do script logo abaixo deve sumir e trazer mais confiabilidade pro addon ao olhar de algumas pessoas.

- Quando eu acesso essa URL ela leva para uma página de autenticação da globo e o processo de autenticação segue duas etapas com o login da operadora e depois a associação de uma conta globo.com. E isso se repete TODAS AS VEZES que tentei login. Talvez isso dê um pouco de trabalho. Aliás, esses caras tão de brincadeira em pedir isso no login. =/

- Por fim, neste log também estão uns erros de conexão com os streams da Globo normal. Observei desde streams de 5 minutos (no máximo) até erros sequentes de conexão. Tá muito aleatório. Não sei se o InputStream age aqui tbm, mas quando habilitado nem inicia a conexão, e quando desabilitado pelo próprio addon nas configurações o comportamento acima é apresentado.

É isso... o que der pra eu ajudar, estamos ai!
Abs.

**Comment by yaisecb** [comment]
@olavopeixoto, acho que vai ser uma correção simples pra você. A OAUTH_URL que vc usa em /resources/lib/modules/globosat/auth.py continua correta. Só que se vc colar ela no navegador vai ver que a Globo subiu uma nova opção, que é realizar o Login na Globosat via uma conta existente na Globo. A conta da TV a cabo agora pode ficar associada a sua conta da Globo. 

![image](https://user-images.githubusercontent.com/40279401/41439779-f2f51b26-6fe0-11e8-86b6-18475e3a70fb.png)

Clicar no botão "Operadora" basicamente troca a window.location.href para /core/provider/?case=0&redirect_uri=https%3A%2F%2Fglobosatplay.globo.com%2F-%2Fauth%2Fgplay%2Fcallback&duid=&client_id=85014160-e953-4ddb-bbce-c8271e4fde74 (com certeza essas GUIDs devem variar) -- e aí você tem a lista de operadoras novamente, como antigamente.

Então pra tudo voltar a funcionar, talvez o mais simples seja simular um clique nesse botão antes de prosseguir com o login? Não sei, não vou dar PR porque não olhei o código a fundo, não vou saber as nuâncias do que você desenvolveu aí.

Abs, e valeu pelo add-on, funciona muito bem!

**Comment by olavopeixoto** [comment]
Obrigado pelas dicas.

consertado no master.

Agora só tem a opção de credencial da globo play que deve ser associado ao seu provedor através do site da globosat play

**Comment by pprado** [comment]
Funcionando perfeitamente no mi box com Android Oreo e Kodi 17.
