### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by PauloDapper** [olavopeixoto/plugin.video.brplay#64]
Na nova atualização, o EPG dos canais Globosat sumiram, vai adicionar de volta futuramente?

**Comment by olavopeixoto** [comment]
EPG está funcionando pra mim. Tenta limpar o seu cache pelo addon, se nao funcionar me manda o log.

**Comment by PauloDapper** [comment]
Limpei e não obtive resultado, testei no SPMC e no Kodi e sem sucesso. Só recebo o EPG do Futura, Combate, Globo e Universal.
Onde posso encontrar o LOG pra te enviar?

**Comment by olavopeixoto** [comment]
Habilite o debug no settings do BRplay alem de seguir esses passos:

https://kodi.wiki/view/Log_file/Advanced
