### ISSUE TITLE
Erros de atributo no multiprocessamento

### ISSUE THREAD

**Issue by digaogt** [olavopeixoto/plugin.video.brplay#65]
Ola, Olavo. Primeiramente gostaria de agradecer imensamente o seu empenho na manutencao periodica do plugin. Eu gostaria de saber se tem algum link para do repo do plugin (pq ele esta associado a versao 0.0.14 do addonBrasil) e também mencionar 3 erros de atributo na classe Live que estao sendo apresentados na geracao da lista de canais:
AttributeError: "'thread.lock' object has no attribute '_release_save'"
AttributeError: "'thread.lock' object has no attribute '_acquire_restore'"
AttributeError: "'thread.lock' object has no attribute '_is_owned'"

Obs: eles nao impedem em nada a execucao
Abracos e sucesso!

**Comment by olavopeixoto** [comment]
Não tenho ainda um repositório com atualizações.
Quanto aos erros eu preciso de um log completo com debug habilitado para tentar entender o problema.
Mas se não está impedindo em nada a execução provavelmente não é nada demais.

**Comment by olavopeixoto** [comment]
o repo esta aqui:
https://github.com/olavopeixoto/repository.brplayer/releases/download/v1.0/repository.brplayer-1.0.0.zip
