### ISSUE TITLE
Canais Ao Vivo sumiram.

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#66]
Após instalar a versão 0.021 master , canais ao vivo sumiram, apenas o canal futura está presente, outro ponto de observação, é que não possui local de autenticação com a conta globosat. Qual procedimento realizar.

**Comment by amaurigsilva** [comment]
Olá!

Está faltando mais uma entrada com "Usuário e Senha" para "ASSINANTES" da Globo Play. Dessa forma será possível assistir ao vivo os canais regionais da Globo (Afiliadas). Pois, nessa última atualização (0.0.21), só permite a visualização dos canais ao vivo para os assinantes de operadoras de TV que já possuem o login da sua operadora já associado ao login Globo.com.

**Comment by amaurigsilva** [comment]
Olá!

Está faltando mais uma entrada com "Usuário e Senha" somente para "ASSINANTES" da Globo Play. Dessa forma será possível assistir ao vivo os canais regionais da Globo (Afiliadas), como existia na versão 0.0.14.
Pois, na última atualização (0.0.21), só permite a visualização dos canais ao vivo para os assinantes de operadoras de TV que já fizeram a associação do login da operadora de TV  com um login Globo.com, o chamado Login Único.

**Comment by amaurigsilva** [comment]
Olá, Diegopeixotostich,

Acesse o site:    https://globosatplay.globo.com/   e crie o seu login Único. 

Entre no Globosat Play pelo login único Globo.com
O seu acesso mudou e agora você deve associar a sua assinatura a um login Globo.com (o mesmo usado para todos os serviços digitais Globo, como Cartola FC, Globoplay, Editora Globo e muito mais).
Escolha uma opção para começar

**Comment by amaurigsilva** [comment]
Olá, Diegopeixotostich,

Acesse o site: https://globosatplay.globo.com/ e crie o seu login Único. Se vc não tiver um e-mail Globo.com vc pode associar um email Google que vc já possua ou poderá criar um no e-mail Google e associá-lo.

Entre no Globosat Play pelo login único Globo.com
O seu acesso mudou e agora você deve associar a sua assinatura a um login Globo.com (o mesmo usado para todos os serviços digitais Globo, como Cartola FC, Globoplay, Editora Globo e muito mais).
Escolha uma opção para começar

**Comment by amaurigsilva** [comment]
Olá, Diegopeixotostich,

Acesse o site:   https://globosatplay.globo.com/ e crie o seu login Único. Se vc não tiver um e-mail Globo.com vc pode associar um e-mail Google que vc já possua ou poderá criar um novo e-mail Google e depois associá-lo.

"Entre no Globosat Play pelo login único Globo.com
O seu acesso mudou e agora você deve associar a sua assinatura a um login Globo.com (o mesmo usado para todos os serviços digitais Globo, como Cartola FC, Globoplay, Editora Globo e muito mais).
Escolha uma opção para começar"

**Comment by olavopeixoto** [comment]
Exatamente, a globosat agora obriga o usuário a associar um login globo.com para acessar o serviço. Com isso o BRplay não autentica diretamente nas operadoras, você deve fazer primeiro a associação do login no site da globosat play e configurar o seu login globo.com no BRplay.
O BRplay permite somente um login globo.com no momento, você deve associar o mesmo login globo.com do globo play no globosat play para poder acessar ambos os serviços pelo addon.

![screen shot 2018-07-05 at 16 45 39](https://user-images.githubusercontent.com/7496076/42333665-463b0f82-8073-11e8-89ab-78ec4dbc1efa.png)

**Comment by amaurigsilva** [comment]
Após essa mudança na forma na forma de login para quem já fez a associação
no site Globosat Play, faltou repetir a forma de login que já existia na
versão 0.0.14 e nas anteriores, onde precisava entrar com usuário/senha na
Globo.com para ver os canais locais da Globo (Afiliadas). Falta uma entrada
a parte somente para assinantes do Globo.com, pois, quando eu entrava
apenas com o e-mail de assinante da Globo.com (Agora Globo Play), mesmo SEM
logar com o usuário/senha da TV por assinatura, somente os canais Globo
(Afiliadas), funcionavam normalmente.

Em 5 de julho de 2018 12:48, Olavo Castro <notifications@github.com>
escreveu:

**Comment by 1bertox** [comment]
sou assinante da OITV e estou tendo o mesmo problema. so consigo assistir os canais da globo. os ao vivo da globosat não consigo mais abrir. já fiz o cadastro do login unico pelo https://globosatplay.globo.com/. porem agora da erro dizendo que meu usuário e senha são inválidos.  ainda estou na versão 0.014. como faço para usar a versão mais nova?

**Comment by amaurigsilva** [comment]
Olá, 

Entre em https://github.com/olavopeixoto/plugin.video.brplay , ao clicar no botão verde  "clone or download" no lado direito, será aberta a uma janela com o título "Clone with HTTP", em seguida clique na opção "download zip". Dessa forma, vc fará o download da última versão do Brplay.

**Comment by francoforte** [comment]
Estou tendo os mesmos problemas! Sumiram os canais da globo ao vivo, só aparece o futura. Não sou assinante do globosat e uso somente para ver os programas da globo, com uma conta do globoplay. Desde ontem os canais se foram. Tem que ser assinante do globsat agora para pegar novamente ou será que não funciona mais porque estou no exterior e eles bloquearam a TV ao vivo de vez?

**Comment by Throots** [comment]
De ontem pra hoje sumiram os canais da globo, só estão aparecendo os canais Globosat

**Comment by Throots** [comment]
Franco forte , sou assinante da Sky e e só estou conseguindo acessar os canais Globosat, de ontem pra o canal da Globo sumiu e não ta aparecendo mais, não tem nada a ver com o fato de estar no exterior

**Comment by rocha1973** [comment]
Boa tarde a todos, ótimo as dicas do site, estou conseguindo ver o Player, consegui configurar porem alguns canais aparecem a seguinte mensagem( RECURSOS DE VÍDEO NÃO ENCONTRADOS), Podem me ajudar?
