### ISSUE TITLE
Canais ao vivo da Globo (Afiliadas) não funcionam, com o login Único.

### ISSUE THREAD

**Issue by amaurigsilva** [olavopeixoto/plugin.video.brplay#67]
Olá!

Os canais locais da Globo não estão funcionando. Está faltando mais uma entrada com "Usuário e Senha" somente para "ASSINANTES" da Globo Play. Dessa forma será possível assistir ao vivo os canais regionais da Globo (Afiliadas), como existia na versão 0.0.14.

Pois, na última atualização (0.0.21), só permite a visualização dos canais ao vivo para os assinantes de operadoras de TV que já fizeram a associação do login de sua operadora de TV com um login Globo.com, o chamado Login Único.

**Comment by olavopeixoto** [comment]
O addon está assumindo que o seu login globo.com é único tanto para o globo play como para globosat play.

Você possui dois logins globo.com um para cada serviço?

**Comment by amaurigsilva** [comment]
Olá,

Criei um novo e-mail (gmail), e com esse novo e-mail (...@gmail.com), fiz a
associação do "login da operadora de TV" com esse e-mail novo criado, no
site da Globosat Play. Os canais Globosat funcionaram, exceto os canais
Globo (Afiliadas RJ, SP...).

E também fiz um teste associando um e-mail de um assinante do Globo Play
(...@globo.com) a outra operadora de TV por assinatura. Os canais da
Globosat Play funcionaram, sendo que os canais Globo (Afiliadas) não
funcionaram.

Pelo que percebi, os canais Globo (Afiliadas) funcionavam quando haviam as
duas opções de entrada, uma com usuário/senha para assinantes de TV por
assinatura  e a    outra com usuário/senha para assinantes da Globo.c.om

2018-07-05 12:43 GMT-03:00 Olavo Castro <notifications@github.com>:

**Comment by olavopeixoto** [comment]
O provedor de email (gmail, globo.com, hotmail, etc) não é relevante.
O único requisito é funcionar o mesmo email/senha tanto para o globosat play como para o globo play.
É o meu caso e está funcionando normalmente.

Se você fez esse teste e não funcionou experimente limpar o cache e as credenciais no addon.

**Comment by amaurigsilva** [comment]
O canal Globo RJ(SP, MG...) está funcionando para você?

**Comment by olavopeixoto** [comment]
Sim

**Comment by amaurigsilva** [comment]
Olavo,

Consegui fazer funcionar... foi falha minha!!!

Tá tudo funcionando perfeitamento.

Muito obrigado!

Parabéns pelo plugin BRPLAY... É sensacional!!!

**Comment by amaurigsilva** [comment]
Olavo,

Consegui fazer funcionar... foi falha minha. Peço desculpas!

Tá tudo funcionando perfeitamente.

Muito obrigado!

Parabéns pelo plugin BRPLAY... É sensacional!!!
