### ISSUE TITLE
Canais globosat pararam aqui

### ISSUE THREAD

**Issue by brunomilet** [olavopeixoto/plugin.video.brplay#68]
Canais globosat pararam aqui. Uso login da NET. A msg de erro é "recursos de vídeo não encontrados".

**Comment by digaogt** [comment]
Entra no site do Globosat (https://globosatplay.globo.com/). Eles unificaram com o login e a senha do globo.com! Vc precisa autorizar a sua conta para que volte a funcionar.

**Comment by brunomilet** [comment]
Obrigado. Achei que já tinha feito isso. Vou refazer e testar. Depois dou
feedback.

Valeu!


Em sáb, 7 de jul de 2018 19:55, digaogt <notifications@github.com> escreveu:

**Comment by 1bertox** [comment]
estou tendo o mesmo problema. so consigo assistir os canais da globo. os ao vivo da globosat não consigo mais abrir. ja fiz o cadastro do login unico pelo https://globosatplay.globo.com/.  porem agora da erro dizendo que meu usuário e senha são inválidos.  sou assinante da OITV

**Comment by digaogt** [comment]
Quando vc faz o cadastro de login único na pagina do Globosat Play, seu email e senha do Globo.com se tornam o login para ambos os serviços.
