### ISSUE TITLE
Login globosat

### ISSUE THREAD

**Issue by Istafull** [olavopeixoto/plugin.video.brplay#69]
Olá, na nova atualização não está aparecendo a opção de login do globosat, apenas aparece do globo play.

**Comment by leosmeira** [comment]
Agora é necessário vincular a sua conta da Globo.com com o login da Globo Sat. 

Faça o login no site abaixo que o mesmo pedirá para você vincular a conta da Globo.

https://globosatplay.globo.com/

**Comment by Istafull** [comment]
Eu fiz isso, mas mesmo assim não aparece para fazer o login do globosat só globo play. 
Segue imagem 
https://drive.google.com/file/d/10kagfmp_w9xlSVR9fhBKVqpQg05DOtck/view?usp=drivesdk

**Comment by digaogt** [comment]
Quando voce vincula a conta através do site Globoplay, seu email e senha da Globo.com servirá para o login em ambos.

**Comment by havilson** [comment]
O problema é quando o login e senha são diferentes. O que é meu caso por exemplo (senha).

**Comment by Istafull** [comment]
Realmente é isso, meu login também não é @globo.com e só carrega os canais globo play

**Comment by diegopeixotostitch** [comment]
Vinculei ao globo.com , porém apenas canal futura e Globo RJ aparecem. Através dos aplicativos e sites confio efetuar logon com login único. Alguém sabe como resolver?

**Comment by olavopeixoto** [comment]
Experimente a ultima versão, se não resolver favor mandar o log com a opção Debug habilitada no addon
