### ISSUE TITLE
plugin.video.brplay no repository.brplayer

### ISSUE THREAD

**Issue by digaogt** [olavopeixoto/plugin.video.brplay#71]
Mestre Olavo, voce se importaria em mover o plugin para o seu repositorio repository.brplayer? Assim, ficaria tao mais facil realizar as atualizacoes sem ter que reinstalar em cada dispositivo via arquivo zip.

Abraçao, sucesso e mais uma vez muito obrigado pela manutenção consistente do plugin.

**Comment by diegopeixotostitch** [comment]
Excelente opinião.

**Comment by olavopeixoto** [comment]
Atualizei la. Vou configurar o script pra ir automático em cada release
