### ISSUE TITLE
transmissão ao vivo para apos alguns minutos!!

### ISSUE THREAD

**Issue by 1bertox** [olavopeixoto/plugin.video.brplay#72]
Bom dia Olavo.
primeiro parabéns pelo ótimo app.
porem gostaria de notificar um problema chato que venho tendo com as transmissões ao vivo usando seu addon **BR PLAY 0.0.22**

quando seleciono qualquer canal ao vivo, pode ser da globo ou globosat, apos alguns minutos eles param de ser reproduzidos e ficam travados. ai tenho que sair da transmissão e abrir o canal novamente. porem fica nisso o tempo todo!!

quando usava a versão **0.0.14**, e deixava os canais rodando o dia todo e não parava, a não ser se a minha  internet caísse a conexão. mas não é esse o caso, pois minha conexão é de 50mb e é bem estavel.

fis o teste abrindo o sportv play pelo Smartphone e não travou em nenhum momento durante a transmissão do jogo ao vivo de ontem (16/07/18) mas pelo addon foram varias interrupções durante o jogo.

como disse, na versão anterior não tinha esse problema e talvez possa ser algo que não estou sabendo configurar.

de qualquer forma, deixo meu relato e se possível, aguardo uma solução para o problema informado caso seja possível sua solução.

**Comment by pprado** [comment]
Está usando qual versão do Kodi?

O inputStream esta habilitado?

**Comment by olavopeixoto** [comment]
Esse problema está acontecendo eventualmente com o plugin inputStream.adaptive habilitado.
Você pode desligar o uso desse plugin no settings para ver se resolve o seu problema.

**Comment by 1bertox** [comment]
Eu uso o libreelec com Kodi 18.
O imputstram estava desabilitado, mas ja faz algum tempo que não tenho problemas com travamentos.

Porém gostaria de saber porque os videos on demand do mega pix não inicia. Sempre que seleciono um filme ele não abre.
