### ISSUE TITLE
lista de jogos do PFC

### ISSUE THREAD

**Issue by 1bertox** [olavopeixoto/plugin.video.brplay#73]
apos a ultima atualização, não é possível mais escolher os jogos que vai passar pelo PFC. somente passa o mesmo jogo que é transmitido pelo sportv.

**Comment by joaoberg** [comment]
Aqui está assim também.
Não aparece mais os canais Premiere que tenho na minha conta globosat

**Comment by aacunha** [comment]
+1

**Comment by CaioTheBrain** [comment]
Aqui também. 

Na verdade não é necessariamente o mesmo jogo do SporTV

É o jogo do Premiere 24h (ou Premiere Clubes, antigo PFC 1).

Hoje mesmo passou América-MG x Internacional no SporTV e Grêmio x São Paulo no Premiere 1.

**Comment by Throots** [comment]
Estou com o mesmo problema, deve ser geral

**Comment by olavopeixoto** [comment]
Resolvido na ultima versão

**Comment by CaioTheBrain** [comment]
Aqui também, mesma coisa.

Desinstalei e instalei a versão 0.0.21 de volta mas não adiantou.

Só aparecem o Futura e o Gloobinho mas nenhum dos dois abre.

**Comment by 1bertox** [comment]
bom dia Olavo. Como copio o log para te enviar? Sou leigo nisso.

Eu reparei que existe dois logins, uma para usar o da globoplay para ambos os serviços da globo e globosat, e a opção de usar o login unico do globo play para os dois serviços. 
Porém aqui não funciona mesmo eu colocando login e senha do globosat play.

**Comment by 1bertox** [comment]
Outro detalhe, se eu deixar apenas o login pela opção do globosat play, só aparece o canal futura.

**Comment by 1bertox** [comment]
[01_KODI.log](https://github.com/olavopeixoto/plugin.video.brplay/files/2249085/01_KODI.log)
não sei se é isso. mas ativei o debug log do addon e copiei o arquivo log do kodi completo.

**Comment by olavopeixoto** [comment]
Obrigado pelo Log.
Estava faltando um arquivo no ultimo commit.
Me diz se funciona pra você agora.

**Comment by 1bertox** [comment]
Boa Tarde.
@olavopeixoto , tudo funcionando normal aqui, porem sobre essa interface do BRPlay que é mostrada nas telas, como se ativa ?
![image](https://user-images.githubusercontent.com/41131545/43908856-662befc4-9bcf-11e8-9cd0-c95e2479d7dc.png)

pois a interface que tenho aqui é muito diferente.

**Comment by 1bertox** [comment]
Entendi. 
Mas pelo jeito a skin so funciona nas versões antiga do Kodi. Eu estou usando o kodi 18 leia.

**Comment by thigas88** [comment]
> Respondido nessa issue:
> #58

@digaogt o link para o skin modificado não está mais disponível, teria como disponibilizar novamente?

**Comment by Titorj** [comment]
Olá @olavopeixoto, no meu Kodi não aparece os canais Premiere apesar de eu ter, deveriam aparacer?
Será que fiz alguma coisa errada?
Abaixo segue o Log, se puder me ajudar eu agradeço.

Raspbarry Pi 3 LibreELEC
Kodi 18.0-RC5
[01_KODI.log](https://github.com/olavopeixoto/plugin.video.brplay/files/2800426/01_KODI.log)

**Comment by helviojr** [comment]
Aparentemente consigo acessar os demais canais Premiere na opção "Próximos Jogos", mas como só haverá jogo amanhã à noite, pode ser o motivo dos canais não estarem aparecendo?

**Comment by olavopeixoto** [comment]
Os jogos que estão sendo transmitidos ao vivo aparecem junto com os demais canais, a "pasta" Próximos Jogos só tem a lista de jogos futuros mas não tem video associado.

**Comment by helviojr** [comment]
Testei agora. Durante os jogos, os canais aparecem. Fantástico! Em Próximos Jogos há um stream de uma tela verde escrita Premiere, igual aos canais no cabo quando não há jogo sendo transmitido. 

Tudo perfeito!
