### ISSUE TITLE
Sbt online

### ISSUE THREAD

**Issue by aacunha** [olavopeixoto/plugin.video.brplay#74]
Olavo, o sbt está com streaming ao vivo via youtube, não sei se daria para adicionar:

https://youtu.be/sjRIQBAQj-0

**Comment by olavopeixoto** [comment]
adicionei no brguide o sbt entre outros canais abertos na internet

**Comment by helviojr** [comment]
Sei que é antigo, mas já que não fechou o issue ;) , o que é o BRGuide? Todos os canais disponíveis como ou usando os recursos de IPTV do Kodi?

**Comment by olavopeixoto** [comment]
BRguide é um add-on pra assistir somente os canais ao vivo com epg e e navegação apropriada pra acompanhar TV ao vivo. Ele não usa PVR/IPTV do Kodi, continua sendo um addon em python mas com UI própria.

**Comment by helviojr** [comment]
Olavo, não consigo assistir aos canais YouTube. Diz que o vídeo não está disponível pra mim (pra meu dispositivo ou minha localidade, não me lembro agora). O addon Youtube está funcionando.

**Comment by olavopeixoto** [comment]
O SBT normalmente só funciona dentro do Brasil. Você consegue acessar pelo YouTube? O link que está hardcode no addon é do SBT Rio.

Os demais canais do YouTube deveriam funcionar ok: senado, shoptime, etc.

**Comment by helviojr** [comment]
O erro é do addon YouTube: "This video is unavailable on this device". Não estou usando qualquer VPN, troca de país ou algo do tipo.

Meus testes:
1. Addon hardcoded: https://www.youtube.com/channel/UCsRfBAspa72ExrsN347W2xg/live - FUNCIONA (da primeira vez ficou carregando mas depois funcionou)
2. Buscando o canal no YouTube: https://www.youtube.com/user/SBTRJ/live - FUNCIONA
3. Buscando vídeo no YouTube: https://www.youtube.com/watch?v=i4pHalUONcY - FUNCIONA
4. Buscando no AddOn YouTube - FUNCIONA

Canais como TV Justiça e Shoptime também têm erro do YouTube (Vídeo unknown). Certo que está havendo alguma incompatibilidade.

**Comment by olavopeixoto** [comment]
Você está usando a última versão? A última versão não usa o plugin do YouTube

**Comment by olavopeixoto** [comment]
Implementado SBT no BRplay na versão 1.0.8
