### ISSUE TITLE
Universal Channel - ao vivo

### ISSUE THREAD

**Issue by CaioTheBrain** [olavopeixoto/plugin.video.brplay#75]
A Globosat liberou o streaming "ao vivo" do Universal Channel e agora o canal aparece duas vezes na lista.

Porém nenhum funciona.

**Comment by olavopeixoto** [comment]
O canal Universal agora tem DRM.
Vou ver se coloco pra funcionar no Kodi Leia.

**Comment by CaioTheBrain** [comment]
DRM no live streaming?

É o primeiro da Globosat a ter isso? Ou o Telecine Pipoca também tem? 

Achei que fosse apenas ondemand. 

Então sem chance de funcionar no Kodi 17 (Krypton), né?

**Comment by olavopeixoto** [comment]
É primeiro da plataforma globo live streaming, o Telecine Pipoca também tem mas usa uma plataforma diferente.

Sem chances de funcionar no Krypton.

**Comment by pprado** [comment]
Instalando o Kodi 18, o que é preciso fazer pra habilitar o DRM e conseguir acessar o Universal Channel?

**Comment by helviojr** [comment]
Ok, também preciso de ajuda aqui. Pensei ser um outro problema #101 , mas meu problema com Megapix, Universal, Studio Universal é o DRM. Tenho Leia 18 e addons InputStream Adaptative 2.4.2, InputStream Helper 0.4.3 habilitados. Alguma outra configuração se faz necessária?

**Comment by olavopeixoto** [comment]
Depende da plataforma.
O Add-on está usando o Widevine. Só funciona no Android ou então em plataformas com libssd_wv. Eu só testei no Android (Shield e FireTV) e no MacOS.
O add-on script.module.inputstreamhelper instala automaticamente pra você se estiver em uma plataforma compatível.

**Comment by helviojr** [comment]
Bem, uso Widevine com o addon plugin.video.netflix, por isso achei que já tinha os pré-requisitos. Do README do addon:

`Widevine DRM For non-Android devices, will automatically be installed (by inputstream.helper). Please make sure to read the licence agreement that is presented upon Widevine installation, so you know what you´re getting yourself into.`

**Comment by helviojr** [comment]
Eu tenho:
Ajustes - Streamimg - Advanced:
DESLIGAR "Disable InputStream.Adaptive"!!!!
Eu também LIGUEI "Prefee Dash over HLS" porque não sei o que é, mas fiquei com a impressão que Dash tem a ver com Widevine. 

Não tenho nem ideia por que deixei o InputStream.Adaptive desativado (será o padrão?). Desculpem-me pelo tempo perdido em algo tão óbvio. A mensagem mandava habilitar, mas achei que fosse no addon InputStream, não bos ajustes do próprio BR Play.

Olavo, parabéns! O trabalho está magnífico!

**Comment by helviojr** [comment]
@CaioTheBrain , @pprado , vocês também conseguiram os canais ao vivo e sob demanda Universal etc. que usam DRM, Widevine? Desculpe-me perguntar, mas tenho impressão que há muitos Issues já resolvidos que permanecem abertos.

**Comment by CaioTheBrain** [comment]
Eu não tenho mais acesso aos canais da Globosat. 

Mas quando eu tinha testei os canais com DRM mas não funcionaram. Eu usei o Kodi 18.5 mas não lembro como estavam o InputStream Adaptive nem o InputStream Helper.

**Comment by pprado** [comment]
Estou com todos os canais funcionando perfeitamente, inclusive os com DRM.

Em sáb, 1 de fev de 2020 22:37, helviojr <notifications@github.com>
escreveu:

**Comment by thorandrade** [comment]
Eu também não estou conseguindo ver conteúdo com DRM, testei tanto no pc quanto android, ambos com InputStream Adaptive nem o InputStream Helper, e utilizo netflix e amazon vod tranquilamente.

Adicionar o BR Play tambem me trouxe um problema que não sei bem como resolver, agora quando quero reproduzir alguma coisa em um plugin (youtube, netflix, amazon e o br play) ao apertar enter não reproduz, é preciso entrar no menu de contexto e mandar reproduzir por lá.

**Comment by pprado** [comment]
Aqui funcionando corretamente. Pelo nível de problemas relatados, deve ser
problema no Kodi.

Refaça a instalação do Kodi e do Brplay.

Atualizações de plugins no Kodi já corromperam mais de uma vez minhas
configurações. Só resolvendo depois de refazer toda a instalação.

Em dom, 12 de abr de 2020 00:54, thorandrade <notifications@github.com>
escreveu:

**Comment by thorandrade** [comment]
Consegui resolver desmarcando a caixa de desabilitar o inputStream no br play,mas o som do vídeo é cortado após um segundo.

**Comment by ReinaldoPEIXOTO** [comment]
alguem tem o script sky brasil ou globo play
