### ISSUE TITLE
Sem acesso ao GloboSat Play ... 

### ISSUE THREAD

**Issue by diegopeixotostitch** [olavopeixoto/plugin.video.brplay#76]
Ja criei o login único junto a operadora, e consigo conectar perfeitamente pelo site e aplicativos, porém mesmo com a versão 0.22 não consigo acesso aos canais globosat, o mesmo só exibe os globo plays e o canal futura. Já limpei cache, ja tentei login antigo, nada habilita os canais globosat.

**Comment by pprado** [comment]
Após o commit do dia 30/07/2018, aconteceu o mesmo comigo. Voltei para a versão anterior do commit e consegui acesso aos canais globosat.

**Comment by 1bertox** [comment]
@olavopeixoto , bom dia novamente.
não sei se é isso. mas ativei o debug log do addon e copiei o arquivo log do kodi completo.
[01_KODI.log](https://github.com/olavopeixoto/plugin.video.brplay/files/2249093/01_KODI.log)

**Comment by joaokemmer** [comment]
Os Aqui só aparece  as globo e o futura na versão 0.22 . Porem os globo da erro. Na 0.21 aparece todos mas nao funciona nem aparece os globo. Sera q tem algo errado na minha config?

**Comment by pprado** [comment]
Eu estava com o mesmo problema, fiz todas as combinações possíveis de localização e não tive sucesso. Contudo, eu precisei reinstalar o kodi 17 do zero. Removendo todos os arquivos com o ES File Manager, mais do que simplesmente desinstalar. Para minha surpresa os canais globo passaram a funcionar.
Como já que estava com a mão na massa, resolvi remover novamente o Kodi 17 e instalar o Kodi 18 alpha 3, felizmente tudo funcionou, precisei apenas nesse caso desabilitar o uso do inputStream adaptativo no Kodi.
Provavelmente algum lixo de configuração antiga está gerando erro.

**Comment by helviojr** [comment]
Qual é o estado atual do Addon? Está funcional? Eu não consegui fazer funcionar este (que foi recomendado) nem outros Addons de globo.com e Globosat. Gostaria de saber se há um commit estável ou alguma operação prévia a ser feita, ou se o addon realmente não está funcionando no momento. Obrigado.

**Comment by pprado** [comment]
Funcionando perfeitamente aqui, inclusive os canais com DRM.

Em dom, 29 de dez de 2019 08:07, helviojr <notifications@github.com>
escreveu:
