### ISSUE TITLE
BRplay no Kodi 18

### ISSUE THREAD

**Issue by aleprovencio** [olavopeixoto/plugin.video.brplay#77]
Alguém consegue rodar?

**Comment by digaogt** [comment]
A base do Kodi 18 (ainda em versão beta) é Python 3, mesmo que alguns recursos de Python 2 (base do Kodi 17 e anteriores) sejam convertidos para funcionar no Kodi 18. Penso que quando lançar a versão oficial do Kodi 18 que é uma prévia de migração definitiva para o Kodi 19 (que somente suportará Python 3) valeria a pena converter todo o addon do zero para Python 3.
Acho que demorará um pouco mais de tempo para que esse addon, bem como muitos outros, funcionem 100% no Kodi 18

**Comment by pprado** [comment]
Sim. Roda perfeitamente.

Baixe e instale a versão do repositório.

Na configuração do BRPlay, encontre a opção "Desabilitar InputStream Adaptative" e a marque.
