### ISSUE TITLE
Exibir edições sem filtrar por data

### ISSUE THREAD

**Issue by CaioTheBrain** [olavopeixoto/plugin.video.brplay#78]
Olavo, no antigo addon Globo.com as edições dos programas dos canais Globosat não eram filtradas por data. Apareciam todos numa lista geral, em ordem cronológica, sem que fosse necessário selecionar "vídeos mais antigos" sempre que se quisesse acessar uma edição anterior à que estava na tela. 

E isso faz muito sentido pois, diferentemente do conteúdo da Rede Globo, os programas dos canais pagos não são divididos em trechos de uma mesma edição. 

Teria como implementar isso no BR Play, nem que seja como opção?

**Comment by olavopeixoto** [comment]
O addon foi todo alterado pra nova API da globo, não deve ter mais problemas desse tipo.
