### ISSUE TITLE
-BR PLAY - Adicionar RBS-RS ou NSC-SC

### ISSUE THREAD

**Issue by joaokemmer** [olavopeixoto/plugin.video.brplay#79]
Bom dia. Olavo, existe a possibilidade de adicionar no canais globo, Rbs Porto Alegre ou alguma NSC Santa Catarina. Moro em SC e acharia interessante se tivesse uma dessas opções. 
Seu addon na ultima versão esta perfeito, apenas, como moro aqui nessa região, se tivesse essa opção ficaria top.. 10 mesmo.. 
Obrigado pela atenção desde já

**Comment by pprado** [comment]
A RBS-RS não tem nenhum serviço de transmissão de sua programação pela Internet. Até onde sei, o mesmo acontece com a NSC-SC.
O BRPlay necessita que os canais tenham a disponibilidade do serviço na internet.

**Comment by olavopeixoto** [comment]
Você pode usar as coordenadas da localização que desejar, se existir a transmissão para a localidade ela irá aparecer
