### ISSUE TITLE
Ordenar os canais ao vivo

### ISSUE THREAD

**Issue by atsjiedel** [olavopeixoto/plugin.video.brplay#80]
Olá!
Seria possível colocar uma opção de ordenação dos canais ao vivo?
Por exemplo, Por ordem alfabética de nome (asc/desc) ou até por ordem de número de canal.
Atualmente não existe regra, cada vez que se acessa esta opção os canais são exibidos em uma ordem diferente, dando um trabalhinho extra ficar procurando o canal que se deseja acessar.

Vlw!

**Comment by olavopeixoto** [comment]
Atualmente a regra é programação mais recente. Na frente da lista está sempre o programa que começou por último.
O motivo desta ordem é que no widget da skin que eu uso aparecem somente 5 canais sempre na home screen. Se tiver ordem fixa sempre aparecem os mesmos canais.
Com essa ordenação da pra ver sempre a programação mais recente.

Vou verificar a possibilidade de incluir outras ordenações

**Comment by CaioTheBrain** [comment]
@atsjiedel, alternativamente você pode usar o script BR Guide do próprio Olavo, que ordena os canais pelo nome. Só está faltando o PFC 24h dos lineares. E ele mostra todos os canais, mesmo aqueles que não tem autorização, ao contrário do BR Play que tem a opção de ocultá-los, caso queira.

Você pode instalá-lo a partir do repositório do desenvolvedor:

https://github.com/olavopeixoto/repository.brplayer/archive/master.zip

@olavopeixoto, por que não atualiza a versão do BR Play no seu repositório? Ainda está na 0.0.5, enquanto o repositório do Kodi Brasil Forum está em dia com a versão 0.0.22.

**Comment by olavopeixoto** [comment]
A última versão permite ordenar os canais por nome do canal [NAME], nome do provedor [STUDIO] (Globoplay, Globosat, Oi Play, TNT, etc), nome do programa [TITLE] ou horário de inicio do programa [DATE ADDED]
