### ISSUE TITLE
Canais travandos

### ISSUE THREAD

**Issue by useribip** [olavopeixoto/plugin.video.brplay#82]
Em todos os modos (adptativo, etc) os canais ficam travandos e voltando uns segundos antes a reprodução. Tenho um internet boa para rodar os canais (15mb) o que poderia ser o problema? Grato!

**Comment by joaokemmer** [comment]
Também tenho notado isso , nos ultimos dia, pois até ai todos iam bem a  qualquer hora, e agora travam bastante onde antes rodavam liso , nao mudei nada no kodi. Sera q é servidor do Globoplay ou algo assim.

**Comment by digaogt** [comment]
Aqui rodando normalmente, todos os canais!
Provavelmente algum na conexão de internet mesmo.

Rodrigo Gonçalves Torres
