### ISSUE TITLE
Videos ON DEMAND

### ISSUE THREAD

**Issue by 1bertox** [olavopeixoto/plugin.video.brplay#84]
bom dia @olavopeixoto .
poderia me ajudar?

estou usando os canais ao vivo sem problema. porem estou tentando executar os videos On demand, mas quando seleciono o vídeo que quero ver, por exemplo, algum video do Globo News, o vídeo parece que vai abrir, mas volta para a lista de videos. e não abre.

Já tentei abrir varios conteúdos de canais diferentes (combate, sportv, multishow), mas infelizmente nenhum esta mais abrindo. 

Eu já consegui assistir varias vezes os videos pelo On Demand, mas já faz algum tempo que não estou conseguindo mais assistir nada.

vou deixar o log para que você possa analisar e ver se identifica o erro que possa esta causando isso.

Grato.

[LOG KODI](http://ix.io/1nlQ)

**Comment by digaogt** [comment]
Ola, 1bertox.

Eu testei os videos OnDemand e percebi que os videos nao encriptografados estao funcionando, tipo Multishow, GloboNews, etc. Eu so precisei ajustar no InputStream.Adaptive para "Ignorar a Resolucao do Display".
Agora, os videos encriptografados (DRM) do Megapix, por exemplo, nao estao funcionando e estou tentando desvendar o motivo, e ja testei com todas as variacoes de setup do InputStream.Adaptive e do menu Stream do BrPlay.

**Comment by digaogt** [comment]
O problema dos filmes do MegaPix é que eles não estão conseguindo ser descriptografados pelo InputStream.Adaptive.
ERROR: AddOnLog: InputStream Adaptive: No decrypter found for encrypted stream
Acompanhando para ver se o Olavo consegue alguma solução.

**Comment by 1bertox** [comment]
> O problema dos filmes do MegaPix é que eles não estão conseguindo ser descriptografados pelo InputStream.Adaptive.
> ERROR: AddOnLog: InputStream Adaptive: No decrypter found for encrypted stream
> Acompanhando para ver se o Olavo consegue alguma solução.
> Obs: Testado no Kodi 18 e Kodi 17.6

@digaogt , tudo bem?
então, eu uso o libreelec com kodi 18, e deixo o inputStream desativado nas configurações do BRPLAY por causa dos travamentos nos canais ao vivo.
porem ao ativar o InputStream, eu consegui abrir os Videos On Demand, inclusive os filmes do Mega Pix.
porem começo a ter os videos ao vivo começam a travar com muita frequência.

então pelo que percebi, eu tenho que desativar o inputStream para canais ao vivo, e ativar o inputStream para assistir os videos On Demand.

não sei se é correto, mas é o que funcionou para mim.

Abçs.

**Comment by 1bertox** [comment]
Bom dia.
Atualizando a informações que deixei anteriormente, deixando o inputStream desativado nas configurações do BRPLAY não consigo abrir os Videos On demand. 

Deixando o inputStream ATIVADO nas configurações do BRPLAY, consigo abrir os videos On Demand, porem os videos do Mega Pix, Studio Universal, universal channel e SYFY abrem os videos, mas sem áudio.

segue uma foto da tela de informações de um filme do Mega Pix sendo executado, aonde na parte de Stream de Áudio aparece a informação de áudio "UNKNOWN".



![image](https://user-images.githubusercontent.com/41131545/45950900-e3788380-bfd7-11e8-85cc-3cac5701d470.png)

**Comment by rocha1973** [comment]
Bom dia a todos.
tambem etou com dificuldade, quando tento abrir o megapix aparece a mensagem RECURSOS DE VIDEO NA ENCONTRADOS, PODEM ME AJUDAR:

**Comment by Thicoxxi** [comment]
Boa tarde,
Estou tendo o mesmo problema, porém o audio começa a ser executado do nada para. Será que alguém pode ajudar. Uso o kodi 18.5 em um raspberry pi 3.

**Comment by thorandrade** [comment]
Boa noite também estou com esse problema, após desmarcar a caixa de desabilitar o inputStream no br play, até consigo abrir o vídeo mas o som é cortado após um segundo.

**Comment by helviojr** [comment]
Boa noite. Voltei a usar o brplay e me deparei com esse problema de novo. Universal sem audio nem legenda. Isso não foi acertado

**Comment by olavopeixoto** [comment]
O problema do audio não é no BRplay é no inputstream.adaptive. Ainda não foi consertado.
Vou ver se consigo dar um jeito alternativo pelo addon.

**Comment by olavopeixoto** [comment]
O problema de audio nos streams dash do globoplay e canais globo foi resolvido.
