### ISSUE TITLE
Sem canais GlobosatPlay

### ISSUE THREAD

**Issue by pprado** [olavopeixoto/plugin.video.brplay#85]
Não sei se houve alguma mudança, mas hoje de noite os canais globosat não estão mais aparecendo, apenas os da globoplay.

Estou usando o Kodi 18 e a última versão do BrPlay. Até hoje de tarde estava funcionando.

[]'s

**Comment by pprado** [comment]
Segue o log de DEBUG.

[kodi.log](https://github.com/olavopeixoto/plugin.video.brplay/files/2453034/kodi.log)

**Comment by joutinho** [comment]
Oi Pessoal, 
FELIZ 2019 PARA TODOS !!!
Tem alguém mais sem ver os canais. Pra mim parou aqui hoje de manhã 8 de Janeiro 2019.
Qualquer ajuda é bem vinda !!!
