### ISSUE TITLE
suporte para o provedor vivo no globosat play

### ISSUE THREAD

**Issue by tiagoluizo** [olavopeixoto/plugin.video.brplay#9]
boa tarde a todos

gostaria de usar o addon mas aparentemente não é compatível com o provedor vivo.

existe previsão para adicionar esse suporte?

abraços.

**Comment by olavopeixoto** [comment]
Para poder dar suporte a provedores adicionais eu preciso da seguinte informação:

1) Abra uma janela privada (Incognito Window) para garantir que é uma nova sessão. 
2) Abra a aba de desenvolvedor do chrome (Command + Option + I no MAC ou Ctrl + Shift + I no Windows) 3) Va na aba Network (Rede) e deixe ela aberta 
3) Abra o site Globosat Play - https://globosatplay.globo.com/ 
4) Faça o login na sua operadora 
5) Depois de logado aperte o botão direito na lista de requests da aba Network (Rede) e escolha "Save as HAR With Content" (Salvar como HAR com conteúdo)

Esse arquivo contém todas as requisições que foram feitas no servidor e terá o seu login e senha. Abra ele em um editor de texto e apague as informações confidenciais, pode usar um "find and replace" ou algo do tipo.

**Comment by tiagoluizo** [comment]
@olavopeixoto obrigado pela rápida resposta. envio aqui o arquivo solicitado. conforme a sua orientação, suprimi todas as informações confidenciais (cpf e senha). se precisar de mais alguma coisa é só me pedir.

abraços e até mais

https://drive.google.com/file/d/0B0TtF16MU48oSXgyVGRWM0FfSEk/view

**Comment by olavopeixoto** [comment]
Eu fiz uma alteração que deve resolver o seu problema, pode testar a última versão do master?
Não tem release ainda. É só copiar os arquivos por cima do seu addon.

**Comment by tiagoluizo** [comment]
@olavopeixoto funcionando perfeitamente. o login é realizado e os vídeos tocam normalmente.
realizei testes na categoria ao vivo e on demand e tudo funcionou.

SPMC v. 16.4.2 Jarvis no Android 4.4
Kodi v. 16.1 Jarvis no Android 4.4
Kodi v. 17.3 Krypton no Windows 7

**Comment by tiagoluizo** [comment]
obrigado!
