### ISSUE TITLE
2019 Os canais sumiram hoje 8 Jan 2019

### ISSUE THREAD

**Issue by joutinho** [olavopeixoto/plugin.video.brplay#90]
Oi Pessoal, 
FELIZ 2019 PARA TODOS !!!
Tem alguém mais sem ver os canais. Pra mim parou aqui hoje de manhã 8 de Janeiro 2019.
Qualquer ajuda é bem vinda !!!

**Comment by digaogt** [comment]
Aqui todos continuam funcionando normalmente! Esta apresentando algum erro ou somente sumiram os canais? Caso tenham somente sumindo os canais sem erro, entre no settings, menu General, limpe o cache e as credenciais e tente novamente. 
Outra coisa q eu percebi é que agora a pagina da Globo/Globosat pediu autenticação de login antes de eu iniciar o video. Tente abrir no computador via browser com seu login para ver se abre o canal também.

Sucesso,

Rodrigo

**Comment by pprado** [comment]
Mesmo problema por aqui. Apenas os canais da Globo estão aparecendo. Nenhum Globosat aparece na lista dos Ao Vivo.

Consigo entrar na lista do programas On Demand da Globosat, mas nenhum funciona.

Não qualquer sinalização de erro, apenas não carrega.

Abs

**Comment by joutinho** [comment]
Olá pprado, não sei qual plataforma você está usando mas eu fiz o seguinte e resolveu o meu problema dos canais não aparecerem;
Desinstalei o Kodi (só uso ele pro BrPlay e para uma lista de IPTV).
Reinstalei o Kodi e o BrPlay e configurei o login e a senha da globoplay. 
Meus canais on demand voltaram a aparecer e toca normal programas antigos tipo noticiários, séries, novelas etc...
No entanto, canais ao vivo não tenho nada. Se eu clicar em Live não aparece nenhum canal.
Espero que funcione pra você o que eu fiz pois os passos anteriores que o Rodrigo acima me orientou a fazer infelizmente não funcionaram.

Agora se alguém souber como faz para assistir canais ao vivo por favor toda a ajuda é bem-vinda pessoal, afinal a ideia aqui é uns ajudarem os outros né.

**Comment by pprado** [comment]
@joutinho depois de uns dias, alguns canais on demand voltaram a funcionar sem fazer nada, não são todos e está bem aleatório. Uso Kodi 18 RC2 com Android TV numa Mi Box 3.

Quanto aos canais ao vivo, só globo play. Globosat play segue morto.

**Comment by digaogt** [comment]
Olá, Joutinho.

Eu uso o BRPlay no mesmo aparelho que você, o Nvidia Shield TV e todos os canais seguem funcionando perfeitamente. Você consegue assistir aos canais na página web da Globoplay e Globosat normalmente? Ja fez a integração do seu login do Globoplay com o da Globosat na página deles?
Experimentou utilizar uma versão anterior do BRPlay para ver se funciona?
Já testou em um Kodi instalado em um Mac/PC para ver se funciona?
Se você está fora do país como eu, seu VPN está ativo? (sem o VPN ativo no Brasil, às vezes ele não gera a lista com os todos os canais).
Já tentou usando o addon BRGuide do Olavo? (ele funciona independente ao BRPlay)

Abraços e sucesso,

Rodrigo Gonçalves Torres

**Comment by digaogt** [comment]
Esqueci de mencionar também. Tenta apagar os arquivos cache.db e settings.xml manualmente da pasta userdata/addon_data/plugin.video.brplay (não se preocupe que eles são gerados automaticamente na execução do addon, sendo necessário reconfigurar seu login sem Settings)

Abraço.

Rodrigo

**Comment by joutinho** [comment]
Grande Rodrigo,
Olha aí você dando aquela força novamente! Agradeço já de cara a ajuda !!!
Agorinha mesmo estou no Brasil visitando a família mas voltando pra casa semana que vem vou conferir esses passos que você mencionou.
Quanto a integração GloboPlay com GloboSat vou ter que perguntar pro meu sogro pois eu uso o login dele da GloboPlay. Quanto a VPN eu nunca usei especificamente com o Add-on mas quando deu o primeiro problema de sumirem os canais eu tentei com a VPN e os canais não voltaram a aparecer (uso ExpressVPN, antes usava SpiderVPN).
Não sabia que existia um Add-on chamado BRGuide do Olavo. Onde acho ele ? Na mesma pasta do BRPlay ?
Abs

**Comment by digaogt** [comment]
Entao, @joutinho. Desde a metade do ano passado que os canais globosat e globoplay unificaram o login. Quando vc acessava pela pagina web, ele informava a unificação e pedia para escolher o email de login. Isso foi mencionado na [issue 76](https://github.com/olavopeixoto/plugin.video.brplay/issues/76)
Quanto ao BRGuide, o arquivo zip dele está no repositorio do brplayer](https://github.com/olavopeixoto/repository.brplayer/tree/master/script.brguide)
Abs.

**Comment by pprado** [comment]
@digaogt @joutinho 

Eu fiz um downgrade do Kodi 18 RC 5.2 para o Kodi 18 RC 4 e todos os canais voltaram a funcionar. Deve ter tido algum problema no processo de atualização.

[]'s

**Comment by CaioTheBrain** [comment]
@oceanodrs

Isso tem a ver com o inputstream.adaptive. 

Qual a versão do Kodi você está usando? 

Se for a versão 17, tem que habilitar nas configurações do Kodi.

**Comment by oceanodrs** [comment]
@CaioTheBrain 

Obrigado pela dica. Mas porque não aparece na lista de canais ao vivo o Premiere? Aparecem todos os ao vivo menos combate e pfc.
Valeu

**Comment by CaioTheBrain** [comment]
@oceanodrs

Se algum canal não estiver aparecendo, vá nas configurações do addon -> Geral -> Manutenção do Addon -> Limpar o Cache e Limpar as Credenciais.

Dê OK e abra o addon novamente. 

Se não adiantar, volte para as Configurações -> Geral -> Globosat Play -> ative Ignorar Autorização de Canais.

Dê OK e faça um novo teste. 

Isso faz com que o addon liste todos os canais, mesmo que você não tenha acesso.

**Comment by oceanodrs** [comment]
@CaioTheBrain 
Mais uma vez obrigado. Os canais agora apareceram. Mas ao acessar  o combato ou pfc por ex aparece a mensagem de erro: Falha na reprodução - Recurso de vídeo não encontrado. Desculpe a pergunta, mas é necessário eu ser assinante destes canais? Se for, qual o intuito de assisti-los via kodi, já que poderia ser por qualquer outra plataforma?
Valeu

**Comment by CaioTheBrain** [comment]
@oceanodrs

Sim, precisa ser assinante. 

O intuito deste addon não é obter acesso não autorizado.

Ele serve tanto para usufruir do conteúdo em plataformas onde não há app disponível (Somente recentemente saiu app do Premiere para Android TV e Globosat Play não tem até agora, por exemplo), como para quem quer centralizar tudo no Kodi, mesmo podendo acessar cada app individualmente.

**Comment by oceanodrs** [comment]
@CaioTheBrain 

Ok, entendi. Mas voltando a dica anterior, referente a parar a transmissão aos 5 min. Ao habilitar o inputstream.adaptive ocorre erro ao acessar conteúdo ao vivo: Falha na Reprodução - Verifique o Log. E o único canal ao vivo que aparece é a Globo. Se desabilitar o inputstream.adaptive o canal trava após 5 min. O que poderia ser? A versão dele é a 1.0.8.

**Comment by CaioTheBrain** [comment]
@oceanodrs

Atualiza o Kodi pra ver se resolve. 

Aqui eu estou com as seguintes versões:

Kodi 18.1
InputStream Adaptive 2.3.15
BR Play 0.0.22

**Comment by joutinho** [comment]
@CaioTheBrain 
Não entendo o seguinte. Você disse acima que está usando a versão BR play 0.0.22 mas na página do Olavo a última versão oficial é a 0.0.14 
Como é isso ?
https://github.com/olavopeixoto/plugin.video.brplay/releases

**Comment by pprado** [comment]
Nesse link que vc postou, só ficam as releases, ou seja, versões que foram
definidas como estáveis para seus recursos.

Vai na página principal e clique em "clone or download", baixe no formato
zip e instale ele no Kodi.

https://github.com/olavopeixoto/plugin.video.brplay

[]'s

Em seg, 18 de fev de 2019 às 10:37, joutinho <notifications@github.com>
escreveu:

**Comment by oceanodrs** [comment]
@CaioTheBrain 

Atualizei tudo, mas a mesma situação continua. Só que agora só a globo carrega... outros canais ao vivo não carregam e ocorre o mesmo erro: Falha na Reprodução. Estando o InputStream Adaptive ativado ou não. E canais sob demanda nem aparecem.
Agradeço;


> @oceanodrs
> 
> Atualiza o Kodi pra ver se resolve.
> 
> Aqui eu estou com as seguintes versões:
> 
> Kodi 18.1
> InputStream Adaptive 2.3.15
> BR Play 0.0.22
