### ISSUE TITLE
Globoplay erro de autenticação

### ISSUE THREAD

**Issue by jorgeallyson** [olavopeixoto/plugin.video.brplay#94]
Estou usando o LibreElec 9.0.1, Kodi 18 num Raspberry Pi 2
O acesso ao Globoplay não funcionou diretamente. Ao olhar o log vi que estava dando erro de autenticação. Fui no navegador, fiz o login com as mesmas credenciais e funcionou. Peguei então o GLBID gerado no navegador e coloquei fixo no retorno da função _authenticate do arquivo lib/modules/globoplay/auth.py e a partir daí consegui tocar o vídeo ao vivo, que é mesmo o único que meu login tem acesso. Parece que mudou alguma coisa na forma de conseguir o GLBID. Vi que o payload na função _authenticate não inclui o campo fingerprint. Esse campo existe na requisição quando loguei pelo navegador. Segue o arquivo com as informações do login que fiz pelo navegador. 
[globoplay.globo.com.har.txt](https://github.com/olavopeixoto/plugin.video.brplay/files/3061319/globoplay.globo.com.har.txt)

**Comment by amaurigsilva** [comment]
A mais de uma semana, somente os canais Globosat pararam de funcionar, de repente.

**Comment by amaurigsilva** [comment]
Quando tento abrir um canal Globosat aparece a seguinte mensagem : "Um ou mais itens falharam na execução. Por favor verifique o log para mais informações sobre esta mensagem.' Estou usando KODY 17.6 na MIBOX 3.

**Comment by amaurigsilva** [comment]
A mais de uma semana, somente os canais Globosat pararam de funcionar, de repente. Os canais Globo RJ, BH, DF, PE, SP e MAN, funcionam normalmente. Estou usando o KODI 17.6 na MIBOX 3 e 4.

**Comment by amaurigsilva** [comment]
A mais de uma semana, somente os canais Globosat pararam de funcionar, de repente. Os canais Globo RJ, BH, DF, PE, SP e MAN, funcionam normalmente. Estou usando o KODI 17.6 na MIBOX 3 e 4.

**Comment by amaurigsilva** [comment]
Os canais Globosat pararam de funcionar no KODI 17.6 na MIBOX 3 e 4.

**Comment by jorgeallyson** [comment]
Bem, aqui nunca funcionou o Globosat, tentei fazer o mesmo que fiz com o Globoplay, colocando as credenciais do Globosat que peguei no navegador mas não deu resultado. Não sei se os dois problemas são relacionados.

**Comment by olavopeixoto** [comment]
Você usa as mesmas crendenciais para o globoplay e globosat?

Havia um bug para credenciais distintas, resolvido na ultima versão. Verifica se ajuda no seu problema.

**Comment by jorgeallyson** [comment]
Uso o mesmo login e senha para os dois. Já faz tempo que não testo, assim que tiver um tempo vou verificar se estou com a versão mais nova. Caso não esteja vou atualizar e testar novamente.

**Comment by jorgeallyson** [comment]
Depois de muito tempo, como minha antena parou de funcionar de novo, atualizei o Libreelec, adaptive stream e, depois disso os canais globosat apareceram pela primeira vez. Ficou faltando o ao vivo do globoplay, que era o principal. Neste caso tive que selecionar a afiliada na configuração e, por fim funcionou. Obrigado.
