### ISSUE TITLE
Erro no plugin

### ISSUE THREAD

**Issue by OneFeaR** [olavopeixoto/plugin.video.brplay#96]
Em primeiro lugar, agradeço pelo desenvolvimento desse plugin. Ajuda demais!

Sou usuário iniciante aqui e no Kodi. Uso a versão 18.5 do programa.

O erro acontece apenas em canais ao vivo, independente de qual eu escolha. Às vezes volta sozinho (mais raro), e quando buga a maioria dos canais, tenho que desinstalar o plugin, instalar de novo e volta a funcionar. No entanto, o problema volta a se repetir... Então vim buscar ajuda, pois não sei se é problema com o plugin, programa e afins.  Já fiz o processo de apagar o cachê e as credenciais também.

Segue print do relatório do erro em questão:

https://i.imgur.com/tXkyEu0.jpg

https://i.imgur.com/phKGNvu.jpg

https://i.imgur.com/65oYaCg.jpg

Existe solução para o problema?

*PS: O login e senha funciona normalmente pelo navegador.

Link para a visualização completa: https://drive.google.com/file/d/1VtvvUBq-LDCe9y4bjVDTwwIhJ-PfgP_c/view?usp=sharing

**Comment by GustavoOS** [comment]
Consegue copiar o texto do exception e colar aqui?

**Comment by GustavoOS** [comment]
Aparentemente se trata do mesmo erro dessa [issue](https://github.com/olavopeixoto/plugin.video.brplay/issues/101)

**Comment by GustavoOS** [comment]
@olavopeixoto Seria o mesmo erro da [issue](https://github.com/olavopeixoto/plugin.video.brplay/issues/101) ?

**Comment by GustavoOS** [comment]
O erro foi consertado pelo [commit](https://github.com/olavopeixoto/plugin.video.brplay/commit/7a0c78b40fd896e4b55b0359b3c4f62e99805ddf#diff-7b837fb110345ae0f28be08f5c40bc87). Mas ainda não entrou numa versão de release, cuja última versão é de 2017 @olavopeixoto
