### ISSUE TITLE
CANAIS GLOBOSAT ?

### ISSUE THREAD

**Issue by joaokemmer** [olavopeixoto/plugin.video.brplay#97]
ja tentei varios procedimentos, mas só ta funcionando as Globo
os demais canais, sportv, premiere, etc não aparece mais na lista, tenho login q funciona no aplicativo no celular, mas no kodi não funciona.. tenho o login associado da globo, mas nada funciona, mais alguem , como concertar.. ja limpei cache, credenciais, desinstalei kodi reinstalei, todas versões e nada.. alguma luz ai?

**Comment by RafaelMoreiraa** [comment]
Então, instalei o Brplay no Kodi nova versão. Fiz o login com a conta do globo.com atrelado a operadora de TV, porém só consigo visualizar conteúdo dos canais Globo. Os demais como Off, Premiere.. está em off. 

Está ocorrendo isso com vocês ?

**Comment by olavopeixoto** [comment]
Atualiza pra ultima versão 0.0.25, por favor

**Comment by RafaelMoreiraa** [comment]
Consegui visualizar a maioria dos canais, faltou instalar o input video adaptative no Kodi 18 Leia.

Vou atualizar a versão do app, vlw !!

**Comment by hcisilio** [comment]
Acabei de atualizar o plugin conforme o master do projeto e ainda não consigo acesso aos canais sportv e premiere. Inclusive só os vejo na lista de canais ao vivo se eu habilitar a opção ignorar autorização de canais (vejo porém não reproduz).
Há algum formato específico para informar login e senha? Utilizo o mesmo e-mail e senha que estou informando no kodi no navegador e consigo ver normalmente, apenas no kodi não  funciona.

**Comment by olavopeixoto** [comment]
Essa URL não é "navegável" (não aceita GET), pra funcionar tem que usar o método POST.
Ela existe porque retornou 401 com o seu login.
Não sei exatamente qual o problema no seu caso só consigo saber que as credenciais não estão funcionando.
Qual o seu provedor?
Você fez o cadastro no globo.com e vinculou o seu provedor?
O login e senha tem que ser do globo.com

**Comment by hcisilio** [comment]
sim, fiz o login primeiramente com a conta sky (meu provedor) e depois vinculei meu email. mas utilizo meu email normaal (@live) e não globo.com

**Comment by hcisilio** [comment]
Então, meu provedor é sky e vinculei a conta sim. Consegui fazr funcionar e relatar a situação toda, quem sabe pode ajudar

- eu tenho um e-mail @live vinculado a conta sky e que eu coloquei pra configurar no kodi

- minha prima tem uma conta @globo também vinculada a esta mesma conta sky e também é uma conta do globoplay

- eu estava fazendo a seguinte configuração: colocando a conta da minha prima para globplay e a minha para globosat (desmarcando a opção de usar a conta globoplay para globosat). Fiz isso porque marcando a opção par ausar a conta globoplay para globosat não funcionou

- Então mantive desmarcada a opção de usar a conta globoplay para globosat e coloquei manualmente a minha conta @live para login nos 2 (globoplay e globosat)

- Dessa forma fucionou.

- Segue o print da configuração:
![Screenshot_20190923_234235](https://user-images.githubusercontent.com/8618281/65477239-0c865b00-de5c-11e9-9a29-f238179c4a5a.png)

- Por ultimo, vale informar que essa conta @live não tem acesso ao globoplay. apenas ao globosatplay
