### ISSUE TITLE
No module named simplewriter

### ISSUE THREAD

**Issue by digaogt** [olavopeixoto/plugin.video.brplay#98]
Oi, Olavo. Tudo bem contigo?

Quando eu tento usar o BRPlay em modo Adaptive / Redirect, ele está gerando um exception.ImportError na falta de um módulo chamado simplewriter.

O módulo deveria estar na parta resources.lib.hlsproxy.simplewriter (vc comentou a linha "from resources.lib.hlsproxy.hlswriter import HLSWriter" / # player = HLSWriter no módulo hlshelper.py)

Tentei achar um módulo no qual vc se embasou, de mesmo nome na internet, sem sucesso.

O dispositivo que estou usando é um Nvidia Shield TV.

Abraços.

**Comment by olavopeixoto** [comment]
Opa, obrigado por avisar. O commit foi com o arquivo indevido sem querer, já consertei.
Mas vale avisar que esse modo alternativo não está muito testado e pode ter bugs.

**Comment by digaogt** [comment]
Esse SimpleWriter funciona com o mesmo HLS Proxy anterior do https://www.hls-proxy.com/ ou é de algum server distinto?

**Comment by olavopeixoto** [comment]
Nenhum serviço externo, so uns testes locais tentando melhorar a estabilidade dos streams.
