### ISSUE TITLE
Video na integra nao encontrado

### ISSUE THREAD

**Issue by joutinho** [olavopeixoto/plugin.video.brplay#99]
Oi Pessoal,
Instalei o BRPlay 0.0.26 no Nvidia Shield TV, coloquei meu login e senha e o seguinte esta acontecendo.
Aparecem 3 opções pra mim
- Live TV (clico na globo mas apesar de ler o que esta sendo transmitido nada acontece, o video não carrega mas também não da nenhum erro)
- On Demand - So aparece Futura e Globo. Na Globo da pra ver varias coisas como os Jornais e Novelas. No entanto so consigo ver os trechos pequenos e nenhum na integra. Se eu clico na Integra o Kodi me da um erro dizendo que o arquivo não foi encontrado.
Meu input adaptive esta ativo.
Alguém consegue me dar uma orientação por favor ? 
Obrigado desde ja !

**Comment by olavopeixoto** [comment]
Aparentemente algum problema com o seu login.
Pra ajudar preciso do log pra entender o problema.

**Comment by bruno-briner** [comment]
@joutinho : Você é assinante do GloboPlay? Se não o for, você somente conseguirá assistir os trechos pequenos.

Quanto à transmissão ao vivo não lembro se é possível assistir sem ser assinante, mas se você não estiver em um local onde o serviço não é disponível, o feed é bloqueado.
